### ISSUE TITLE
problem with redis upon creating container

### ISSUE THREAD

**Issue by brackendalebrewing** [infiniflow/ragflow#1023]
### Describe your problem

hi
I previously hag ragflow working with law documents and I was very impressed.

I updated the ragflow and now have problems with redis.
i did change the web app port to 8085:80 this is the only change, I am on ubuntu 22.04 
the web app runs i added openai api key , there is a redis key error in system 

[+] Running 10/10
 ✔ Network docker_ragflow      Created                                     0.0s 
 ✔ Volume "docker_mysql_data"  Created                                     0.0s 
 ✔ Volume "docker_minio_data"  Created                                     0.0s 
 ✔ Volume "docker_redis_data"  Created                                     0.0s 
 ✔ Volume "docker_esdata01"    Created                                     0.0s 
 ✔ Container ragflow-redis     Started                                     0.9s 
 ✔ Container ragflow-es-01     Healthy                                    21.6s 
 ✔ Container ragflow-minio     Started                                     1.0s 
 ✔ Container ragflow-mysql     Healthy                                    11.6s 
 ✔ Container ragflow-server    Started                                    21.7s 
[WARNING] [2024-05-31 17:45:45,788] [synonym.__init__] [line:24]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-05-31 17:45:45,895] [synonym.__init__] [line:24]: Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!

$ docker ps
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED          STATUS                    PORTS                                                                NAMES
b1f87d421bd9   infiniflow/ragflow:v0.7.0                              "./entrypoint.sh"        31 minutes ago   Up 31 minutes             0.0.0.0:443->443/tcp, 0.0.0.0:9380->9380/tcp, 0.0.0.0:8085->80/tcp   ragflow-server
a926dc1deb51   docker.elastic.co/elasticsearch/elasticsearch:8.11.3   "/bin/tini -- /usr/l…"   31 minutes ago   Up 31 minutes (healthy)   9300/tcp, 0.0.0.0:1200->9200/tcp                                     ragflow-es-01
6c8932c0ece2   redis:7.2.4                                            "docker-entrypoint.s…"   31 minutes ago   Up 31 minutes             6379/tcp                                                             ragflow-redis
5bfdcac4bb6a   mysql:5.7.18                                           "docker-entrypoint.s…"   31 minutes ago   Up 31 minutes (healthy)   0.0.0.0:5455->3306/tcp                                               ragflow-mysql
efccc12cbea2   quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z       "/usr/bin/docker-ent…"   31 minutes ago   Up 31 minutes             0.0.0.0:9000-9001->9000-9001/tcp                                     ragflow-minio

**Comment by stephenlzc** [comment]
+1

When I install RagFlow in my Windows 11 with python 3.11 and Docker Desktop( Current version: 4.29.0 (145265)) in my WSL Ubuntu.  After running 
`docker compose -f docker-compose-CN.yml up -d`

I get the erroe message below.

> root@cong:/mnt/e/ragflow/docker# docker compose -f docker-compose-CN.yml up -d
[+] Running 6/6
 ✔ Network docker_ragflow    Created                                                                               0.0s
 ✔ Container ragflow-redis   Started                                                                               0.1s
 ✔ Container ragflow-mysql   Created                                                                               0.1s
 ✔ Container ragflow-minio   Started                                                                               0.1s
 ✔ Container ragflow-es-01   Created                                                                               0.1s
 ✔ Container ragflow-server  Created                                                                               0.1s
Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:1200 -> 0.0.0.0:0: listen tcp 0.0.0.0:1200: bind: An attempt was made to access a socket in a way forbidden by its access permissions.


The log from ragflow-es-01 shows an error message as 
>(HTTP code 500) server error - Ports are not available: exposing port TCP 0.0.0.0:1200 -> 0.0.0.0:0: listen tcp 0.0.0.0:1200: bind: An attempt was made to access a socket in a way forbidden by its access permissions. 

please help me to figure out this problem. Many Thanks.

**Comment by KevinHuSh** [comment]
> 5bfdcac4bb6a mysql:5.7.18 "docker-entrypoint.s…"

I don't see any error in the log. Did I miss something?
Redis is use for parsing task schecule. So, ignore it if parsing is running well.

**Comment by KevinHuSh** [comment]
> +1
> 
> When I install RagFlow in my Windows 11 with python 3.11 and Docker Desktop( Current version: 4.29.0 (145265)) in my WSL Ubuntu. After running `docker compose -f docker-compose-CN.yml up -d`
> 
> I get the erroe message below.
> 
> > [+] Running 10/10
> > ✔ Network ragflow_ragflow      Created                                                                                                                                                                                                                                            0.0s
> > ✔ Volume "ragflow_redis_data"  Created                                                                                                                                                                                                                                            0.0s
> > ✔ Volume "ragflow_esdata01"    Created                                                                                                                                                                                                                                            0.0s
> > ✔ Volume "ragflow_mysql_data"  Created                                                                                                                                                                                                                                            0.0s
> > ✔ Volume "ragflow_minio_data"  Created                                                                                                                                                                                                                                            0.0s
> > ✔ Container ragflow-minio      Started                                                                                                                                                                                                                                            0.2s
> > ✔ Container ragflow-redis      Started                                                                                                                                                                                                                                            0.2s
> > ✔ Container ragflow-es-01      Created                                                                                                                                                                                                                                            0.1s
> > ✔ Container ragflow-mysql      Created                                                                                                                                                                                                                                            0.2s
> > ✔ Container ragflow-server     Created                                                                                                                                                                                                                                            0.1s
> > Error response from daemon: Ports are not available: exposing port TCP 0.0.0.0:1200 -> 0.0.0.0:0: listen tcp 0.0.0.0:1200: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
> 
> The log from ragflow-es-01 shows an error message as
> 
> > (HTTP code 500) server error - Ports are not available: exposing port TCP 0.0.0.0:1200 -> 0.0.0.0:0: listen tcp 0.0.0.0:1200: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
> 
> Error log:
> 
> > Fail to connect to es: Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7fe5dc9fa620>: Failed to resolve 'es01' ([Errno -2] Name or service not known)))
> 
> es.log
> 
> > Fail to connect to es: Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7fe5dc9fa620>: Failed to resolve 'es01' ([Errno -2] Name or service not known)))
> 
> Warning:
> 
> > Fail to connect to es: Connection error caused by: ConnectionError(Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7fe5dc9fa620>: Failed to resolve 'es01' ([Errno -2] Name or service not known)))
> 
> please help me to figure out this problem. Many Thanks.
> 
> @brackendalebrewing

1200 is forbidden by OS. Please google it, make it 1200 available.

**Comment by brackendalebrewing** [comment]
hi
Thanks for responding. I believe that redis updated and broke ragflow.  On
the redis git page i see that there was a may update.

I installed rag flow on bare metal on ubuntu 22.04 and 24.or and on looking
at the initial log " no redis connection"
on the app system screen there is a redis error "invalid key"

I will try to send the logs from that machine shortly

[image: PXL_20240603_015139863.jpg]

**Comment by brackendalebrewing** [comment]
Hi
here is more concerning the problem i am having with ragflow
[image: image.png]
database log
Can't update token usage for afc333d821cd11efb41f0242ac120006/EMBEDDING

error log
Can't update token usage for afc333d821cd11efb41f0242ac120006/EMBEDDING
401 Unauthorized: The server could not verify that you are authorized to
access the URL requested. You either supplied the wrong credentials (e.g. a
bad password), or your browser doesn't understand how to supply the
credentials required.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 870, in
full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 855, in
dispatch_request
    return
self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type:
ignore[no-any-return]
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line
285, in decorated_view
    return current_app.login_manager.unauthorized()
  File
"/usr/local/lib/python3.10/dist-packages/flask_login/login_manager.py",
line 178, in unauthorized
    abort(401)
  File "/usr/local/lib/python3.10/dist-packages/flask/helpers.py", line
272, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/exceptions.py",
line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.Unauthorized: 401 Unauthorized: The server could not
verify that you are authorized to access the URL requested. You either
supplied the wrong credentials (e.g. a bad password), or your browser
doesn't understand how to supply the credentials required.
401 Unauthorized: The server could not verify that you are authorized to
access the URL requested. You either supplied the wrong credentials (e.g. a
bad password), or your browser doesn't understand how to supply the
credentials required.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 870, in
full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 855, in
dispatch_request
    return
self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type:
ignore[no-any-return]
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line
285, in decorated_view
    return current_app.login_manager.unauthorized()
  File
"/usr/local/lib/python3.10/dist-packages/flask_login/login_manager.py",
line 178, in unauthorized
    abort(401)
  File "/usr/local/lib/python3.10/dist-packages/flask/helpers.py", line
272, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/exceptions.py",
line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.Unauthorized: 401 Unauthorized: The server could not
verify that you are authorized to access the URL requested. You either
supplied the wrong credentials (e.g. a bad password), or your browser
doesn't understand how to supply the credentials required.
Fail put 191c5b3421ce11efb46b0242ac120006/Punta Plata Rules and
RegulationsApproved at Extraordinary Meeting March142020(3).pdf: S3
operation failed; code: NoSuchBucket, message: The specified bucket does
not exist, resource: /191c5b3421ce11efb46b0242ac120006, request_id:
17D58E872118BF47, host_id:
dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8,
bucket_name: 191c5b3421ce11efb46b0242ac120006

minio log

Fail put 191c5b3421ce11efb46b0242ac120006/Punta Plata Rules and
RegulationsApproved at Extraordinary Meeting March142020(3).pdf: S3
operation failed; code: NoSuchBucket, message: The specified bucket does
not exist, resource: /191c5b3421ce11efb46b0242ac120006, request_id:
17D58E872118BF47, host_id:
dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8,
bucket_name: 191c5b3421ce11efb46b0242ac120006

stat log

Fail put 191c5b3421ce11efb46b0242ac120006/Punta Plata Rules and
RegulationsApproved at Extraordinary Meeting March142020(3).pdf: S3
operation failed; code: NoSuchBucket, message: The specified bucket does
not exist, resource: /191c5b3421ce11efb46b0242ac120006, request_id:
17D58E872118BF47, host_id:
dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8,
bucket_name: 191c5b3421ce11efb46b0242ac120006

warning log

Can't update token usage for afc333d821cd11efb41f0242ac120006/EMBEDDING
401 Unauthorized: The server could not verify that you are authorized to
access the URL requested. You either supplied the wrong credentials (e.g. a
bad password), or your browser doesn't understand how to supply the
credentials required.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 870, in
full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 855, in
dispatch_request
    return
self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type:
ignore[no-any-return]
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line
285, in decorated_view
    return current_app.login_manager.unauthorized()
  File
"/usr/local/lib/python3.10/dist-packages/flask_login/login_manager.py",
line 178, in unauthorized
    abort(401)
  File "/usr/local/lib/python3.10/dist-packages/flask/helpers.py", line
272, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/exceptions.py",
line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.Unauthorized: 401 Unauthorized: The server could not
verify that you are authorized to access the URL requested. You either
supplied the wrong credentials (e.g. a bad password), or your browser
doesn't understand how to supply the credentials required.
401 Unauthorized: The server could not verify that you are authorized to
access the URL requested. You either supplied the wrong credentials (e.g. a
bad password), or your browser doesn't understand how to supply the
credentials required.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 870, in
full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 855, in
dispatch_request
    return
self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type:
ignore[no-any-return]
  File "/usr/local/lib/python3.10/dist-packages/flask_login/utils.py", line
285, in decorated_view
    return current_app.login_manager.unauthorized()
  File
"/usr/local/lib/python3.10/dist-packages/flask_login/login_manager.py",
line 178, in unauthorized
    abort(401)
  File "/usr/local/lib/python3.10/dist-packages/flask/helpers.py", line
272, in abort
    current_app.aborter(code, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/werkzeug/exceptions.py",
line 861, in __call__
    raise self.mapping[code](*args, **kwargs)
werkzeug.exceptions.Unauthorized: 401 Unauthorized: The server could not
verify that you are authorized to access the URL requested. You either
supplied the wrong credentials (e.g. a bad password), or your browser
doesn't understand how to supply the credentials required.
Fail put 191c5b3421ce11efb46b0242ac120006/Punta Plata Rules and
RegulationsApproved at Extraordinary Meeting March142020(3).pdf: S3
operation failed; code: NoSuchBucket, message: The specified bucket does
not exist, resource: /191c5b3421ce11efb46b0242ac120006, request_id:
17D58E872118BF47, host_id:
dd9025bab4ad464b049177c95eb6ebf374d3b3fd1af9251148b658df7ac2e3e8,
bucket_name: 191c5b3421ce11efb46b0242ac120006

**Comment by tslyellow** [comment]
> +1
> 
> 当我在 Windows 11 中使用 python 3.11 和 Docker Desktop（当前版本：4.29.0 （145265））在我的 WSL Ubuntu 中安装 RagFlow 时。运行后 `docker compose -f docker-compose-CN.yml up -d`
> 
> 我在下面收到 erroe 消息。
> 
> > [+]运行 10/10 ✔ 网络ragflow_ragflow 创建 0.0s ✔ 卷“ragflow_redis_data” 创建 0.0s ✔ 卷“ragflow_esdata01” 创建 0.0s ✔ 卷“ragflow_mysql_data” 创建 0.0s ✔ 卷“ragflow_minio_data” 创建 0.0s ✔ 容器 ragflow-minio 启动 0.2s ✔ 容器 ragflow-redis 启动 0.2s ✔ 容器 ragflow-es-01 创建 0.1s ✔ 容器 ragflow-mysql 创建 0.2s✔ 容器 ragflow-server 创建 0.1s 来自守护程序的错误响应：端口不可用：暴露端口 TCP 0.0.0.0：1200 -> 0.0.0.0：0：0：监听 TCP 0.0.0.0：1200：bind：尝试以套接字访问权限禁止的方式访问套接字。
> 
> ragflow-es-01 中的日志显示错误消息为
> 
> > （HTTP 代码 500） 服务器错误 - 端口不可用：公开端口 TCP 0.0.0.0：1200 -> 0.0.0.0：0：侦听 tcp 0.0.0.0：1200：bind：尝试以套接字的访问权限禁止的方式访问套接字。
> 
> 错误日志：
> 
> > 无法连接到 es：连接错误导致的：ConnectionError（连接错误导致：NameResolutionError（< 0x7fe5dc9fa620> 处的 urllib3.connection.HTTPConnection 对象：无法解析“es01”（[Errno -2] 名称或服务未知）））
> 
> es.log
> 
> > 无法连接到 es：连接错误导致的：ConnectionError（连接错误导致：NameResolutionError（< 0x7fe5dc9fa620> 处的 urllib3.connection.HTTPConnection 对象：无法解析“es01”（[Errno -2] 名称或服务未知）））
> 
> 警告：
> 
> > 无法连接到 es：连接错误导致的：ConnectionError（连接错误导致：NameResolutionError（< 0x7fe5dc9fa620> 处的 urllib3.connection.HTTPConnection 对象：无法解析“es01”（[Errno -2] 名称或服务未知）））
> 
> 请帮我解决这个问题。非常感谢。
> 
> @brackendalebrewing

Dude, have you solved this problem yet? About the interface 1200.
![0956e0032253e7d9790a36dc730c37a](https://github.com/infiniflow/ragflow/assets/97387908/57b5b023-71a5-4eec-8fae-667275f70c12)

**Comment by KevinHuSh** [comment]
1200 is forbidden by OS.

**Comment by Kevin30Huang** [comment]
Change the docker-compose-base.yaml under in  .\ragflow\docker to a specific number to solve port 1200 issue.
![image](https://github.com/user-attachments/assets/6c0d62cb-a4d1-4e22-8e22-6ab9e24e047a)

**Comment by wycoal** [comment]
how to solve the problem?

**Comment by wycoal** [comment]
> Change the docker-compose-base.yaml under in .\ragflow\docker to a specific number to solve port 1200 issue. ![image](https://github.com/user-attachments/assets/6c0d62cb-a4d1-4e22-8e22-6ab9e24e047a)

the esport is 9200,are you sure it is the right one to modify?

**Comment by Morningstars666** [comment]
you should change ES_PORT in .env

**Comment by henrygaoy** [comment]
试试在“启用和关闭windows功能”里不要勾选“适用于Linux的Windows子系统”

**Comment by kenny-chen** [comment]
`docker network connect docker_ragflow docker-redis-1`
Try to move **docker-redis-1** to **docker_ragflow**. It works for me.
