### ISSUE TITLE
[Question]: The file can not be parsed, has been stuck in parsing, even for a day or two without any change。

### ISSUE THREAD

**Issue by Romanzhang2024** [infiniflow/ragflow#1091]
### Describe your problem

I select the corresponding knowledge base on the web page, upload multiple PDF files, start one or more file parsing, often appear stuck in the parsing (one or two days do not change), open the background log, loop the following error and warning information, please help locate the specific problem, thank you!

**Comment by Romanzhang2024** [comment]
Loops of warnings and error messages：
[WARNING] [2024-06-07 03:15:36,354] [synonym.__init__] [line:24]: Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 375, in <module>
    main()
  File "/ragflow/rag/svr/task_executor.py", line 294, in main
    rows = collect()
  File "/ragflow/rag/svr/task_executor.py", line 117, in collect
    assert tasks, "{} empty task!".format(msg["id"])
AssertionError: b89fcce8247811ef99fa0242ac120003 empty task!
[WARNING] [2024-06-07 03:15:56,104] [synonym.__init__] [line:24]: Realtime synonym is disabled, since no redis connection.
[INFO] [2024-06-07 03:15:56,703] [_internal._log] [line:96]: 172.18.0.6 - - [07/Jun/2024 03:15:56] "GET /v1/document/list?kb_id=6529d8601f2311efa1140242ac120006&page=1&page_size=10 HTTP/1.1" 200 -
[WARNING] Load term.freq FAIL!
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 375, in <module>
    main()
  File "/ragflow/rag/svr/task_executor.py", line 294, in main
    rows = collect()
  File "/ragflow/rag/svr/task_executor.py", line 117, in collect
    assert tasks, "{} empty task!".format(msg["id"])
AssertionError: b89fcd4c247811ef99fa0242ac120003 empty task!
[WARNING] [2024-06-07 03:16:16,005] [synonym.__init__] [line:24]: Realtime synonym is disabled, since no redis connection.

**Comment by KevinHuSh** [comment]
> Loops of warnings and error messages： [WARNING] [2024-06-07 03:15:36,354] [synonym.**init**] [line:24]: Realtime synonym is disabled, since no redis connection. [WARNING] Load term.freq FAIL! Traceback (most recent call last): File "/ragflow/rag/svr/task_executor.py", line 375, in main() File "/ragflow/rag/svr/task_executor.py", line 294, in main rows = collect() File "/ragflow/rag/svr/task_executor.py", line 117, in collect assert tasks, "{} empty task!".format(msg["id"]) AssertionError: b89fcce8247811ef99fa0242ac120003 empty task! [WARNING] [2024-06-07 03:15:56,104] [synonym.**init**] [line:24]: Realtime synonym is disabled, since no redis connection. [INFO] [2024-06-07 03:15:56,703] [_internal._log] [line:96]: 172.18.0.6 - - [07/Jun/2024 03:15:56] "GET /v1/document/list?kb_id=6529d8601f2311efa1140242ac120006&page=1&page_size=10 HTTP/1.1" 200 - [WARNING] Load term.freq FAIL! Traceback (most recent call last): File "/ragflow/rag/svr/task_executor.py", line 375, in main() File "/ragflow/rag/svr/task_executor.py", line 294, in main rows = collect() File "/ragflow/rag/svr/task_executor.py", line 117, in collect assert tasks, "{} empty task!".format(msg["id"]) AssertionError: b89fcd4c247811ef99fa0242ac120003 empty task! [WARNING] [2024-06-07 03:16:16,005] [synonym.**init**] [line:24]: Realtime synonym is disabled, since no redis connection.

This happens when the data is dirty after restarting ragflow. Ignore them, and cancel the task on the web page.

**Comment by Romanzhang2024** [comment]
1、The configuration file docker-compose.yml in the docker directory has specified that two GPU resources A10 are used
deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0','1']              
            capabilities: [gpu]
2、Look at the web page parsing progress bar (progress 40.91%, experienced about 5 hours，Long time no change) prompt message, found the following Loop  error：
Page(85~97): [ERROR]Embedding error:Account abnormal. Please ensure it's on good standing.
Page(97~109): [ERROR]Embedding error:Account abnormal. Please ensure it's on good standing.

**Comment by KevinHuSh** [comment]
> 1、The configuration file docker-compose.yml in the docker directory has specified that two GPU resources A10 are used deploy: resources: reservations: devices: - driver: nvidia device_ids: ['0','1'] capabilities: [gpu] 2、Look at the web page parsing progress bar (progress 40.91%, experienced about 5 hours，Long time no change) prompt message, found the following Loop error： Page(85~97): [ERROR]Embedding error:Account abnormal. Please ensure it's on good standing. Page(97~109): [ERROR]Embedding error:Account abnormal. Please ensure it's on good standing.

Please check the status of embedding you've choosen. Is it based on SaaS. If it is, you need to set API key in system settings.

**Comment by Romanzhang2024** [comment]
I have configured The LLM factory（service_conf.yaml：user_default_llm, ali:Tongyi-Qianwen ） and the corresponding api_key.

**Comment by DiaQusNet** [comment]
Have you solved this yet? I've encountered the same problem too.

**Comment by aixiaozou** [comment]
也是同样的问题

**Comment by KevinHuSh** [comment]
> I have configured The LLM factory（service_conf.yaml：user_default_llm, ali:Tongyi-Qianwen ） and the corresponding api_key.

After changing user_default_llm, it is effective only for new registered user.

**Comment by zz290-yapper** [comment]
我也出现这样的情况，还请有人能否解决一下，尝试了很多次  除非清除数据重新加载

**Comment by FinTechCao** [comment]
> 我也出现这样的情况，还请有人能否解决一下，尝试了很多次 除非清除数据重新加载

我也遇到了同样的问题，也有好几个帖子报告了这个问题。但是他们拒绝承认这是bug，一直在说等等就好了。我的结论跟你一样，只有清除所有数据才能行

**Comment by JinHai-CN** [comment]
Fixed by #2094
