### ISSUE TITLE
[Bug]: AssertionError: cf9f5a6c267b11efa54d0242ac120006 empty task!

### ISSUE THREAD

**Issue by chicken8848** [infiniflow/ragflow#1108]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

f900e43

### Other environment information

```Markdown
Arch Linux
```

### Actual behavior

Was running fine until I cancelled a job halfway, then could no longer parse any files, could still chat with the bot.
Running `docker compose down` followed by `docker compose up -d` did not seem to fix the issue. Also did a full system restart.

When I run `docker compose up -d`:
```
 ✔ Network docker_ragflow    Created                                                                                                     0.0s 
 ✔ Container ragflow-minio   Started                                                                                                     0.4s 
 ✔ Container ragflow-redis   Started                                                                                                     0.4s 
 ✔ Container ragflow-es-01   Healthy                                                                                                    21.0s 
 ✔ Container ragflow-mysql   Healthy                                                                                                    11.0s 
 ✔ Container ragflow-server  Started  
```

### Expected behavior

Expected to parse documents again normally like usual.

### Steps to reproduce

```Markdown
Had about 8 documents lined up to be parsed, cancelled halfway using bulk cancel.
```

### Additional information

Keep getting this on a loop, can't parse anything
```
2024-06-10 01:33:20 ragflow-server  | [WARNING] Load term.freq FAIL!
2024-06-10 01:33:20 ragflow-server  | Traceback (most recent call last):
2024-06-10 01:33:20 ragflow-server  |   File "/ragflow/rag/svr/task_executor.py", line 375, in <module>
2024-06-10 01:33:20 ragflow-server  |     main()
2024-06-10 01:33:20 ragflow-server  |   File "/ragflow/rag/svr/task_executor.py", line 294, in main
2024-06-10 01:33:20 ragflow-server  |     rows = collect()
2024-06-10 01:33:20 ragflow-server  |   File "/ragflow/rag/svr/task_executor.py", line 117, in collect
2024-06-10 01:33:20 ragflow-server  |     assert tasks, "{} empty task!".format(msg["id"])
2024-06-10 01:33:20 ragflow-server  | AssertionError: cf9f62e6267b11efa54d0242ac120006 empty task!
2024-06-10 01:33:20 ragflow-mysql   | 2024-06-09T17:33:20.960905Z 149 [Note] Aborted connection 149 to db: 'rag_flow' user: 'root' host: '172.19.0.6' (Got an error reading communication packets)
```

Here's my docker-compose:

```
include:
  - path: ./docker-compose-base.yml
    env_file: ./.env

services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
      es01:
        condition: service_healthy
    image: infiniflow/ragflow:${RAGFLOW_VERSION}
    container_name: ragflow-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 8080:80
      - 8443:443
    volumes:
      - ./entrypoint.sh:/ragflow/entrypoint.sh
      - ./service_conf.yaml:/ragflow/conf/service_conf.yaml
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=${TIMEZONE}
      - HF_ENDPOINT=https://huggingface.co
    networks:
      - ragflow
    restart: always
```
And my docker-compose-base:

```
services:
  es01:
    container_name: ragflow-es-01
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=es01
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - bootstrap.memory_lock=false
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - TZ=${TIMEZONE}
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
    networks:
      - ragflow
    restart: always

  mysql:
    image: mysql:5.7.18
    container_name: ragflow-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - TZ=${TIMEZONE}
    command:
      --max_connections=1000
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --default-authentication-plugin=mysql_native_password
      --tls_version="TLSv1.2,TLSv1.3"
      --init-file /data/application/init.sql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    networks:
      - ragflow
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-p${MYSQL_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 3
    restart: always

  minio:
    image: quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z
    container_name: ragflow-minio
    command: server --console-address ":9001" /data
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    environment:
      - MINIO_ROOT_USER=${MINIO_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_PASSWORD}
      - TZ=${TIMEZONE}
    volumes:
      - minio_data:/data
    networks:
      - ragflow
    restart: always

  redis:
    image: redis:7.2.4
    container_name: ragflow-redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - redis_data:/data
    networks:
      - ragflow
    restart: always



volumes:
  esdata01:
    driver: local
  mysql_data:
    driver: local
  minio_data:
    driver: local
  redis_data:
    driver: local

networks:
  ragflow:
    driver: bridge
```
logs from ragflow-mysql:
```2024-06-09T17:39:05.023773Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2024-06-09T17:39:05.025156Z 0 [Note] mysqld (mysqld 5.7.18) starting as process 1 ...
2024-06-09T17:39:05.027244Z 0 [Note] InnoDB: PUNCH HOLE support available
2024-06-09T17:39:05.027261Z 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2024-06-09T17:39:05.027265Z 0 [Note] InnoDB: Uses event mutexes
2024-06-09T17:39:05.027267Z 0 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
2024-06-09T17:39:05.027270Z 0 [Note] InnoDB: Compressed tables use zlib 1.2.3
2024-06-09T17:39:05.027273Z 0 [Note] InnoDB: Using Linux native AIO
2024-06-09T17:39:05.027752Z 0 [Note] InnoDB: Number of pools: 1
2024-06-09T17:39:05.027843Z 0 [Note] InnoDB: Using CPU crc32 instructions
2024-06-09T17:39:05.029368Z 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
2024-06-09T17:39:05.034911Z 0 [Note] InnoDB: Completed initialization of buffer pool
2024-06-09T17:39:05.036557Z 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2024-06-09T17:39:05.048226Z 0 [Note] InnoDB: Highest supported file format is Barracuda.
2024-06-09T17:39:05.058979Z 0 [Note] InnoDB: Creating shared tablespace for temporary tables
2024-06-09T17:39:05.059018Z 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2024-06-09T17:39:05.080116Z 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2024-06-09T17:39:05.080615Z 0 [Note] InnoDB: 96 redo rollback segment(s) found. 96 redo rollback segment(s) are active.
2024-06-09T17:39:05.080625Z 0 [Note] InnoDB: 32 non-redo rollback segment(s) are active.
2024-06-09T17:39:05.081055Z 0 [Note] InnoDB: 5.7.18 started; log sequence number 254632629
2024-06-09T17:39:05.081381Z 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2024-06-09T17:39:05.081462Z 0 [Note] Plugin 'FEDERATED' is disabled.
2024-06-09T17:39:05.082665Z 0 [Note] InnoDB: Buffer pool(s) load completed at 240610  1:39:05
2024-06-09T17:39:05.084419Z 0 [Note] Found ca.pem, server-cert.pem and server-key.pem in data directory. Trying to enable SSL support using them.
2024-06-09T17:39:05.084439Z 0 [Warning] Failed to set up SSL because of the following SSL library error: TLS version is invalid
2024-06-09T17:39:05.084766Z 0 [Note] Server hostname (bind-address): '*'; port: 3306
2024-06-09T17:39:05.084794Z 0 [Note] IPv6 is available.
2024-06-09T17:39:05.084802Z 0 [Note]   - '::' resolves to '::';
2024-06-09T17:39:05.084812Z 0 [Note] Server socket created on IP: '::'.
2024-06-09T17:39:05.089431Z 0 [Warning] 'user' entry 'root@localhost' ignored in --skip-name-resolve mode.
2024-06-09T17:39:05.089449Z 0 [Warning] 'user' entry 'mysql.sys@localhost' ignored in --skip-name-resolve mode.
2024-06-09T17:39:05.089461Z 0 [Warning] 'db' entry 'sys mysql.sys@localhost' ignored in --skip-name-resolve mode.
2024-06-09T17:39:05.089467Z 0 [Warning] 'proxies_priv' entry '@ root@localhost' ignored in --skip-name-resolve mode.
2024-06-09T17:39:05.092015Z 0 [Warning] 'tables_priv' entry 'sys_config mysql.sys@localhost' ignored in --skip-name-resolve mode.
2024-06-09T17:39:05.098710Z 0 [Note] Event Scheduler: Loaded 0 events
2024-06-09T17:39:05.098793Z 0 [Note] Execution of init_file '/data/application/init.sql' started.
2024-06-09T17:39:05.099316Z 0 [Note] Execution of init_file '/data/application/init.sql' ended.
2024-06-09T17:39:05.099372Z 0 [Note] mysqld: ready for connections.
Version: '5.7.18'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server (GPL)
2024-06-09T17:39:05.099382Z 0 [Note] Executing 'SELECT * FROM INFORMATION_SCHEMA.TABLES;' to get a list of tables using the deprecated partition engine. You may use the startup option '--disable-partition-engine-check' to skip this check. 
2024-06-09T17:39:05.099385Z 0 [Note] Beginning of list of non-natively partitioned tables
2024-06-09T17:39:05.105957Z 0 [Note] End of list of non-natively partitioned tables
2024-06-09T17:39:40.925978Z 9 [Note] Aborted connection 9 to db: 'rag_flow' user: 'root' host: '172.20.0.6' (Got an error reading communication packets)
2024-06-09T17:39:51.629651Z 11 [Note] Aborted connection 11 to db: 'rag_flow' user: 'root' host: '172.20.0.6' (Got an error reading communication packets)
2024-06-09T17:40:02.108021Z 13 [Note] Aborted connection 13 to db: 'rag_flow' user: 'root' host: '172.20.0.6' (Got an error reading communication packets)
2024-06-09T17:40:12.599498Z 16 [Note] Aborted connection 16 to db: 'rag_flow' user: 'root' host: '172.20.0.6' (Got an error reading communication packets)
2024-06-09T17:40:23.250884Z 18 [Note] Aborted connection 18 to db: 'rag_flow' user: 'root' host: '172.20.0.6' (Got an error reading communication packets)
2024-06-09T17:40:33.984283Z 20 [Note] Aborted connection 20 to db: 'rag_flow' user: 'root' host: '172.20.0.6' (Got an error reading communication packets)
2024-06-09T17:40:44.693481Z 23 [Note] Aborted connection 23 to db: 'rag_flow' user: 'root' host: '172.20.0.6' (Got an error reading communication packets)
2024-06-09T17:40:55.240548Z 25 [Note] Aborted connection 25 to db: 'rag_flow' user: 'root' host: '172.20.0.6' (Got an error reading communication packets)
2024-06-09T17:41:05.724723Z 28 [Note] Aborted connection 28 to db: 'rag_flow' user: 'root' host: '172.20.0.6' (Got an error reading communication packets)
```

Any help would be great!! Thank youuuu

**Comment by chicken8848** [comment]
Nevermind found the issue, `expressvpn` was on the same port and enabling the daemon caused the problem. Thank you

**Comment by hehemagic** [comment]
How did you solve the problem? Can you elaborate on the problem?

**Comment by chicken8848** [comment]
Probably a problem where the task handler bugs out when you cancel large files, just simply wait awhile and it should timeout and you'll be able to use ragflow again. Never found a definitive answer but waiting always works

**Comment by alanOO7** [comment]
> 没关系，发现了问题，在同一个端口上，启用守护进程导致了问题。谢谢`expressvpn`

I have the same problem, how to solve it?
