### ISSUE TITLE
[Question]: unable to launch the RAGFlow backend service while launching service from source

### ISSUE THREAD

**Issue by ja3592** [infiniflow/ragflow#1118]
### Describe your problem

I have run the ragflow sucessfully through docker and the nginx server can be started up normally. BUT when I tried use the Launch Service from Source, I met some problems.

I modified the entrypoint.sh file as follows:
![问题](https://github.com/infiniflow/ragflow/assets/42410824/d335794e-f5b0-478d-860d-df0e7ad7bd18)

when I run the follow scripts:
"chmod +x ./entrypoint.sh
 bash ./entrypoint.sh"

problems happend:
[WARNING] [2024-06-11 18:25:32,265] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 1 times in a row, putting on 1 second timeout
[WARNING] [2024-06-11 18:25:32,265] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 1 times in a row, putting on 1 second timeout
[WARNING] [2024-06-11 18:25:32,266] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 0 of 3)
Traceback (most recent call last):
  File "/home/ja/anaconda3/envs/ragflow/lib/python3.11/site-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ja/anaconda3/envs/ragflow/lib/python3.11/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7fb3057e0510>: Failed to resolve 'es01' ([Errno -2] Name or service not known))
[WARNING] [2024-06-11 18:25:32,265] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 0 of 3)
Traceback (most recent call last):
  File "/home/ja/anaconda3/envs/ragflow/lib/python3.11/site-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ja/anaconda3/envs/ragflow/lib/python3.11/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f720e772650>: Failed to resolve 'es01' ([Errno -2] Name or service not known))
[WARNING] [2024-06-11 18:25:33,337] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 2 times in a row, putting on 2 second timeout

Please give some guidance and help, Thank you!

**Comment by JinHai-CN** [comment]
RAGFlow can't connect with ES.

1. check if ES docker server is up.
2. check if the port is set correctly.

FAQ document also mention this problem.

**Comment by KevinHuSh** [comment]
Check every host in conf/service_conf.yml. Change them to 127.0.0.1. And mind the ports in conf/service_conf.yml. Make sure these ports are available outside the docker container.
