### ISSUE TITLE
[Question]: Running sudo bash ./entrypoint.sh reports an error

### ISSUE THREAD

**Issue by Old-Lane** [infiniflow/ragflow#1266]
### Describe your problem

- I want to start the project with source code for secondary development, but it is too difficult to start it.
- I have seen similar issues, but they don't work for me.
- The code is yesterday's main branch.
- The following is the error message：
```bash
[WARNING] Load term.freq FAIL!
[WARNING] Load term.freq FAIL!
[WARNING] [2024-06-25 09:27:12,237] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-06-25 09:27:12,237] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
Traceback (most recent call last):
  File "/mnt/c/home/oldlane/program/rag/ragflow/api/ragflow_server.py", line 26, in <module>
    from api.apps import app
  File "/mnt/c/home/oldlane/program/rag/ragflow/api/apps/__init__.py", line 96, in <module>
    client_urls_prefix = [
                         ^
  File "/mnt/c/home/oldlane/program/rag/ragflow/api/apps/__init__.py", line 97, in <listcomp>
    register_page(path)
  File "/mnt/c/home/oldlane/program/rag/ragflow/api/apps/__init__.py", line 83, in register_page
    spec.loader.exec_module(page)
  File "/mnt/c/home/oldlane/program/rag/ragflow/api/apps/api_app.py", line 27, in <module>
    from api.db.services.dialog_service import DialogService, chat
  File "/mnt/c/home/oldlane/program/rag/ragflow/api/db/services/dialog_service.py", line 25, in <module>
    from rag.app.resume import forbidden_select_fields4resume
  File "/mnt/c/home/oldlane/program/rag/ragflow/rag/app/resume.py", line 23, in <module>
    from deepdoc.parser.resume import step_one, step_two
  File "/mnt/c/home/oldlane/program/rag/ragflow/deepdoc/parser/resume/step_two.py", line 17, in <module>
    from deepdoc.parser.resume.entities import degrees, schools, corporations
  File "/mnt/c/home/oldlane/program/rag/ragflow/deepdoc/parser/resume/entities/corporations.py", line 65, in <module>
    GOOD_CORP = set([corpNorm(rmNoise(c), False) for c in GOOD_CORP])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/home/oldlane/program/rag/ragflow/deepdoc/parser/resume/entities/corporations.py", line 65, in <listcomp>
    GOOD_CORP = set([corpNorm(rmNoise(c), False) for c in GOOD_CORP])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/home/oldlane/program/rag/ragflow/deepdoc/parser/resume/entities/corporations.py", line 45, in corpNorm
    tks = rag_tokenizer.tokenize(nm).split(" ")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/home/oldlane/program/rag/ragflow/rag/nlp/rag_tokenizer.py", line 266, in tokenize
    return " ".join([self.stemmer.stem(self.lemmatizer.lemmatize(t)) for t in word_tokenize(line)])
                                                                              ^^^^^^^^^^^^^^^^^^^
  File "/home/oldlane/anaconda3/envs/ragflow/lib/python3.11/site-packages/nltk/tokenize/__init__.py", line 129, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldlane/anaconda3/envs/ragflow/lib/python3.11/site-packages/nltk/tokenize/__init__.py", line 106, in sent_tokenize
    tokenizer = load(f"tokenizers/punkt/{language}.pickle")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldlane/anaconda3/envs/ragflow/lib/python3.11/site-packages/nltk/data.py", line 750, in load
    opened_resource = _open(resource_url)
                      ^^^^^^^^^^^^^^^^^^^
  File "/home/oldlane/anaconda3/envs/ragflow/lib/python3.11/site-packages/nltk/data.py", line 876, in _open
    return find(path_, path + [""]).open()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldlane/anaconda3/envs/ragflow/lib/python3.11/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/PY3/english.pickle

  Searched in:
    - '/root/nltk_data'
    - '/home/oldlane/anaconda3/envs/ragflow/nltk_data'
    - '/home/oldlane/anaconda3/envs/ragflow/share/nltk_data'
    - '/home/oldlane/anaconda3/envs/ragflow/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************

Traceback (most recent call last):
  File "/mnt/c/home/oldlaneTraceback (most recent call last):
  File "/mnt/c/home/oldlane/program/rag/ragflow/rag/svr/task_executor.py", line 48, in <module>
    from rag.app import law/program/rag/ragflow/rag/svr/task_executor.py", line 48, in <module>
    from rag.app import laws, paper, presentation, manual, qa, table, book, resume, picture, naive, one
  File "/mnt/c/home/oldlane/program/rag/ragflow/rag/app/resume.py", line 23, in <module>
    from deepdoc.parser.resume import step_one, step_two
  File "/mnt/c/home/oldlane/program/rag/ragflow/deepdoc/parser/resume/step_two.py", line 17, in <module>
    from deepdoc.parser.resume.entities import degrees, schools, corporations
  File "/mnt/c/home/oldlane/program/rag/ragflow/deepdoc/parser/resume/entities/corporations.py", line 65, in <module>
    GOOD_CORP = set([corpNorm(rmNoise(c), False) for c in GOOD_CORP])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/home/oldlane/program/rag/ragflow/deepdoc/parser/resume/entities/corporations.py", line 65, in <listcomp>
    GOOD_CORP = set([corpNorm(rmNoise(c), False) for c in GOOD_CORP])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/home/oldlane/program/rag/ragflow/deepdoc/parser/resume/entities/corporations.py", line 45, in corpNorm
    tks = rag_tokenizer.tokenize(nm).split(" ")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/home/oldlane/program/rag/ragflow/rag/nlp/rag_tokenizer.py", line 266, in tokenize
    return " ".join([self.stemmer.stem(self.lemmatizer.lemmatize(t)) for t in word_tokenize(line)])
                                                                              ^^^^^^^^^^^^^^^^^^^
  File "/home/oldlane/anaconda3/envs/ragflow/lib/python3.11/site-packages/nltk/tokenize/__init__.py", line 129, in word_tokenize
    sentences = [text] if preserve_line else sent_tokenize(text, language)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldlane/anaconda3/envs/ragflow/lib/python3.11/site-packages/nltk/tokenize/__init__.py", line 106, in sent_tokenize
    tokenizer = load(f"tokenizers/punkt/{language}.pickle")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldlane/anaconda3/envs/ragflow/lib/python3.11/site-packages/nltk/data.py", line 750, in load
    opened_resource = _open(resource_url)
                      ^^^^^^^^^^^^^^^^^^^
  File "/home/oldlane/anaconda3/envs/ragflow/lib/python3.11/site-packages/nltk/data.py", line 876, in _open
    return find(path_, path + [""]).open()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oldlane/anaconda3/envs/ragflow/lib/python3.11/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError:
**********************************************************************
  Resource punkt not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('punkt')

  For more information see: https://www.nltk.org/data.html

  Attempted to load tokenizers/punkt/PY3/english.pickle

  Searched in:
    - '/root/nltk_data'
    - '/home/oldlane/anaconda3/envs/ragflow/nltk_data'
    - '/home/oldlane/anaconda3/envs/ragflow/share/nltk_data'
    - '/home/oldlane/anaconda3/envs/ragflow/lib/nltk_data'
    - '/usr/share/nltk_data'
    - '/usr/local/share/nltk_data'
    - '/usr/lib/nltk_data'
    - '/usr/local/lib/nltk_data'
    - ''
**********************************************************************
```

**Comment by lzj0322** [comment]
did you solve this issue?

**Comment by Old-Lane** [comment]
> did you solve this issue?

Run Command
```bash
python -c "import nltk;nltk.download('punkt');nltk.download('wordnet')"
```
You will see the download path and you can see that it is not in the scanned path
Just use the mv command to move it

**Comment by quack-gaga** [comment]
> > did you solve this issue?
> 
> Run Command
> 
> python -c "import nltk;nltk.download('punkt');nltk.download('wordnet')"
> You will see the download path and you can see that it is not in the scanned path Just use the mv command to move it

Thanks! I use this command and solved this issue
