### ISSUE TITLE
[Question]: I only want to retrieve the recalled documents through the API, not the content of the Q&A. What should I do?

### ISSUE THREAD

**Issue by wanyuks** [infiniflow/ragflow#1476]
### Describe your problem

I only want to retrieve the recalled documents through the API, not the content of the Q&A. What should I do?

**Comment by KevinHuSh** [comment]
You can get document by "doc_id". Have a look at preview of file on web UI.

**Comment by wanyuks** [comment]
Yes, I have tried.But I can't get the result. My request is below:
````python
base_url = "http://localhost/v1/api/dataset"
headers = {"Authorization":  MY_KEY}
paras = {
            "offset": 0,
            "count": -1,
            "orderby": "create_time",
            "desc": True
        }
res = requests.post(url=base_url, params=params, headers=headers)
``

The res.json() is 
```
{'data': None, 'retcode': 100, 'retmsg': "<NotFound '404: Not Found'>"}
```

I don't how to solve it.

**Comment by wanyuks** [comment]
> You can get document by "doc_id". Have a look at preview of file on web UI.

Yes, I have tried.But I can't get the result. My request is below:
```python
base_url = "http://localhost/v1/api/dataset"
headers = {"Authorization":  MY_KEY}
paras = {
            "offset": 0,
            "count": -1,
            "orderby": "create_time",
            "desc": True
        }
res = requests.post(url=base_url, params=params, headers=headers)
```

The res.json() is 
```
{'data': None, 'retcode': 100, 'retmsg': "<NotFound '404: Not Found'>"}
```

I don't how to solve it.

**Comment by KevinHuSh** [comment]
The base url seems to be wrong.
base_url = "http://localhost/api/v1/dataset"

**Comment by wanyuks** [comment]
> The base url seems to be wrong. base_url = "http://localhost/api/v1/dataset"

![image](https://github.com/user-attachments/assets/8549d21f-729b-4379-b784-103a881a1b0b)
The base_url I saw from the frontend is "http://localhost/v1/api/"

**Comment by wanyuks** [comment]
> The base url seems to be wrong. base_url = "http://localhost/api/v1/dataset"

And when I change the base_url to "http://localhost/api/v1/dataset", Another error has occurred when I print res.json()
```
Traceback (most recent call last):
  File "/home/wangjian/.conda/envs/db-gpt/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/wangjian/.conda/envs/db-gpt/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/wangjian/.conda/envs/db-gpt/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/wangjian/.conda/envs/db-gpt/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wangjian/workspace/KnowledgeQA/rangflow_test.py", line 25, in <module>
    print(res.json())
  File "/home/wangjian/.conda/envs/db-gpt/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by kaka36** [comment]
请问解决了么

**Comment by TTTnlp** [comment]
i have the same question

**Comment by elepherai** [comment]
same here
