### ISSUE TITLE
[Bug]: IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by liwan14x** [infiniflow/ragflow#1569]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

fe5dd5b

### Actual behavior

[WARNING] Load term.freq FAIL!
Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 26, in <module>
    from api.apps import app
  File "/ragflow/api/apps/__init__.py", line 96, in <module>
    client_urls_prefix = [
  File "/ragflow/api/apps/__init__.py", line 97, in <listcomp>
    register_page(path)
  File "/ragflow/api/apps/__init__.py", line 83, in register_page
    spec.loader.exec_module(page)
  File "/ragflow/api/apps/canvas_app.py", line 26, in <module>
    from graph.canvas import Canvas
  File "/ragflow/graph/canvas.py", line 25, in <module>
    from graph.component import component_class
  File "/ragflow/graph/component/__init__.py", line 13, in <module>
    from .duckduckgo import DuckDuckGo, DuckDuckGoParam
  File "/ragflow/graph/component/duckduckgo.py", line 60
    if not duck_res:
                    ^
IndentationError: unindent does not match any outer indentation level

I just update the code then use "docker logs -f ragflow-server" and encountered this error, I think it's a code issue

### Steps to reproduce

```Markdown
git pull
docker pull swr.cn-north-4.myhuaweicloud.com/infiniflow/ragflow:dev
docker compose -f docker-compose-CN.yml up -d
docker logs -f ragflow-server
```

**Comment by fanfanaqiuqiu** [comment]
我也遇到了这个问题

**Comment by narendra-bluebash** [comment]
I am also facing the same issue

**Comment by liwan14x** [comment]
This is a code issue and I checkout to pull the prod version then issue has been resolved.
docker pull swr.cn-north-4.myhuaweicloud.com/infiniflow/ragflow:latest
Will close this ticket and wait for dev team to fix it.

**Comment by hrchu** [comment]
this is why we need CI
