### ISSUE TITLE
[Question]: No objects to concatenate

### ISSUE THREAD

**Issue by water-2022** [infiniflow/ragflow#1697]
### Describe your problem

~~~
root@fce13cef52ca:/ragflow# PYTHONPATH=/ragflow python3 graph/test/client.py -t f4c90d7e2c5711efbe730242ac160006 -s graph/test/dsl_examples/headhunter_zh.json
[WARNING] Load term.freq FAIL!
[WARNING] [2024-07-25 10:55:08,126] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
Traceback (most recent call last):
  File "/ragflow/graph/test/client.py", line 37, in <module>
    ans = canvas.run(stream=args.stream)
  File "/ragflow/graph/canvas.py", line 238, in run
    ans = self.components[cpn_id]["obj"].run(self.history, **kwargs)
  File "/ragflow/graph/component/base.py", line 407, in run
    raise e
  File "/ragflow/graph/component/base.py", line 403, in run
    res = self._run(history, **kwargs)
  File "/ragflow/graph/component/answer.py", line 45, in _run
    ans = self.get_input()
  File "/ragflow/graph/component/base.py", line 463, in get_input
    return pd.concat(upstream_outs, ignore_index=False)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/reshape/concat.py", line 382, in concat
    op = _Concatenator(
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/reshape/concat.py", line 445, in __init__
    objs, keys = self._clean_keys_and_objs(objs, keys)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/reshape/concat.py", line 507, in _clean_keys_and_objs
    raise ValueError("No objects to concatenate")
ValueError: No objects to concatenate
~~~

I don't know why. I don't know what to do.

Thank you for your reply.

**Comment by KevinHuSh** [comment]
Please upgrade the ragflow to dev version of image and pull the latest code.

**Comment by water-2022** [comment]
@KevinHuSh new issue.

~~~
root@f781ec8ae537:/ragflow# PYTHONPATH=/ragflow python3 graph/test/client.py -t f4c90d7e2c5711efbe730242ac160006 -s graph/test/dsl_examples/headhunter_zh.json
[WARNING] Load term.freq FAIL!
[WARNING] [2024-07-25 03:49:16,323] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
==================== Bot =====================
>    Traceback (most recent call last):
  File "/ragflow/graph/test/client.py", line 45, in <module>
    print(ans["content"])
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/frame.py", line 4090, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.10/dist-packages/pandas/core/indexes/range.py", line 417, in get_loc
    raise KeyError(key)
KeyError: 'content'
~~~

**Comment by KevinHuSh** [comment]
You need to set a valid kb_id in dsl based on your local system.

**Comment by water-2022** [comment]
@KevinHuSh new issue.

![企业微信截图_17219601291220](https://github.com/user-attachments/assets/984481cc-1c20-4444-97c6-98d634226adc)

**Comment by which-W** [comment]
@water-2022 
Thanks a lot for your suggestion — and apologies for the delayed reply! 🙇‍♂️

We've recently restructured the project 🧱🔧 and would love to know if your issue has been resolved in the latest version. If it has, please go ahead and close this feature request ✅. If not, feel free to let us know what you're still experiencing!

Looking forward to more constructive feedback from you — thank you again! 🚀
