### ISSUE TITLE
[Bug]: Index dataset document failed

### ISSUE THREAD

**Issue by Lxx-c** [infiniflow/ragflow#1743]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

all

### Other environment information

```Markdown
windows11 x86_64
docker 26.1.1
```

### Actual behavior

The following is the error log. I directly used the process in the ReadME document to start the Docker service by ` docker compose - f docker compose CN. yml up - d `. Then I created a dataset and uploaded a PDF document, and it reported an error. According to the log, it says it cannot access Elasticsearch, but I can access it through the command line

```log
[INFO] [2024-07-30 03:51:12,492] [_internal._log] [line:96]: 172.23.0.6 - - [30/Jul/2024 03:51:12] "GET /v1/document/list?kb_id=1a2b4b0c4d8411ef81770242ac140006&page=1&page_size=10 HTTP/1.1" 200 -
./entrypoint.sh: line 12:   269 Killed                  $PY rag/svr/task_executor.py
[WARNING] [2024-07-30 03:51:24,406] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 1 times in a row, putting on 1 second timeout
[WARNING] [2024-07-30 03:51:24,406] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 0 of 3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f75efe43250>: Failed to establish a new connection: [Errno 111] Connection refused)
[WARNING] [2024-07-30 03:51:24,410] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 2 times in a row, putting on 2 second timeout
[WARNING] [2024-07-30 03:51:24,410] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 1 of 3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f75efe434f0>: Failed to establish a new connection: [Errno 111] Connection refused)
[WARNING] [2024-07-30 03:51:24,411] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 3 times in a row, putting on 4 second timeout
[WARNING] [2024-07-30 03:51:24,411] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 2 of 3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f75efe416f0>: Failed to establish a new connection: [Errno 111] Connection refused)
[WARNING] [2024-07-30 03:51:24,413] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 4 times in a row, putting on 8 second timeout
[WARNING] [2024-07-30 03:51:25,419] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 1 times in a row, putting on 1 second timeout
[WARNING] [2024-07-30 03:51:25,419] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 0 of 3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f75efe94d00>: Failed to establish a new connection: [Errno 111] Connection refused)
[WARNING] [2024-07-30 03:51:25,421] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 2 times in a row, putting on 2 second timeout
[WARNING] [2024-07-30 03:51:25,421] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 1 of 3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f75efe94eb0>: Failed to establish a new connection: [Errno 111] Connection refused)
[WARNING] [2024-07-30 03:51:25,423] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 3 times in a row, putting on 4 second timeout
[WARNING] [2024-07-30 03:51:25,423] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 2 of 3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7f75efe95120>: Failed to establish a new connection: [Errno 111] Connection refused)
[WARNING] [2024-07-30 03:51:25,424] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 4 times in a row, putting on 8 second timeout
[WARNING] [2024-07-30 03:51:26,429] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 1 times in a row, putting on 1 second timeout
[WARNING] [2024-07-30 03:51:26,429] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 0 of 3)



# curl http://es01:9200
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":["Basic realm=\"security\" charset=\"UTF-8\"","ApiKey"]}},"status":401}
```

### Steps to reproduce

```Markdown
cd /docker && docker compose -f docker-compose-CN.yml up -d
```

**Comment by Lxx-c** [comment]
Elastic's memory is not enough, it needs to be added in Docker configuration as' ES_JAVA-POTS=- Xms512m - Xmx512m '`
