### ISSUE TITLE
[Bug]: RuntimeError: no validator found for <class 'zhipuai.core._base_type.NotGiven'>, see `arbitrary_types_allowed` in Config

### ISSUE THREAD

**Issue by mayonggang** [infiniflow/ragflow#1775]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

c3b2a1

### Other environment information

```Markdown
OS: ubuntu
```

### Actual behavior

Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 26, in <module>
    from api.apps import app
  File "/ragflow/api/apps/__init__.py", line 96, in <module>
    client_urls_prefix = [
  File "/ragflow/api/apps/__init__.py", line 97, in <listcomp>
    register_page(path)
  File "/ragflow/api/apps/__init__.py", line 83, in register_page
    spec.loader.exec_module(page)
  File "/ragflow/api/apps/llm_app.py", line 18, in <module>
    from api.db.services.llm_service import LLMFactoriesService, TenantLLMService, LLMService
  File "/ragflow/api/db/services/llm_service.py", line 18, in <module>
    from rag.llm import EmbeddingModel, CvModel, ChatModel, RerankModel
  File "/ragflow/rag/llm/__init__.py", line 16, in <module>
    from .embedding_model import *
  File "/ragflow/rag/llm/embedding_model.py", line 22, in <module>
    from zhipuai import ZhipuAI
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/__init__.py", line 2, in <module>
    from ._client import ZhipuAI
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/_client.py", line 9, in <module>
    from .core._http_client import HttpClient, ZHIPUAI_DEFAULT_MAX_RETRIES
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/core/_http_client.py", line 21, in <module>
    from ._request_opt import ClientRequestParam, UserRequestInput
  File "/usr/local/lib/python3.10/dist-packages/zhipuai/core/_request_opt.py", line 25, in <module>
    class ClientRequestParam(pydantic.BaseModel):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 504, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 434, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 550, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 806, in pydantic.fields.ModelField._create_sub_type
  File "pydantic/fields.py", line 434, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 555, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 829, in pydantic.fields.ModelField.populate_validators
  File "pydantic/validators.py", line 765, in find_validators
RuntimeError: no validator found for <class 'zhipuai.core._base_type.NotGiven'>, see `arbitrary_types_allowed` in Config

### Expected behavior

ffff 

### Steps to reproduce

```Markdown
no thing
```

### Additional information

f  f f

**Comment by kaiwenbb** [comment]
+1

**Comment by KevinHuSh** [comment]
Do you install zhipuai==2.0.1?
It seems a version conflict.

**Comment by mayonggang** [comment]
> Do you install zhipuai==2.0.1? It seems a version conflict.
yes


# docker exec ragflow-server pip show zhipuai

Name: zhipuai
Version: 2.0.1
Summary: A SDK library for accessing big model apis from ZhipuAI
Home-page: https://open.bigmodel.cn/
Author: Zhipu AI
Author-email: 
License: 
Location: /usr/local/lib/python3.10/dist-packages
Requires: cachetools, httpx, pydantic, pyjwt
Required-by:

**Comment by KevinHuSh** [comment]
uninstall jina and reinstall zhipu,
