### ISSUE TITLE
[Question]: Running on docker WSL2

### ISSUE THREAD

**Issue by underlines** [infiniflow/ragflow#1789]
### Describe your problem

Hi,
I'm on Windows 11 using docker and WSL2 Ubuntu backend.

**1. I use the following config for WSL2:**
`.wslconfig`
```ini
[wsl2]
networkingMode=mirrored
```
**2. Then I follow the installation tutorial:**
```bash
git clone https://github.com/infiniflow/ragflow/
cd ragflow/docker
docker compose up -d
time="2024-08-02T10:32:50+02:00" level=warning msg="The \"MACOS\" variable is not set. Defaulting to a blank string."
[+] Running 5/5
 ✔ Container ragflow-minio   Running 0.0s
 ✔ Container ragflow-es-01   Healthy 0.5s
 ✔ Container ragflow-redis   Running 0.0s
 ✔ Container ragflow-mysql   Healthy 0.5s
 ✔ Container ragflow-server  Running 0.0s
```
This works and all containers are up and running.

**3. Redis connection issue**
The logs show ragflow can't connect to redis (I didn't make any configuration changes, everything is default):

```bash
docker logs -f ragflow-server
[WARNING] [2024-08-01 23:06:20,843] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-08-01 23:06:20,847] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 26, in <module>
    from api.apps import app
  File "/ragflow/api/apps/__init__.py", line 97, in <module>
    client_urls_prefix = [
  File "/ragflow/api/apps/__init__.py", line 98, in <listcomp>
    register_page(path)
  File "/ragflow/api/apps/__init__.py", line 84, in register_page
    spec.loader.exec_module(page)
  File "/ragflow/api/apps/canvas_app.py", line 26, in <module>
    from graph.canvas import Canvas
  File "/ragflow/graph/canvas.py", line 25, in <module>
    from graph.component import component_class
  File "/ragflow/graph/component/__init__.py", line 17, in <module>
    from .google import Google, GoogleParam
  File "/ragflow/graph/component/google.py", line 17, in <module>
    from serpapi import GoogleSearch
ModuleNotFoundError: No module named 'serpapi'
```

**4. Inspecting network issues, show no problems:**
I checked what the IP of ragflow-redis is via this command:
```bash
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ragflow-redis
172.19.0.2
```
Then I use curl (ping not available in ragflow-server) to see if ragflow-server can access ragflow-redis:
```bash
docker exec ragflow-server curl 172.19.0.2:6379
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server
```
So the connection works. There's no network issue to my understanding.

What could be the issue?

**Comment by KevinHuSh** [comment]
Fixed. Pull the dev version of image again.

**Comment by underlines** [comment]
I tried with the latest dev image and it works perfect now. :) Thank you
