### ISSUE TITLE
[Question]:  Why mysql container is not standing up using docker compose

### ISSUE THREAD

**Issue by tanerozel** [infiniflow/ragflow#1799]
Hi, I am starting the project using docker compose, all services are working but mysql container is not running. I use  Macbook m1

` ✘ Container ragflow-mysql                                                                                                                                Error0.0s 
 ! mysql The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested   0.0s 
 ✔ Container ragflow-server                                                                                                                               Created0.1s 
 ! ragflow The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s 
dependency failed to start: container ragflow-mysql is unhealth`

Mysql Logs:
`2024-08-03 11:33:59 runtime: failed to create new OS thread (have 2 already; errno=22)
2024-08-03 11:33:59 fatal error: newosproc
2024-08-03 11:33:59 
2024-08-03 11:33:59 runtime stack:
2024-08-03 11:33:59 runtime.throw(0x524da0, 0x9)
2024-08-03 11:33:59     /usr/local/go/src/runtime/panic.go:527 +0x90
2024-08-03 11:33:59 runtime.newosproc(0xc820034000, 0xc820043fc0)
2024-08-03 11:33:59     /usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
2024-08-03 11:33:59 runtime.newm(0x555ce8, 0x0)
2024-08-03 11:33:59     /usr/local/go/src/runtime/proc1.go:1105 +0x130
2024-08-03 11:33:59 runtime.main.func1()
2024-08-03 11:33:59     /usr/local/go/src/runtime/proc.go:48 +0x2c
2024-08-03 11:33:59 runtime.systemstack(0x5c4300)
2024-08-03 11:33:59     /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
2024-08-03 11:33:59 runtime.mstart()
2024-08-03 11:33:59     /usr/local/go/src/runtime/proc1.go:674
2024-08-03 11:33:59 
2024-08-03 11:33:59 goroutine 1 [running]:
2024-08-03 11:33:59 runtime.systemstack_switch()
2024-08-03 11:33:59     /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002e770 sp=0xc82002e768
2024-08-03 11:33:59 runtime.main()
2024-08-03 11:33:59     /usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc82002e7c0 sp=0xc82002e770
2024-08-03 11:33:59 runtime.goexit()
2024-08-03 11:33:59     /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
2024-08-03 11:34:00 runtime: failed to create new OS thread (have 2 already; errno=22)
2024-08-03 11:34:00 fatal error: newosproc
2024-08-03 11:34:00 
2024-08-03 11:34:00 runtime stack:
2024-08-03 11:34:00 runtime.throw(0x524da0, 0x9)
2024-08-03 11:34:00     /usr/local/go/src/runtime/panic.go:527 +0x90
2024-08-03 11:34:00 runtime.newosproc(0xc820034000, 0xc820043fc0)
2024-08-03 11:34:00     /usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
2024-08-03 11:34:00 runtime.newm(0x555ce8, 0x0)
2024-08-03 11:34:00     /usr/local/go/src/runtime/proc1.go:1105 +0x130
2024-08-03 11:34:00 runtime.main.func1()
2024-08-03 11:34:00     /usr/local/go/src/runtime/proc.go:48 +0x2c
2024-08-03 11:34:00 runtime.systemstack(0x5c4300)
2024-08-03 11:34:00     /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
2024-08-03 11:34:00 runtime.mstart()
2024-08-03 11:34:00     /usr/local/go/src/runtime/proc1.go:674
2024-08-03 11:34:00 
2024-08-03 11:34:00 goroutine 1 [running]:
2024-08-03 11:34:00 runtime.systemstack_switch()
2024-08-03 11:34:00     /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002e770 sp=0xc82002e768
2024-08-03 11:34:00 runtime.main()
2024-08-03 11:34:00     /usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc82002e7c0 sp=0xc82002e770
2024-08-03 11:34:00 runtime.goexit()
2024-08-03 11:34:00     /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
2024-08-03 11:34:01 runtime: failed to create new OS thread (have 2 already; errno=22)
2024-08-03 11:34:01 fatal error: newosproc
2024-08-03 11:34:01 
2024-08-03 11:34:01 runtime stack:
2024-08-03 11:34:01 runtime.throw(0x524da0, 0x9)
2024-08-03 11:34:01     /usr/local/go/src/runtime/panic.go:527 +0x90
2024-08-03 11:34:01 runtime.newosproc(0xc820034000, 0xc820043fc0)
2024-08-03 11:34:01     /usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
2024-08-03 11:34:01 runtime.newm(0x555ce8, 0x0)
2024-08-03 11:34:01     /usr/local/go/src/runtime/proc1.go:1105 +0x130
2024-08-03 11:34:01 runtime.main.func1()
2024-08-03 11:34:01     /usr/local/go/src/runtime/proc.go:48 +0x2c
2024-08-03 11:34:01 runtime.systemstack(0x5c4300)
2024-08-03 11:34:01     /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
2024-08-03 11:34:01 runtime.mstart()
2024-08-03 11:34:01     /usr/local/go/src/runtime/proc1.go:674
2024-08-03 11:34:01 
2024-08-03 11:34:01 goroutine 1 [running]:
2024-08-03 11:34:01 runtime.systemstack_switch()
2024-08-03 11:34:01     /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002e770 sp=0xc82002e768
2024-08-03 11:34:01 runtime.main()
2024-08-03 11:34:01     /usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc82002e7c0 sp=0xc82002e770
2024-08-03 11:34:01 runtime.goexit()
2024-08-03 11:34:01     /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
2024-08-03 11:34:02 runtime: failed to create new OS thread (have 2 already; errno=22)
2024-08-03 11:34:02 fatal error: newosproc
2024-08-03 11:34:02 
2024-08-03 11:34:02 runtime stack:
2024-08-03 11:34:02 runtime.throw(0x524da0, 0x9)
2024-08-03 11:34:02     /usr/local/go/src/runtime/panic.go:527 +0x90
2024-08-03 11:34:02 runtime.newosproc(0xc820034000, 0xc820043fc0)
2024-08-03 11:34:02     /usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
2024-08-03 11:34:02 runtime.newm(0x555ce8, 0x0)
2024-08-03 11:34:02     /usr/local/go/src/runtime/proc1.go:1105 +0x130
2024-08-03 11:34:02 runtime.main.func1()
2024-08-03 11:34:02     /usr/local/go/src/runtime/proc.go:48 +0x2c
2024-08-03 11:34:02 runtime.systemstack(0x5c4300)
2024-08-03 11:34:02     /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
2024-08-03 11:34:02 runtime.mstart()
2024-08-03 11:34:02     /usr/local/go/src/runtime/proc1.go:674
2024-08-03 11:34:02 
2024-08-03 11:34:02 goroutine 1 [running]:
2024-08-03 11:34:02 runtime.systemstack_switch()
2024-08-03 11:34:02     /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002e770 sp=0xc82002e768
2024-08-03 11:34:02 runtime.main()
2024-08-03 11:34:02     /usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc82002e7c0 sp=0xc82002e770
2024-08-03 11:34:02 runtime.goexit()
2024-08-03 11:34:02     /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
2024-08-03 11:34:06 runtime: failed to create new OS thread (have 2 already; errno=22)
2024-08-03 11:34:06 fatal error: newosproc
2024-08-03 11:34:06 
2024-08-03 11:34:06 runtime stack:
2024-08-03 11:34:06 runtime.throw(0x524da0, 0x9)
2024-08-03 11:34:06     /usr/local/go/src/runtime/panic.go:527 +0x90
2024-08-03 11:34:06 runtime.newosproc(0xc820034000, 0xc820043fc0)
2024-08-03 11:34:06     /usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
2024-08-03 11:34:06 runtime.newm(0x555ce8, 0x0)
2024-08-03 11:34:06     /usr/local/go/src/runtime/proc1.go:1105 +0x130
2024-08-03 11:34:06 runtime.main.func1()
2024-08-03 11:34:06     /usr/local/go/src/runtime/proc.go:48 +0x2c
2024-08-03 11:34:06 runtime.systemstack(0x5c4300)
2024-08-03 11:34:06     /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
2024-08-03 11:34:06 runtime.mstart()
2024-08-03 11:34:06     /usr/local/go/src/runtime/proc1.go:674
2024-08-03 11:34:06 
2024-08-03 11:34:06 goroutine 1 [running]:
2024-08-03 11:34:06 runtime.systemstack_switch()
2024-08-03 11:34:06     /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002e770 sp=0xc82002e768
2024-08-03 11:34:06 runtime.main()
2024-08-03 11:34:06     /usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc82002e7c0 sp=0xc82002e770
2024-08-03 11:34:06 runtime.goexit()
2024-08-03 11:34:06     /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
2024-08-03 11:34:08 runtime: failed to create new OS thread (have 2 already; errno=22)
2024-08-03 11:34:08 fatal error: newosproc
2024-08-03 11:34:08 
2024-08-03 11:34:08 runtime stack:
2024-08-03 11:34:08 runtime.throw(0x524da0, 0x9)
2024-08-03 11:34:08     /usr/local/go/src/runtime/panic.go:527 +0x90
2024-08-03 11:34:08 runtime.newosproc(0xc820034000, 0xc820043fc0)
2024-08-03 11:34:08     /usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
2024-08-03 11:34:08 runtime.newm(0x555ce8, 0x0)
2024-08-03 11:34:08     /usr/local/go/src/runtime/proc1.go:1105 +0x130
2024-08-03 11:34:08 runtime.main.func1()
2024-08-03 11:34:08     /usr/local/go/src/runtime/proc.go:48 +0x2c
2024-08-03 11:34:08 runtime.systemstack(0x5c4300)
2024-08-03 11:34:08     /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
2024-08-03 11:34:08 runtime.mstart()
2024-08-03 11:34:08     /usr/local/go/src/runtime/proc1.go:674
2024-08-03 11:34:08 
2024-08-03 11:34:08 goroutine 1 [running]:
2024-08-03 11:34:08 runtime.systemstack_switch()
2024-08-03 11:34:08     /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002e770 sp=0xc82002e768
2024-08-03 11:34:08 runtime.main()
2024-08-03 11:34:08     /usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc82002e7c0 sp=0xc82002e770
2024-08-03 11:34:08 runtime.goexit()
2024-08-03 11:34:08     /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
2024-08-03 11:34:13 runtime: failed to create new OS thread (have 2 already; errno=22)
2024-08-03 11:34:13 fatal error: newosproc
2024-08-03 11:34:13 
2024-08-03 11:34:13 runtime stack:
2024-08-03 11:34:13 runtime.throw(0x524da0, 0x9)
2024-08-03 11:34:13     /usr/local/go/src/runtime/panic.go:527 +0x90
2024-08-03 11:34:13 runtime.newosproc(0xc820034000, 0xc820043fc0)
2024-08-03 11:34:13     /usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
2024-08-03 11:34:13 runtime.newm(0x555ce8, 0x0)
2024-08-03 11:34:13     /usr/local/go/src/runtime/proc1.go:1105 +0x130
2024-08-03 11:34:13 runtime.main.func1()
2024-08-03 11:34:13     /usr/local/go/src/runtime/proc.go:48 +0x2c
2024-08-03 11:34:13 runtime.systemstack(0x5c4300)
2024-08-03 11:34:13     /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
2024-08-03 11:34:13 runtime.mstart()
2024-08-03 11:34:13     /usr/local/go/src/runtime/proc1.go:674
2024-08-03 11:34:13 
2024-08-03 11:34:13 goroutine 1 [running]:
2024-08-03 11:34:13 runtime.systemstack_switch()
2024-08-03 11:34:13     /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002e770 sp=0xc82002e768
2024-08-03 11:34:13 runtime.main()
2024-08-03 11:34:13     /usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc82002e7c0 sp=0xc82002e770
2024-08-03 11:34:13 runtime.goexit()
2024-08-03 11:34:13     /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
2024-08-03 11:34:20 runtime: failed to create new OS thread (have 2 already; errno=22)
2024-08-03 11:34:20 fatal error: newosproc
2024-08-03 11:34:20 
2024-08-03 11:34:20 runtime stack:
2024-08-03 11:34:20 runtime.throw(0x524da0, 0x9)
2024-08-03 11:34:20     /usr/local/go/src/runtime/panic.go:527 +0x90
2024-08-03 11:34:20 runtime.newosproc(0xc820034000, 0xc820043fc0)
2024-08-03 11:34:20     /usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
2024-08-03 11:34:20 runtime.newm(0x555ce8, 0x0)
2024-08-03 11:34:20     /usr/local/go/src/runtime/proc1.go:1105 +0x130
2024-08-03 11:34:20 runtime.main.func1()
2024-08-03 11:34:20     /usr/local/go/src/runtime/proc.go:48 +0x2c
2024-08-03 11:34:20 runtime.systemstack(0x5c4300)
2024-08-03 11:34:20     /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
2024-08-03 11:34:20 runtime.mstart()
2024-08-03 11:34:20     /usr/local/go/src/runtime/proc1.go:674
2024-08-03 11:34:20 
2024-08-03 11:34:20 goroutine 1 [running]:
2024-08-03 11:34:20 runtime.systemstack_switch()
2024-08-03 11:34:20     /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002e770 sp=0xc82002e768
2024-08-03 11:34:20 runtime.main()
2024-08-03 11:34:20     /usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc82002e7c0 sp=0xc82002e770
2024-08-03 11:34:20 runtime.goexit()
2024-08-03 11:34:20     /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
2024-08-03 11:34:34 runtime: failed to create new OS thread (have 2 already; errno=22)
2024-08-03 11:34:34 fatal error: newosproc
2024-08-03 11:34:34 
2024-08-03 11:34:34 runtime stack:
2024-08-03 11:34:34 runtime.throw(0x524da0, 0x9)
2024-08-03 11:34:34     /usr/local/go/src/runtime/panic.go:527 +0x90
2024-08-03 11:34:34 runtime.newosproc(0xc820034000, 0xc820043fc0)
2024-08-03 11:34:34     /usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
2024-08-03 11:34:34 runtime.newm(0x555ce8, 0x0)
2024-08-03 11:34:34     /usr/local/go/src/runtime/proc1.go:1105 +0x130
2024-08-03 11:34:34 runtime.main.func1()
2024-08-03 11:34:34     /usr/local/go/src/runtime/proc.go:48 +0x2c
2024-08-03 11:34:34 runtime.systemstack(0x5c4300)
2024-08-03 11:34:34     /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
2024-08-03 11:34:34 runtime.mstart()
2024-08-03 11:34:34     /usr/local/go/src/runtime/proc1.go:674
2024-08-03 11:34:34 
2024-08-03 11:34:34 goroutine 1 [running]:
2024-08-03 11:34:34 runtime.systemstack_switch()
2024-08-03 11:34:34     /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002e770 sp=0xc82002e768
2024-08-03 11:34:34 runtime.main()
2024-08-03 11:34:34     /usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc82002e7c0 sp=0xc82002e770
2024-08-03 11:34:34 runtime.goexit()
2024-08-03 11:34:34     /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
2024-08-03 11:35:00 runtime: failed to create new OS thread (have 2 already; errno=22)
2024-08-03 11:35:00 fatal error: newosproc
2024-08-03 11:35:00 
2024-08-03 11:35:00 runtime stack:
2024-08-03 11:35:00 runtime.throw(0x524da0, 0x9)
2024-08-03 11:35:00     /usr/local/go/src/runtime/panic.go:527 +0x90
2024-08-03 11:35:00 runtime.newosproc(0xc820034000, 0xc820043fc0)
2024-08-03 11:35:00     /usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
2024-08-03 11:35:00 runtime.newm(0x555ce8, 0x0)
2024-08-03 11:35:00     /usr/local/go/src/runtime/proc1.go:1105 +0x130
2024-08-03 11:35:00 runtime.main.func1()
2024-08-03 11:35:00     /usr/local/go/src/runtime/proc.go:48 +0x2c
2024-08-03 11:35:00 runtime.systemstack(0x5c4300)
2024-08-03 11:35:00     /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
2024-08-03 11:35:00 runtime.mstart()
2024-08-03 11:35:00     /usr/local/go/src/runtime/proc1.go:674
2024-08-03 11:35:00 
2024-08-03 11:35:00 goroutine 1 [running]:
2024-08-03 11:35:00 runtime.systemstack_switch()
2024-08-03 11:35:00     /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002e770 sp=0xc82002e768
2024-08-03 11:35:00 runtime.main()
2024-08-03 11:35:00     /usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc82002e7c0 sp=0xc82002e770
2024-08-03 11:35:00 runtime.goexit()
2024-08-03 11:35:00     /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
2024-08-03 11:35:52 runtime: failed to create new OS thread (have 2 already; errno=22)
2024-08-03 11:35:52 fatal error: newosproc
2024-08-03 11:35:52 
2024-08-03 11:35:52 runtime stack:
2024-08-03 11:35:52 runtime.throw(0x524da0, 0x9)
2024-08-03 11:35:52     /usr/local/go/src/runtime/panic.go:527 +0x90
2024-08-03 11:35:52 runtime.newosproc(0xc820034000, 0xc820043fc0)
2024-08-03 11:35:52     /usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
2024-08-03 11:35:52 runtime.newm(0x555ce8, 0x0)
2024-08-03 11:35:52     /usr/local/go/src/runtime/proc1.go:1105 +0x130
2024-08-03 11:35:52 runtime.main.func1()
2024-08-03 11:35:52     /usr/local/go/src/runtime/proc.go:48 +0x2c
2024-08-03 11:35:52 runtime.systemstack(0x5c4300)
2024-08-03 11:35:52     /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
2024-08-03 11:35:52 runtime.mstart()
2024-08-03 11:35:52     /usr/local/go/src/runtime/proc1.go:674
2024-08-03 11:35:52 
2024-08-03 11:35:52 goroutine 1 [running]:
2024-08-03 11:35:52 runtime.systemstack_switch()
2024-08-03 11:35:52     /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002e770 sp=0xc82002e768
2024-08-03 11:35:52 runtime.main()
2024-08-03 11:35:52     /usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc82002e7c0 sp=0xc82002e770
2024-08-03 11:35:52 runtime.goexit()
2024-08-03 11:35:52     /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
2024-08-03 11:36:52 runtime: failed to create new OS thread (have 2 already; errno=22)
2024-08-03 11:36:52 fatal error: newosproc
2024-08-03 11:36:52 
2024-08-03 11:36:52 runtime stack:
2024-08-03 11:36:52 runtime.throw(0x524da0, 0x9)
2024-08-03 11:36:52     /usr/local/go/src/runtime/panic.go:527 +0x90
2024-08-03 11:36:52 runtime.newosproc(0xc820034000, 0xc820043fc0)
2024-08-03 11:36:52     /usr/local/go/src/runtime/os1_linux.go:150 +0x1ab
2024-08-03 11:36:52 runtime.newm(0x555ce8, 0x0)
2024-08-03 11:36:52     /usr/local/go/src/runtime/proc1.go:1105 +0x130
2024-08-03 11:36:52 runtime.main.func1()
2024-08-03 11:36:52     /usr/local/go/src/runtime/proc.go:48 +0x2c
2024-08-03 11:36:52 runtime.systemstack(0x5c4300)
2024-08-03 11:36:52     /usr/local/go/src/runtime/asm_amd64.s:262 +0x79
2024-08-03 11:36:52 runtime.mstart()
2024-08-03 11:36:52     /usr/local/go/src/runtime/proc1.go:674
2024-08-03 11:36:52 
2024-08-03 11:36:52 goroutine 1 [running]:
2024-08-03 11:36:52 runtime.systemstack_switch()
2024-08-03 11:36:52     /usr/local/go/src/runtime/asm_amd64.s:216 fp=0xc82002e770 sp=0xc82002e768
2024-08-03 11:36:52 runtime.main()
2024-08-03 11:36:52     /usr/local/go/src/runtime/proc.go:49 +0x62 fp=0xc82002e7c0 sp=0xc82002e770
2024-08-03 11:36:52 runtime.goexit()
2024-08-03 11:36:52     /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1 fp=0xc82002e7c8 sp=0xc82002e7c0
`

**Comment by KevinHuSh** [comment]
Is it on MACOS.  Change it to mariaDB, and set MACOS=1 in docker/.env

**Comment by tanerozel** [comment]
@KevinHuSh 
I tried it before and it didn't work, and now I tried it again and it didn't work.
Why can't we find a radical solution to this? This problem is experienced by many people.
Can we use postgresql instead of mysql?
