### ISSUE TITLE
[Bug]: GraphRAG function error occurred

### ISSUE THREAD

**Issue by morler** [infiniflow/ragflow#1800]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

dev

### Commit ID

152072f

### Other environment information

```Markdown
ASUS ROG Strix Scar 15 Pro with 13980HX + 4060Ti laptop graphics card

Windows 11 with WSL2
```

### Actual behavior

Failed to parse the Markdown document.
![240804](https://github.com/user-attachments/assets/8c6fa2d7-e01d-4d8f-976f-132bde28f027)

### Steps to reproduce

```Markdown
Establish a knowledge base, import Markdown documents, and begin parsing.
```

### Additional information

2024-08-04 21:41:18 ragflow-server  | Traceback (most recent call last):
2024-08-04 21:41:18 ragflow-server  |   File "/ragflow/rag/svr/task_executor.py", line 148, in build
2024-08-04 21:41:18 ragflow-server  |     cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
2024-08-04 21:41:18 ragflow-server  |   File "/ragflow/rag/app/knowledge_graph.py", line 16, in chunk
2024-08-04 21:41:18 ragflow-server  |     sections = naive.chunk(filename, binary, from_page=from_page, to_page=to_page, section_only=True, parser_config=parser_config)
2024-08-04 21:41:18 ragflow-server  |   File "/ragflow/rag/app/naive.py", line 247, in chunk
2024-08-04 21:41:18 ragflow-server  |     callback(0.1, "Start to parse.")
2024-08-04 21:41:18 ragflow-server  | TypeError: 'NoneType' object is not callable

**Comment by morler** [comment]
The bug has been fixed, thank you very much!
