### ISSUE TITLE
does mysql in docker-compose-base.yaml allow  remote connection as default?

### ISSUE THREAD

**Issue by yangboz** [infiniflow/ragflow#1850]
### Describe your problem

if so , after running docker compose -f docker-compose-base.yaml up -d , try to run ragflow_server.py for local development, then it throws as following:

~~~
Traceback (most recent call last):
  File "/Users/yangboz/git/dangkang/flaskrestx/ragflow_server.py", line 63, in <module>
    init_web_db()
  File "/Users/yangboz/anaconda3/envs/ragflow/lib/python3.11/site-packages/peewee.py", line 3127, in inner

....

peewee.OperationalError: (2003, "Can't connect to MySQL server on 'mysql' ([Errno 8] nodename nor servname provided, or not known)")
~~~

any idea ? thanks.

**Comment by KevinHuSh** [comment]
Check the conf/service_conf.ymal.
Make sure all the hosts there are accessible,
