### ISSUE TITLE
[Question]: Knowledge Graph Has a error when Parsing    [expected string or buffer]

### ISSUE THREAD

**Issue by JaminYan** [infiniflow/ragflow#1859]
### Describe your problem

Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 149, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
  File "/ragflow/rag/app/knowledge_graph.py", line 18, in chunk
    chunks = build_knowlege_graph_chunks(tenant_id, sections, callback,
  File "/ragflow/graphrag/index.py", line 87, in build_knowlege_graph_chunks
    tkn_cnt = num_tokens_from_string(chunks[i])
  File "/ragflow/rag/utils/__init__.py", line 79, in num_tokens_from_string
    num_tokens = len(encoder.encode(string))
  File "/usr/local/lib/python3.10/dist-packages/tiktoken/core.py", line 116, in encode
    if match := _special_token_regex(disallowed_special).search(text):
TypeError: expected string or buffer

![image](https://github.com/user-attachments/assets/f3124f64-96a5-4b93-b49c-b3b169ca729c)

**Comment by cyhasuka** [comment]
Same issue. Occurs when uploading any word documents include pics.
