### ISSUE TITLE
[Question]: How to use python deepdoc/vision/t_ocr.py -h after pip install -r requirement.txt ?

### ISSUE THREAD

**Issue by jojogh** [infiniflow/ragflow#222]
### Describe your problem

After pip install -r requrement.txt, I just use  python deepdoc/vision/t_ocr.py -h, it returned error messages below:
Traceback (most recent call last):
  File "/deepdoc/vision/t_ocr.py", line 14, in <module>
    from deepdoc.vision.seeit import draw_box
ModuleNotFoundError: No module named 'deepdoc'
How i can use the deepdoc by cli?

**Comment by KevinHuSh** [comment]
Thanks for following! 

You need to set environment variable PYTHON PATH=path/to/ragflow

**Comment by jojogh** [comment]
Many thanks!

**Comment by jojogh** [comment]
After I set python env, I use commands cli, the return is below, is that means I need to start some related ES service?
!python /content/ragflow/deepdoc/vision/t_ocr.py --inputs /content/inputs --outputs /content/outputs
Traceback (most recent call last):
  File "/content/ragflow/deepdoc/vision/t_ocr.py", line 14, in <module>
    from deepdoc.vision.seeit import draw_box
  File "/content/ragflow/deepdoc/vision/__init__.py", line 5, in <module>
    from .table_structure_recognizer import TableStructureRecognizer
  File "/content/ragflow/deepdoc/vision/table_structure_recognizer.py", line 22, in <module>
    from rag.nlp import huqie
  File "/content/ragflow/rag/nlp/__init__.py", line 4, in <module>
    from rag.utils import num_tokens_from_string
  File "/content/ragflow/rag/utils/__init__.py", line 19, in <module>
    from .es_conn import ELASTICSEARCH
  File "/content/ragflow/rag/utils/es_conn.py", line 456, in <module>
    ELASTICSEARCH = HuEs()
  File "/content/ragflow/rag/utils/__init__.py", line 12, in _singleton
    instances[key] = cls(*args, **kw)
  File "/content/ragflow/rag/utils/es_conn.py", line 23, in __init__
    raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster

**Comment by jimmylevell** [comment]
Using the following lines within Google Colab I receive the same error as @jojogh 


```
!git clone https://github.com/infiniflow/ragflow.git
%cd ragflow

# Based on: https://github.com/infiniflow/ragflow/issues/220
!sudo -H pip install --ignore-installed -U blinker
%pip install -r requirements.txt

# Based on: https://github.com/infiniflow/ragflow/issues/222
%set_env PYTHONPATH=/content/ragflow

!python deepdoc/vision/t_ocr.py --inputs /content/inputs --outputs /content/outputs
```

Curious to know if deepdoc can be executed independently of ragflow or if it requires a running instance of it.

Thank you in advanced for any further insights.
