### ISSUE TITLE
[Question]: Why do I add rerank and call add_llm?

### ISSUE THREAD

**Issue by zzkzzk1984** [infiniflow/ragflow#2294]
### Describe your problem

add rerank model by Xinference 0.11.1
![image](https://github.com/user-attachments/assets/fc6d2c00-5183-4f8d-8a3a-f279e2086724)

ragflow logs： [INFO] [2024-09-06 16:17:18,658] [_internal._log] [line:96]: 172.22.0.6 - - [06/Sep/2024 16:17:18] "POST /v1/llm/add_llm HTTP/1.1" 200 -

xinference logs：
2024-09-06 16:13:04,682 xinference.api.restful_api 1 ERROR    [address=0.0.0.0:44199, pid=656] rerank hasn't support extra parameter.
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/xinference/api/restful_api.py", line 1036, in rerank
    scores = await model.rerank(
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 227, in send
    return self._process_result_message(result)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/context.py", line 102, in _process_result_message
    raise message.as_instanceof_cause()
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 659, in send
    result = await self._run_coro(message.message_id, coro)
  File "/opt/conda/lib/python3.10/site-packages/xoscar/backends/pool.py", line 370, in _run_coro
    return await coro
  File "/opt/conda/lib/python3.10/site-packages/xoscar/api.py", line 384, in __on_receive__
    return await super().__on_receive__(message)  # type: ignore
  File "xoscar/core.pyx", line 558, in __on_receive__
    raise ex
  File "xoscar/core.pyx", line 520, in xoscar.core._BaseActor.__on_receive__
    async with self._lock:
  File "xoscar/core.pyx", line 521, in xoscar.core._BaseActor.__on_receive__
    with debug_async_timeout('actor_lock_timeout',
  File "xoscar/core.pyx", line 526, in xoscar.core._BaseActor.__on_receive__
    result = await result
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/utils.py", line 45, in wrapped
    ret = await func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 80, in wrapped_func
    ret = await fn(self, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 423, in rerank
    return await self._call_wrapper(
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 104, in _async_wrapper
    return await fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/core/model.py", line 333, in _call_wrapper
    ret = await asyncio.to_thread(fn, *args, **kwargs)
  File "/opt/conda/lib/python3.10/asyncio/threads.py", line 25, in to_thread
    return await loop.run_in_executor(None, func_call)
  File "/opt/conda/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/xinference/model/rerank/core.py", line 175, in rerank
    raise ValueError("rerank hasn't support extra parameter.")
ValueError: [address=0.0.0.0:44199, pid=656] rerank hasn't support extra parameter.

**Comment by hangters** [comment]
hi @zzkzzk1984  I tried adding the Xinference rerank, and it worked successfully. Are you using the latest image? If not, you can try updating to the latest one. Additionally, the IP address you are using seems to be from WSL. You can try using your machine's IP address, which typically starts with 192. like:
<img width="526" alt="image" src="https://github.com/user-attachments/assets/f47145a2-42c3-41de-88be-2204af3120a9">
then
<img width="529" alt="image" src="https://github.com/user-attachments/assets/e6b4ad5f-499b-44fb-ac73-c6333796956e">
Before adding, you can try using the curl command to check if the relevant interface is working. If it still doesn't succeed, feel free to let me know.

**Comment by Halfknow** [comment]
I encounter the same problem with ragflow 10.8 latest dev version and xinference 0.14.3 version.

![image](https://github.com/user-attachments/assets/6051f386-e3e3-4b73-9073-44d20181c1d5)

**Comment by kangkang721** [comment]
请问解决了么？我也遇到了相同的情况

**Comment by ilboud** [comment]
@Halfknow did this PR fix your issue?
