### ISSUE TITLE
[Bug]: GraphRAG doesn't get generated - 400 Please use a valid role: user, model.

### ISSUE THREAD

**Issue by marcfon** [infiniflow/ragflow#2300]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

--

### Other environment information

```Markdown
* dev version

KB settings
* chunk method: knowledge graph
* embedding model: Gemini (tried others as well)
```

### Actual behavior

```[ERROR] [2024-09-07 13:00:05,674] [graph_extractor.__call__] [line:135]: error extracting graph
Traceback (most recent call last):
  File "/ragflow/graphrag/graph_extractor.py", line 128, in __call__
    result, token_count = self._process_document(text, prompt_variables)
  File "/ragflow/graphrag/graph_extractor.py", line 177, in _process_document
    if response.find("**ERROR**") >=0: raise Exception(response)
Exception: **ERROR**: 400 Please use a valid role: user, model.
**ERROR**: contents must not be empty```

### Expected behavior

_No response_

### Steps to reproduce

```Markdown
Add a plain text document to the KB and parse.
```

**Comment by KevinHuSh** [comment]
Pull the dev version of docker. It's fixed.

**Comment by KevinHuSh** [comment]
Could you submit an issue for gemini-1.5-flash-lastest?
