### ISSUE TITLE
[Question]: 输入docker logs -f ragflow-server报错   win10系统

### ISSUE THREAD

**Issue by Suiji12** [infiniflow/ragflow#242]
### Describe your problem

![1712460111500](https://github.com/infiniflow/ragflow/assets/113756481/bfbdcc3d-0247-48fb-a1d2-82086846c7fd)

**Comment by Suiji12** [comment]
File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
    instances[key] = cls(*args, **kw)
                     ^^^^^^^^^^^^^^^^
  File "/ragflow/rag/utils/es_conn.py", line 23, in __init__
    raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster

    ____                 ______ __
   / __ \ ____ _ ____ _ / ____// /____  _      __
  / /_/ // __ `// __ `// /_   / // __ \| | /| / /
 / _, _// /_/ // /_/ // __/  / // /_/ /| |/ |/ /
/_/ |_| \__,_/ \__, //_/    /_/ \____/ |__/|__/
              /____/


Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 50, in <module>
    init_web_data()
  File "/ragflow/api/db/init_data.py", line 301, in init_web_data
    init_superuser()
  File "/ragflow/api/db/init_data.py", line 64, in init_superuser
    TenantLLMService.insert_many(tenant_llm)
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3128, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/ragflow/api/db/services/common_service.py", line 92, in insert_many
    cls.model.insert_many(data_list[i:i + batch_size]).execute()
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 2011, in inner
    return method(self, database, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 2082, in execute
    return self._execute(database)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 2887, in _execute
    return super(Insert, self)._execute(database)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 2600, in _execute
    cursor = database.execute(self)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3298, in execute
    sql, params = ctx.sql(query).query()
                  ^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 660, in sql
    return obj.__sql__(self)
           ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 2872, in __sql__
    self._generate_insert(self._insert, ctx)
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 2748, in _generate_insert
    column = getattr(self.table, column)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'TenantLLM' has no attribute 'base_url'
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 33, in <module>
    from api.db.services.task_service import TaskService
  File "/ragflow/api/db/services/__init__.py", line 18, in <module>
    from .user_service import UserService
  File "/ragflow/api/db/services/user_service.py", line 22, in <module>
    from api.db.db_models import DB, UserTenant
  File "/ragflow/api/db/db_models.py", line 33, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY
  File "/ragflow/api/settings.py", line 16, in <module>
    from rag.utils import ELASTICSEARCH
  File "/ragflow/rag/utils/__init__.py", line 19, in <module>
    from .es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/es_conn.py", line 456, in <module>
    ELASTICSEARCH = HuEs()
                    ^^^^^^
  File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
    instances[key] = cls(*args, **kw)
                     ^^^^^^^^^^^^^^^^
  File "/ragflow/rag/utils/es_conn.py", line 23, in __init__
    raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster
WARNING:root:Realtime synonym is disabled, since no redis connection.
WARNING:root:Realtime synonym is disabled, since no redis connection.
Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 6436.27it/s]
[WARNING] Load term.freq FAIL!
WARNING:root:Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 56850.51it/s]            卡在这里不动了

**Comment by KevinHuSh** [comment]
Thank you for following! We intend to create an international community, so we encourage using English for questions and answers to help others with similar queries. 😊

For your question:

`docker pull swr.cn-north-4.myhuaweicloud.com/infiniflow/ragflow:v1.0`

Please make sure ES is running, otherwise, please refer [this](https://github.com/infiniflow/ragflow/blob/main/docs/max_map_count.md)
