### ISSUE TITLE
[Question]: How to add Volcengine embedding model?

### ISSUE THREAD

**Issue by zsp0901** [infiniflow/ragflow#2483]
### Describe your problem

No matter I used Volcengine or other ways, e.g. OpenAI compatible, OpenRouter, it just got KeyError or other errors.

I tested both "Daobao-embedding" and "ep-xxxx" endpoint ID, it just failed.

base url: https://ark.cn-beijing.volces.com/api/v3

But I can add Volcengine chat model using OpenRouter.

Anyone help? Many thanks!!!

**Comment by Queensbarry** [comment]
I meet the same question. I use `ep-xxx-xxx` to add chat LLM is successful, but failed when adding embedding model.

**Comment by eriklee1895** [comment]
I have the same problem:
when add Volcengine embedding model, pop error: KeyError('VolcEngine')
but the chat model was added successful

**Comment by leoxu2024** [comment]
File "/ragflow/api/apps/llm_app.py", line 209, in add_llm
    mdl = EmbeddingModel[factory](
          ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'VolcEngine'
'VolcEngine'
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/.venv/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/api/utils/api_utils.py", line 175, in decorated_function
    return func(*_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/api/apps/llm_app.py", line 209, in add_llm
    mdl = EmbeddingModel[factory](

添加豆包在线推理模型报错了
![20241105添加豆包在线推理模型报错](https://github.com/user-attachments/assets/9d45c4c1-f31c-422e-b6c7-5e1810dcedd9)

**Comment by which-W** [comment]
@zsp0901 
Thanks so much for the suggestion — and sorry for the delay getting back to you! ⏱️

Good news! We've added support for Volcengine configuration 🎉
You can now complete the setup directly via the LLM configuration page 🛠️

If this resolves your issue, feel free to close the feather when it's convenient. Otherwise, we’ll help clean it up during routine maintenance.

Thanks again for being part of the community and helping improve the project! 🚀
