### ISSUE TITLE
[Bug]: Web code build fails on ARM machines

### ISSUE THREAD

**Issue by cike8899** [infiniflow/ragflow#2554]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

ecf441c830162fd8ca8a7715faf8328d91c53cd7

### Actual behavior

Web code build fails on ARM machines

### Steps to reproduce

```Markdown
84.09 > postinstall
84.09 > umi setup
84.09 
86.93 info  - [你知道吗？] 请求加载态、数据管理、避免竟态问题，用 react-query 帮你全部解决，详见 https://umijs.org/docs/max/react-query
86.94 info  - generate files
88.29 info  - Preparing...
88.93 info  - [icons] generate icons local:google, local:github
91.51 
91.51 > prepare
91.51 > cd .. && husky web/.husky
91.51 
91.66 .git can't be found
91.72 added 2452 packages in 2m
91.72 
91.72 42 packages are looking for funding
91.72   run `npm fund` for details
92.37 
92.37 > build
92.37 > umi build
92.37 
95.11 info  - [你知道吗？] umi g component 可以快速生成组件模板，详见 https://umijs.org/docs/guides/generator#组件生成器
95.11 info  - Umi v4.2.3
96.43 info  - Preparing...
97.06 info  - [icons] generate icons local:google, local:github
99.57 ℹ Compiling Webpack
115.3 [BABEL] Note: The code generator has deoptimised the styling of /ragflow/web/src/assets/svg/login-avatars.svg as it exceeds the max of 500KB.
189.2 ✔ Webpack: Compiled with some errors in 1.49m
189.2 info  - Memory Usage: 1428.69 MB (RSS: 2443.76 MB)
189.2 fatal - Error: ERROR in ./src/pages/file-manager/action-cell/index.tsx 10:0-42
189.2 Module not found: Error: Can't resolve './index.less?modules' in '/ragflow/web/src/pages/file-manager/action-cell'
189.2  @ ./src/pages/file-manager/index.tsx 4:0-39 132:31-41
189.2  @ ./src/.umi-production/core/route.tsx
189.2  @ ./src/.umi-production/umi.ts 10:0-41 27:17-26
189.2 
189.2 webpack compiled with 1 error
189.2     at handler (/ragflow/web/node_modules/@umijs/bundler-webpack/dist/build.js:82:79)
189.2     at finalCallback (/ragflow/web/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62945:32)
189.2     at /ragflow/web/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62962:13
189.2     at Hook.eval [as callAsync] (eval at create (/ragflow/web/node_modules/@umijs/bundler-webpack/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7682), <anonymous>:35:1)
189.2     at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/ragflow/web/node_modules/@umijs/bundler-webpack/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:4851)
189.2     at onCompiled (/ragflow/web/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:62960:21)
189.2     at /ragflow/web/node_modules/@umijs/bundler-webpack/compiled/webpack/index.js:63704:17
189.2     at _next0 (eval at create (/ragflow/web/node_modules/@umijs/bundler-webpack/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7682), <anonymous>:16:1)
189.2     at eval (eval at create (/ragflow/web/node_modules/@umijs/bundler-webpack/node_modules/@umijs/bundler-utils/compiled/tapable/index.js:1:7682), <anonymous>:26:1)
189.2     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
190.1 fatal - A complete log of this run can be found in:
190.1 fatal - /ragflow/web/node_modules/.cache/logger/umi.log
190.1 fatal - Consider reporting a GitHub issue on Issues · umijs/umi
------
```

**Comment by yuzhichang** [comment]
Fixed by PR #2557.
