### ISSUE TITLE
[Bug]: 源码启动ragflow失败

### ISSUE THREAD

**Issue by ly0303521** [infiniflow/ragflow#2656]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

674d342761d7f03df5c58854f9c9309fb5cf40f2

### Other environment information

```Markdown
以前的版本有源码启动的介绍，现在新的版本没有，是因为源码启动本来就有问题吗？？
```

### Actual behavior

以前的版本中有介绍源码启动，我的步骤是按照源码启动的步骤来的，先成功启动了四个基础容器

![Screenshot 2024-09-29 14:58:09](https://github.com/user-attachments/assets/8dfeddbc-7155-4d67-925e-f9aa3516db3c)

根据.env的实际情况设置service_conf.yaml，
我的.env文件：
```bash
# Version of Elastic products
STACK_VERSION=8.11.3


# Port to expose Elasticsearch HTTP API to the host
ES_PORT=1200

# Set the Elasticsearch password
ELASTIC_PASSWORD=infini_rag_flow

# Port to expose Kibana to the host
KIBANA_PORT=6601
KIBANA_USER=rag_flow
KIBANA_PASSWORD=infini_rag_flow

# Increase or decrease based on the available host memory (in bytes)

MEM_LIMIT=8073741824


MYSQL_PASSWORD=infini_rag_flow
MYSQL_PORT=5455

# Port to expose minio to the host
MINIO_CONSOLE_PORT=9001
MINIO_PORT=9000

MINIO_USER=rag_flow
MINIO_PASSWORD=infini_rag_flow

REDIS_PORT=6379
REDIS_PASSWORD=infini_rag_flow

SVR_HTTP_PORT=9380

RAGFLOW_VERSION=v0.11.0

TIMEZONE='Asia/Shanghai'

# Inside GFW, we need the following huggingface.co mirror:
HF_ENDPOINT=https://hf-mirror.com

######## OS setup for ES ###########
# sysctl vm.max_map_count
# sudo sysctl -w vm.max_map_count=262144
# However, this change is not persistent and will be reset after a system reboot.
# To make the change permanent, you need to update the /etc/sysctl.conf file.
# Add or update the following line in the file:
# vm.max_map_count=262144

```
我的service_conf.yaml文件：
```bash
ragflow:
  host: localhost
  http_port: 9380
mysql:
  name: 'rag_flow'
  user: 'root'
  password: 'infini_rag_flow'
  host: 'localhost'
  port: 5455
  max_connections: 100
  stale_timeout: 30
minio:
  user: 'rag_flow'
  password: 'infini_rag_flow'
  host: 'minio:9000'
es:
  hosts: 'http://localhost:1200'
  username: 'elastic'
  password: 'infini_rag_flow'
redis:
  db: 1
  password: 'infini_rag_flow'
  host: 'http://localhost:6379'

# postgres:
#   name: 'rag_flow'
#   user: 'rag_flow'
#   password: 'infini_rag_flow'
#   host: 'postgres'
#   port: 5432
#   max_connections: 100
#   stale_timeout: 30
# s3:
#   endpoint: 'endpoint'
#   access_key: 'access_key'
#   secret_key: 'secret_key'
#   region: 'region'
# azure:
#   auth_type: 'sas'
#   container_url: 'container_url'
#   sas_token: 'sas_token'
# azure:
#   auth_type: 'spn'
#   account_url: 'account_url'
#   client_id: 'client_id'
#   secret: 'secret'
#   tenant_id: 'tenant_id'
#   container_name: 'container_name'
# user_default_llm:
#   factory: 'Tongyi-Qianwen'
#   api_key: 'sk-xxxxxxxxxxxxx'
#   base_url: ''
# oauth:
#   github:
#     client_id: xxxxxxxxxxxxxxxxxxxxxxxxx
#     secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
#     url: https://github.com/login/oauth/access_token
#   feishu:
#     app_id: cli_xxxxxxxxxxxxxxxxxxx
#     app_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
#     app_access_token_url: https://open.feishu.cn/open-apis/auth/v3/app_access_token/internal
#     user_access_token_url: https://open.feishu.cn/open-apis/authen/v1/oidc/access_token
#     grant_type: 'authorization_code'
# authentication:
#   client:
#     switch: false
#     http_app_key:
#     http_secret_key:
#   site:
#     switch: false
# permission:
#   switch: false
#   component: false
#   dataset: false

```

bash ./entrypoint.sh 之后报错如下：

```bash
(ragflow-py3.12) ly@BOE:~/SPACE_SDD/Projects/ragflow$ bash ./entrypoint.sh 
[WARNING] Load term.freq FAIL!
[WARNING] Load term.freq FAIL!
[WARNING] [2024-09-29 14:42:54,675] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-09-29 14:42:54,676] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
[WARNING] Load term.freq FAIL!
[WARNING] [2024-09-29 14:42:54,680] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] [2024-09-29 14:42:54,680] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
/home/ly/SPACE_SDD/miniconda3/envs/ragflow/lib/python3.11/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from this module in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
[WARNING] [2024-09-29 14:42:55,537] [redis_conn.__open__] [line:44]: Redis can't be connected.
/home/ly/SPACE_SDD/miniconda3/envs/ragflow/lib/python3.11/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from this module in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
[WARNING] [2024-09-29 14:42:58,609] [redis_conn.__open__] [line:44]: Redis can't be connected.

    ____                 ______ __               
   / __ \ ____ _ ____ _ / ____// /____  _      __
  / /_/ // __ `// __ `// /_   / // __ \| | /| / /
 / _, _// /_/ // /_/ // __/  / // /_/ /| |/ |/ / 
/_/ |_| \__,_/ \__, //_/    /_/ \____/ |__/|__/  
              /____/                             

    
[WARNING] [2024-09-29 14:43:01,989] [redis_conn.set_obj] [line:80]: [EXCEPTION]set_objTASKEXE||'NoneType' object has no attribute 'set'
[WARNING] [2024-09-29 14:43:01,989] [redis_conn.get_unacked_for] [line:163]: [EXCEPTION]xpending_range: task_consumer_0||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:01,989] [redis_conn.__open__] [line:44]: Redis can't be connected.
[WARNING] [2024-09-29 14:43:01,990] [redis_conn.__open__] [line:44]: Redis can't be connected.
[WARNING] [2024-09-29 14:43:01,990] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:02,991] [redis_conn.get_unacked_for] [line:163]: [EXCEPTION]xpending_range: task_consumer_0||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:02,992] [redis_conn.__open__] [line:44]: Redis can't be connected.
[WARNING] [2024-09-29 14:43:02,992] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:03,993] [redis_conn.get_unacked_for] [line:163]: [EXCEPTION]xpending_range: task_consumer_0||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:03,993] [redis_conn.__open__] [line:44]: Redis can't be connected.
[WARNING] [2024-09-29 14:43:03,993] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:04,994] [redis_conn.get_unacked_for] [line:163]: [EXCEPTION]xpending_range: task_consumer_0||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:04,994] [redis_conn.__open__] [line:44]: Redis can't be connected.
[WARNING] [2024-09-29 14:43:04,994] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:05,995] [redis_conn.get_unacked_for] [line:163]: [EXCEPTION]xpending_range: task_consumer_0||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:05,995] [redis_conn.__open__] [line:44]: Redis can't be connected.
[WARNING] [2024-09-29 14:43:05,995] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:06,996] [redis_conn.get_unacked_for] [line:163]: [EXCEPTION]xpending_range: task_consumer_0||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:06,997] [redis_conn.__open__] [line:44]: Redis can't be connected.
[WARNING] [2024-09-29 14:43:06,997] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:07,998] [redis_conn.get_unacked_for] [line:163]: [EXCEPTION]xpending_range: task_consumer_0||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:07,998] [redis_conn.__open__] [line:44]: Redis can't be connected.
[WARNING] [2024-09-29 14:43:07,998] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:08,999] [redis_conn.get_unacked_for] [line:163]: [EXCEPTION]xpending_range: task_consumer_0||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:08,999] [redis_conn.__open__] [line:44]: Redis can't be connected.
[WARNING] [2024-09-29 14:43:09,000] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:10,000] [redis_conn.get_unacked_for] [line:163]: [EXCEPTION]xpending_range: task_consumer_0||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:10,001] [redis_conn.__open__] [line:44]: Redis can't be connected.
[WARNING] [2024-09-29 14:43:10,001] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:11,001] [redis_conn.get_unacked_for] [line:163]: [EXCEPTION]xpending_range: task_consumer_0||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:11,001] [redis_conn.__open__] [line:44]: Redis can't be connected.
[WARNING] [2024-09-29 14:43:11,001] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:12,002] [redis_conn.get_unacked_for] [line:163]: [EXCEPTION]xpending_range: task_consumer_0||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:12,003] [redis_conn.__open__] [line:44]: Redis can't be connected.
[WARNING] [2024-09-29 14:43:12,003] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:13,004] [redis_conn.get_unacked_for] [line:163]: [EXCEPTION]xpending_range: task_consumer_0||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:13,004] [redis_conn.__open__] [line:44]: Redis can't be connected.
[WARNING] [2024-09-29 14:43:13,004] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||'NoneType' object has no attribute 'xinfo_groups'
Start to insert 2 OpenAI embedding models...
init web data success:11.787681102752686
[INFO] [2024-09-29 14:43:13,719] [_internal._log] [line:97]: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:9380
[INFO] [2024-09-29 14:43:13,720] [_internal._log] [line:97]: Press CTRL+C to quit
[WARNING] [2024-09-29 14:43:14,005] [redis_conn.get_unacked_for] [line:163]: [EXCEPTION]xpending_range: task_consumer_0||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:14,005] [redis_conn.__open__] [line:44]: Redis can't be connected.
[WARNING] [2024-09-29 14:43:14,005] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:15,006] [redis_conn.get_unacked_for] [line:163]: [EXCEPTION]xpending_range: task_consumer_0||'NoneType' object has no attribute 'xinfo_groups'
[WARNING] [2024-09-29 14:43:15,006] [redis_conn.__open__] [line:44]: Redis can't be connected.
[WARNING] [2024-09-29 14:43:15,007] [redis_conn.queue_consumer] [line:146]: [EXCEPTION]consumer: rag_flow_svr_queue||'NoneType' object has no attribute 'xinfo_groups'
^CTraceback (most recent call last):
  File "/home/ly/SPACE_SDD/Projects/ragflow/rag/svr/task_executor.py", line 420, in <module>
    main()
  File "/home/ly/SPACE_SDD/Projects/ragflow/rag/svr/task_executor.py", line 320, in main
    rows = collect()
           ^^^^^^^^^
  File "/home/ly/SPACE_SDD/Projects/ragflow/rag/svr/task_executor.py", line 116, in collect
    time.sleep(1)
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/home/ly/SPACE_SDD/miniconda3/envs/ragflow/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/home/ly/SPACE_SDD/miniconda3/envs/ragflow/lib/python3.11/threading.py", line 1553, in _shutdown
Exception ignored in: <module 'threading' from '/home/ly/SPACE_SDD/miniconda3/envs/ragflow/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/home/ly/SPACE_SDD/miniconda3/envs/ragflow/lib/python3.11/threading.py", line 1553, in _shutdown
    atexit_call()
  File "/home/ly/SPACE_SDD/miniconda3/envs/ragflow/lib/python3.11/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/home/ly/SPACE_SDD/miniconda3/envs/ragflow/lib/python3.11/threading.py", line 1112, in join
    atexit_call()
  File "/home/ly/SPACE_SDD/miniconda3/envs/ragflow/lib/python3.11/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
    self._wait_for_tstate_lock()
  File "/home/ly/SPACE_SDD/miniconda3/envs/ragflow/lib/python3.11/threading.py", line 1112, in join
  File "/home/ly/SPACE_SDD/miniconda3/envs/ragflow/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt: 
    self._wait_for_tstate_lock()
  File "/home/ly/SPACE_SDD/miniconda3/envs/ragflow/lib/python3.11/threading.py", line 1132, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt: 
[WARNING] Load term.freq FAIL!
[WARNING] [2024-09-29 14:43:18,272] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
[WARNING] [2024-09-29 14:43:18,277] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
/home/ly/SPACE_SDD/miniconda3/envs/ragflow/lib/python3.11/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from this module in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
[WARNING] [2024-09-29 14:43:22,064] [redis_conn.__open__] [line:44]: Redis can't be connected.

    ____                 ______ __               
   / __ \ ____ _ ____ _ / ____// /____  _      __
  / /_/ // __ `// __ `// /_   / // __ \| | /| / /
 / _, _// /_/ // /_/ // __/  / // /_/ /| |/ |/ / 
/_/ |_| \__,_/ \__, //_/    /_/ \____/ |__/|__/  
              /____/                             

    
Start to insert 2 OpenAI embedding models...
init web data success:11.938937902450562
[INFO] [2024-09-29 14:43:36,955] [_internal._log] [line:97]: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:9380
[INFO] [2024-09-29 14:43:36,956] [_internal._log] [line:97]: Press CTRL+C to quit

```

### Steps to reproduce

```Markdown
1、cp docker/entrypoint.sh ./
2. 添加如下两行
PY=/home/ly/SPACE_SDD/miniconda3/envs/ragflow/bin/python
export PYTHONPATH=/home/ly/SPACE_SDD/Projects/ragflow
3. docker compose -f docker-compose-base.yml up -d
4. cd .. && chmod +x entrypoint.sh
5. bash ./entrypoint.sh
```

**Comment by ly0303521** [comment]
刚找到了开发者的文档，在“docs/guides/develop/launch_ragflow_from_source.md”，按照新的文档启动ragflow
```bash
bash docker/entrypoint.sh
```
报如下错误：
```bash
ModuleNotFoundError: No module named 'api'
```

**Comment by ly0303521** [comment]
> 刚找到了开发者的文档，在“docs/guides/develop/launch_ragflow_from_source.md”，按照新的文档启动ragflow
> 
> ```shell
> bash docker/entrypoint.sh
> ```
> 
> 报如下错误：
> 
> ```shell
> ModuleNotFoundError: No module named 'api'
> ```

为了防止上述错误，得按照之前版本的做法，要把entrypoint.sh 放到工程根目录，然后运行。
同样的，修改“service_conf.yaml” 和 .env一致。最后运行bash ./entrypoint.sh ，没有报错，但是网页登录不进去....
终端日志如下：


```bash
(ragflow-py3.12) ly@BOE:~/SPACE_SDD/Projects/ragflow$ bash ./entrypoint.sh 
[WARNING] Load term.freq FAIL!
[WARNING] [2024-09-29 15:53:54,531] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
[WARNING] [2024-09-29 15:53:54,536] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
[WARNING] [2024-09-29 15:53:54,554] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
[WARNING] [2024-09-29 15:53:54,559] [synonym.__init__] [line:40]: Realtime synonym is disabled, since no redis connection.
/home/ly/SPACE_SDD/miniconda3/envs/ragflow/lib/python3.11/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from this module in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4
/home/ly/SPACE_SDD/miniconda3/envs/ragflow/lib/python3.11/site-packages/pypdf/_crypt_providers/_cryptography.py:32: CryptographyDeprecationWarning: ARC4 has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.ARC4 and will be removed from this module in 48.0.0.
  from cryptography.hazmat.primitives.ciphers.algorithms import AES, ARC4

    ____                 ______ __               
   / __ \ ____ _ ____ _ / ____// /____  _      __
  / /_/ // __ `// __ `// /_   / // __ \| | /| / /
 / _, _// /_/ // /_/ // __/  / // /_/ /| |/ |/ / 
/_/ |_| \__,_/ \__, //_/    /_/ \____/ |__/|__/  
              /____/                             

    
Start to insert 2 OpenAI embedding models...
init web data success:44.41947340965271
[INFO] [2024-09-29 15:54:51,229] [_internal._log] [line:97]: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:9380
[INFO] [2024-09-29 15:54:51,230] [_internal._log] [line:97]: Press CTRL+C to quit
```

**Comment by ly0303521** [comment]
最后经过一番摸索，终于成功了，感觉“launch_ragflow_from_source.md”这个文档写的不是很完善，
有几个重要的点没有写，但是以前的版本写了：
- 比如“entrypoint.sh”这个启动文件应该拷贝到项目根目录
- 在“entrypoint.sh”要添加

> PY=/home/ly/SPACE_SDD/miniconda3/envs/ragflow/bin/python
export PYTHONPATH=/home/ly/SPACE_SDD/Projects/ragflow
- service_conf.yaml 和 .env 中的实际环境要对应
- node的版本必须是v18.20.4   #2426

**Comment by jdx2099** [comment]
我启动./entrypoint.sh以后报下下面的错：
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f083f100ed0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Traceback (most recent call last):
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/contrib/socks.py", line 110, in _new_conn
    conn = socks.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/socks.py", line 180, in create_connection
    for r in socket.getaddrinfo(proxy_addr, proxy_port, 0, socket.SOCK_STREAM):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/socket.py", line 974, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/contrib/socks.py", line 150, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7f1e4f94acd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

**Comment by ly0303521** [comment]
@jdx2099 你这个看上去是网络问题，你的电脑能科学上网吗，不行的话尝试一下

**Comment by danny-zhu** [comment]
需要将ragflow源代码的根目录添加到PYTHONPATH，即在ragflow根目录执行 export PYTHONPATH=$(pwd)，然后再执行bash docker/launch_backend_service.sh
