### ISSUE TITLE
[Question]: No module named torch

### ISSUE THREAD

**Issue by Said-Apollo** [infiniflow/ragflow#2729]
### Describe your problem

After installing the new version of ragflow and setting everything up (using azure-open-ai, uploading some example document and setting chunking to knowledge graph), I'm encountering the following error:
![image](https://github.com/user-attachments/assets/3984406f-befb-4bf8-ace1-0540691e1eb3)

I did all steps according to launch from source. Do you know any quick fix for that?

**Comment by Said-Apollo** [comment]
Next up, when trying to run again, but with other files, it gave me this output in the terminal:

`
ERROR] [2024-10-07 12:15:36,506] [http_request._handle_response] [line:172]: Request: https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation failed, status: 401, message: Invalid API-key provided.
[ERROR] [2024-10-07 12:15:37,838] [http_request._handle_response] [line:172]: Request: https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation failed, status: 401, message: Invalid API-key provided.
[ERROR] [2024-10-07 12:15:37,869] [graph_extractor.__call__] [line:135]: error extracting graph
Traceback (most recent call last):
  File "/home/said/ragflow/graphrag/graph_extractor.py", line 128, in __call__
    result, token_count = self._process_document(text, prompt_variables)
  File "/home/said/ragflow/graphrag/graph_extractor.py", line 177, in _process_document
    if response.find("**ERROR**") >=0: raise Exception(response)
Exception: ERROR: Invalid API-key provided.
[ERROR] [2024-10-07 12:15:39,271] [http_request._handle_response] [line:172]: Request: https://dashscope.aliyuncs.com/api/v1/services/aigc/text-generation/generation failed, status: 401, message: Invalid API-key provided.
ERROR: Invalid API-key provided.
 {'root': {}}
{
  "id": "root",
  "children": []
}`

Why is it calling dashscope api? Even though I'm using text-embedding-large 3. Is it some default I have to change?

After running afterwards for another file again, it then gave this output in terminal:
`[INFO] [2024-10-07 12:26:42,731] [_internal._log] [line:97]: 127.0.0.1 - - [07/Oct/2024 12:26:42] "GET /v1/document/list?kb_id=02cf6123849611ef8e80401a58bf4f84&page=1&page_size=10 HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/home/said/ragflow/rag/svr/task_executor.py", line 173, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/said/ragflow/rag/app/knowledge_graph.py", line 18, in chunk
    chunks = build_knowledge_graph_chunks(tenant_id, sections, callback,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/said/ragflow/graphrag/index.py", line 56, in build_knowledge_graph_chunks
    llm_bdl = LLMBundle(tenant_id, LLMType.CHAT, tenant.llm_id)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/said/ragflow/api/db/services/llm_service.py", line 196, in __init__
    self.mdl = TenantLLMService.model_instance(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/said/ragflow/.venv/lib/python3.12/site-packages/peewee.py", line 3128, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/said/ragflow/api/db/services/llm_service.py", line 104, in model_instance
    raise LookupError("Model({}) not authorized".format(mdlnm))
LookupError: Model(qwen-plus) not authorized
`


Would be great if anyone could help, as I want to compare the knowledge graph version with other methods (which do work)

**Comment by KevinHuSh** [comment]
Did you use slim version of docker image?
For slim version, please setup embedding model at first place.
If you switch from previours version to slim and used BAAI embedding model, you need to re-setup embedding model and parse all the files again.

**Comment by Said-Apollo** [comment]
Not sure how to check, I didnt change anything, just ran the steps from Launch from source description

docker compose -f docker/docker-compose-base.yml up -d
