### ISSUE TITLE
[Question]: When i execute the command "docker logs -f ragflow-server", and exception occurred.

### ISSUE THREAD

**Issue by nevesaynever1** [infiniflow/ragflow#273]
### Describe your problem

 When i execute the command "docker logs -f ragflow-server", and exception occurred. The detailed information is as follows.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 42, in <module>
    from rag.app import laws, paper, presentation, manual, qa, table, book, resume, picture, naive, one
  File "/ragflow/rag/app/picture.py", line 19, in <module>
    from api.db.services.llm_service import LLMBundle
  File "/ragflow/api/db/services/llm_service.py", line 18, in <module>
    from rag.llm import EmbeddingModel, CvModel, ChatModel
  File "/ragflow/rag/llm/__init__.py", line 16, in <module>
    from .embedding_model import *
  File "/ragflow/rag/llm/embedding_model.py", line 37, in <module>
    flag_model = FlagModel("BAAI/bge-large-zh-v1.5",
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/FlagEmbedding/flag_models.py", line 20, in __init__
    self.model = AutoModel.from_pretrained(model_name_or_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/transformers/modeling_utils.py", line 3193, in from_pretrained
    resolved_archive_file = cached_file(
                            ^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/transformers/utils/hub.py", line 398, in cached_file
    resolved_file = hf_hub_download(
                    ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1457, in hf_hub_download
    http_get(
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 451, in http_get
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 408, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='cdn-lfs.hf-mirror.com', port=443): Max retries exceeded with url: /repos/4a/88/4a88d6caacd50c
2f1573210b4304f3e335d0cda244a88621347fc76a0a72a629/bf84a56fb045c24e090495195584a3922c3e4204107f0bba8b79c11f67a207f2?response-content-disposition=attachment%3B+filena
me*%3DUTF-8%27%27pytorch_model.bin%3B+filename%3D%22pytorch_model.bin%22%3B&response-content-type=application%2Foctet-stream&Expires=1712880903&Policy=eyJTdGF0ZW1lbn
QiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcxMjg4MDkwM319LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy80YS84OC80YTg4ZDZ
jYWFjZDUwYzJmMTU3MzIxMGI0MzA0ZjNlMzM1ZDBjZGEyNDRhODg2MjEzNDdmYzc2YTBhNzJhNjI5L2JmODRhNTZmYjA0NWMyNGUwOTA0OTUxOTU1ODRhMzkyMmMzZTQyMDQxMDdmMGJiYThiNzljMTFmNjdhMjA3ZjI~
cmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qJnJlc3BvbnNlLWNvbnRlbnQtdHlwZT0qIn1dfQ__&Signature=qo34XzeZgpXW2BQA2-7I7~ygHc6HFPK8WNpxgksoIDrdr9kqEx1ZM5vmgZuqjC6D7uxCWB9~R8
8b~58dm28xjR1uIgydyoFmjol7Fd-l-fQPUOcc145Ec0dW0LirEzigZ9x9CRfGHrD6WEl8mWU6Gd1E8Zpwjh~Wb3FfiTLrX-QqClVzQXHQKDCNOWaXHfS~BiXGWCQmMxi1vy5KAkGMnCeSylFfiOlEa6uXaXUpwkALa55
lrlnpVg23ZuqpcrkSeEsF21-WmujqJrdSs14o25y4smGKNHXxPDZzswrj8MLsWIqVGyKHds3YeMMgb0~iV7Q4tVuI7gO8xWn9r9E5VQ__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:992)')))"), '(Request ID: 831ae6ea-6404-4fef-b6ce-2df9437da06e)')
WARNING:root:Realtime synonym is disabled, since no redis connection.
WARNING:root:Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
pytorch_model.bin: 100%|██████████| 1.30G/1.30G [09:37<00:00, 2.26MB/s]
[WARNING] Load term.freq FAIL!
ocr.res: 26.2kB [00:00, 214kB/s] | 1/9 [00:00<00:03,  2.27it/s]
tsr.onnx: 100%|██████████| 12.2M/12.2M [00:08<00:00, 1.46MB/s]]
layout.onnx: 100%|██████████| 12.2M/12.2M [00:09<00:00, 1.31MB/s]
layout.paper.onnx: 100%|██████████| 12.2M/12.2M [00:07<00:00, 1.55MB/s]
layout.manual.onnx: 100%|██████████| 12.2M/12.2M [00:08<00:00, 1.50MB/s]
Fetching 9 files: 100%|██████████| 9/9 [00:28<00:00,  3.18s/it]1.46MB/s]
Fetching 9 files: 100%|██████████| 9/9 [00:28<00:00,  3.16s/it]

**Comment by KevinHuSh** [comment]
It seems internet connection fail. Please make sure internet is accessable and try it agian.
