### ISSUE TITLE
[Question]: Trying to run a local reranker using xinference

### ISSUE THREAD

**Issue by ilboud** [infiniflow/ragflow#2792]
### Describe your problem

When trying to configure a local rerank model via Xinference, I get the following error 

<img width="978" alt="Screenshot 2024-10-10 at 7 15 13 PM" src="https://github.com/user-attachments/assets/11cad4cb-7e14-4fcf-b4ed-390a255566b0">

Testing the connectivity and response from the model via curl from inside the ragflow-server container is working with the same config: 

```
# curl -X POST http://host.docker.internal:9997/v1/rerank \
     -H "Content-Type: application/json" \
     -d '{
           "model": "minicpm-reranker",  # or replace with actual model_uid
           "query": "A man is eating pasta.",
           "documents": [
             "A man is eating food.",
             "A man is eating a piece of bread.",
             "The girl is carrying a baby.",
             "A woman is playing violin."
           ]
         }'
{"id":"2b0ee576-871a-11ef-82ed-66ecc185683a","results":[{"index":3,"relevance_score":1.0,"document":null},{"index":0,"relevance_score":1.0,"document":null},{"index":2,"relevance_score":0.9999998807907104,"document":null},{"index":1,"relevance_score":0.03186270222067833,"document":null}],"meta":{"api_version":null,"billed_units":null,"tokens":null,"warnings":null}}#

How could I configure the local rerank model via xinference? What are the correct parameters?

**Comment by KevinHuSh** [comment]
What about this: http://127.17.0.1:9997/v1/rerank

**Comment by ilboud** [comment]
Is 127.17.0.1 the local nginx? 

I get connection error with that setting


Can be verified from within the ragflow server container with curl: 

```
----> with host.docker.internal:9997 ----> OK

 curl -X POST http://host.docker.internal:9997/v1/rerank -H "Content-Type: application/json" -d '{"model": "bge-reranker-base", "query": "A man is eating pasta.", "documents": ["A man is eating food.","A man is eating a piece of bread.","The girl is carrying a baby.","A woman is playing violin."]}'
{"id":"008c2136-877b-11ef-9bde-66ecc185683a","results":[{"index":0,"relevance_score":0.9999247789382935,"document":null},{"index":1,"relevance_score":0.256493479013443,"document":null},{"index":2,"relevance_score":0.00003742107219295576,"document":null},{"index":3,"relevance_score":0.000037397916457848623,"document":null}],"meta":{"api_version":null,"billed_units":null,"tokens":null,"warnings":null}}#
#

---> with 127.17.0.1:9997 ----> Couldn't connect to server

# curl -X POST http://127.17.0.1:9997/v1/rerank -H "Content-Type: application/json" -d '{"model": "bge-reranker-base", "query": "A man is eating pasta.", "documents": ["A man is eating food.","A man is eating a piece of bread.","The girl is carrying a baby.","A woman is playing violin."]}'
curl: (7) Failed to connect to 127.17.0.1 port 9997 after 5 ms: Couldn't connect to server

**Comment by JobSmithManipulation** [comment]
This issue has been resolved on # 2758 and will be released soon. You can do it through http://IP address:9997/v1/rerank or http://IP address:9997 to use  
If the Rerank Model is deployed on WSL, the IP address of WSL can be obtained through the hostname -I command. If the Rerank Model is deployed on Docker, the IP address of  internal Docker should be used

**Comment by ilboud** [comment]
Thanks for your response... but doesn't work with the IP either, get the same error: 
```
hint : 102
Fail to access model(bge-reranker-base).'results'
```

although trying within the container: 
```
root@843dde0b1a68:/ragflow# curl -X POST http://192.168.65.254:9997/v1/rerank -H "Content-Type: application/json" -d '{"model": "bge-reranker-base", "query": "A man is eating pasta.", "documents": ["A man is eating food.","A man is eating a piece of bread.","The girl is carrying a baby.","A woman is playing violin."]}'

{"id":"b1a8049a-878e-11ef-8832-66ecc185683a","results":[{"index":0,"relevance_score":0.9999247789382935,"document":null},{"index":1,"relevance_score":0.256493479013443,"document":null},{"index":2,"relevance_score":0.00003742107219295576,"document":null},{"index":3,"relevance_score":0.000037397916457848623,"document":null}],"meta":{"api_version":null,"billed_units":null,"tokens":null,"warnings":null}}
root@843dde0b1a68:/ragflow#
```

I am running xinference on the mac host OS and ragflow using docker compose

**Comment by ilboud** [comment]
I don't believe the issue is the IP address, as bot the IP address and host.docker.internal are giving the same error. 

Also it is not a connection error, as if you enter a different random IP address that is not reachable, you get a connection error, not `Fail to access model(bge-reranker-base).'results'`

**Comment by JobSmithManipulation** [comment]
[#2758](https://github.com/infiniflow/ragflow/pull/2758/files)   You can check this PR to see if there have been any updates to the above code file in rag/lm/rank_madel. py

**Comment by JobSmithManipulation** [comment]
[#2758](https://github.com/infiniflow/ragflow/pull/2758/files) You can check this PR to see if there have been updates to the code file： rag/lm/rank_madel. py

**Comment by JobSmithManipulation** [comment]
I got it. I deployed the Ragflow development environment locally and tested the bge-reranker-base model successfully. If you still encounter problems, please feel free to ask at any time.
![1728638290227](https://github.com/user-attachments/assets/1a3f5b53-078b-4f18-b22f-47b272ca2d8c)

**Comment by ilboud** [comment]
Thank you for your effort... 

Same error with the dev docker image... 
```
hint : 102
Fail to access model(bge-reranker-base).'results'
```

**Comment by ilboud** [comment]
Actually I just realised the `rag/lm/rank_model.py` file in the ragflow-server container does not contain the PR changes... I am surprised as I pull the latest dev container. Wasn't it released? How can I make that change on my setup?

**Comment by KevinHuSh** [comment]
What about pulling the images again?

**Comment by ilboud** [comment]
Working now, I didn't realise that the image was not being pulled properly due to a host disk size issue

**Comment by skytodmoon** [comment]
I met the same problem. I use the xinference to deploy bce-rerank-v1 model. And I check the service by  the code is OK`curl -X 'POST' \
  'http://192.168.32.243:9997/v1/rerank' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
    "model": "bce-reranker-base_v1",
    "query": "A man is eating pasta.",
    "documents": [
        "A man is eating food.",
        "A man is eating a piece of bread.",
        "The girl is carrying a baby.",
        "A man is riding a horse.",
        "A woman is playing violin."
    ]
  }'`

**Comment by KevinHuSh** [comment]
What is the response of the `curl`?

**Comment by skytodmoon** [comment]
`{"id":"096a45aa-d18e-11ef-9601-3cecefaed1da","results":[{"index":0,"relevance_score":0.5649465918540955,"document":null},{"index":1,"relevance_score":0.5300139784812927,"document":null},{"index":3,"relevance_score":0.4056761860847473,"document":null},{"index":4,"relevance_score":0.3438847064971924,"document":null},{"index":2,"relevance_score":0.3433420658111572,"document":null}],"meta":{"api_version":null,"billed_units":null,"tokens":null,"warnings":null}}% `

**Comment by KevinHuSh** [comment]
So, there is a key named `results`.
Is this `192.168.32.243` accessible in the ragflow container?

**Comment by skytodmoon** [comment]
> So, there is a key named `results`. Is this `192.168.32.243` accessible in the ragflow container?

Yes, Chat model and embeding model is available

**Comment by skytodmoon** [comment]
mark

**Comment by dj1559499173** [comment]
2025-03-24 23:36:20,436 INFO     611 172.18.0.3 - - [24/Mar/2025 23:36:20] "POST /v1/chunk/retrieval_test HTTP/1.1" 200 -
2025-03-24 23:36:44,092 INFO     611 172.18.0.3 - - [24/Mar/2025 23:36:44] "GET /v1/user/info HTTP/1.1" 200 -
2025-03-24 23:36:44,106 INFO     611 HEAD http://es01:9200/ragflow_e0c4d65000eb11f08b17c2b26be82b31 [status:200 duration:0.003s]
2025-03-24 23:36:44,130 INFO     611 172.18.0.3 - - [24/Mar/2025 23:36:44] "GET /v1/kb/detail?kb_id=5d71421407eb11f083e5c629f44be5f4 HTTP/1.1" 200 -
2025-03-24 23:36:44,177 INFO     611 172.18.0.3 - - [24/Mar/2025 23:36:44] "GET /v1/llm/list HTTP/1.1" 200 -
2025-03-24 23:36:44,193 INFO     611 POST http://es01:9200/ragflow_e0c4d65000eb11f08b17c2b26be82b31/_search [status:200 duration:0.017s]
2025-03-24 23:36:44,196 INFO     611 172.18.0.3 - - [24/Mar/2025 23:36:44] "GET /v1/kb/5d71421407eb11f083e5c629f44be5f4/knowledge_graph HTTP/1.1" 200 -
2025-03-24 23:36:45,426 INFO     611 HTTP Request: POST http://192.168.1.11:11434/api/embeddings "HTTP/1.1 200 OK"
2025-03-24 23:36:45,638 INFO     611 POST http://es01:9200/ragflow_e0c4d65000eb11f08b17c2b26be82b31/_search [status:200 duration:0.038s]
2025-03-24 23:36:46,178 ERROR    611 'results'
Traceback (most recent call last):
  File "/ragflow/api/apps/chunk_app.py", line 308, in retrieval_test
    ranks = settings.retrievaler.retrieval(question, embd_mdl, tenant_ids, kb_ids, page, size,
  File "<@beartype(rag.nlp.search.Dealer.retrieval) at 0x7f89fc33a200>", line 35, in retrieval
  File "/ragflow/rag/nlp/search.py", line 366, in retrieval
    sim, tsim, vsim = self.rerank_by_model(rerank_mdl,
  File "<@beartype(rag.nlp.search.Dealer.rerank_by_model) at 0x7f89fc33a0e0>", line 35, in rerank_by_model
  File "/ragflow/rag/nlp/search.py", line 327, in rerank_by_model
    vtsim, _ = rerank_mdl.similarity(query, [rmSpace(" ".join(tks)) for tks in ins_tw])
  File "<@beartype(api.db.services.llm_service.LLMBundle.similarity) at 0x7f89ece9dfc0>", line 50, in similarity
  File "/ragflow/api/db/services/llm_service.py", line 256, in similarity
    sim, used_tokens = self.mdl.similarity(query, texts)
  File "<@beartype(rag.llm.rerank_model.XInferenceRerank.similarity) at 0x7f89eceb5480>", line 50, in similarity
  File "/ragflow/rag/llm/rerank_model.py", line 237, in similarity
    for d in res["results"]:
KeyError: 'results'
2025-03-24 23:36:46,186 INFO     611 172.18.0.3 - - [24/Mar/2025 23:36:46] "POST /v1/chunk/retrieval_test HTTP/1.1" 200 -


xinference rerank models logs

**Comment by dj1559499173** [comment]
> 2025-03-24 23:36:20,436 INFO     611 172.18.0.3 - - [24/Mar/2025 23:36:20] "POST /v1/chunk/retrieval_test HTTP/1.1" 200 -
> 2025-03-24 23:36:44,092 INFO     611 172.18.0.3 - - [24/Mar/2025 23:36:44] "GET /v1/user/info HTTP/1.1" 200 -
> 2025-03-24 23:36:44,106 INFO     611 HEAD http://es01:9200/ragflow_e0c4d65000eb11f08b17c2b26be82b31 [status:200 duration:0.003s]
> 2025-03-24 23:36:44,130 INFO     611 172.18.0.3 - - [24/Mar/2025 23:36:44] "GET /v1/kb/detail?kb_id=5d71421407eb11f083e5c629f44be5f4 HTTP/1.1" 200 -
> 2025-03-24 23:36:44,177 INFO     611 172.18.0.3 - - [24/Mar/2025 23:36:44] "GET /v1/llm/list HTTP/1.1" 200 -
> 2025-03-24 23:36:44,193 INFO     611 POST http://es01:9200/ragflow_e0c4d65000eb11f08b17c2b26be82b31/_search [status:200 duration:0.017s]
> 2025-03-24 23:36:44,196 INFO     611 172.18.0.3 - - [24/Mar/2025 23:36:44] "GET /v1/kb/5d71421407eb11f083e5c629f44be5f4/knowledge_graph HTTP/1.1" 200 -
> 2025-03-24 23:36:45,426 INFO     611 HTTP Request: POST http://192.168.1.11:11434/api/embeddings "HTTP/1.1 200 OK"
> 2025-03-24 23:36:45,638 INFO     611 POST http://es01:9200/ragflow_e0c4d65000eb11f08b17c2b26be82b31/_search [status:200 duration:0.038s]
> 2025-03-24 23:36:46,178 ERROR    611 'results'
> Traceback (most recent call last):
>   File "/ragflow/api/apps/chunk_app.py", line 308, in retrieval_test
>     ranks = settings.retrievaler.retrieval(question, embd_mdl, tenant_ids, kb_ids, page, size,
>   File "<@beartype(rag.nlp.search.Dealer.retrieval) at 0x7f89fc33a200>", line 35, in retrieval
>   File "/ragflow/rag/nlp/search.py", line 366, in retrieval
>     sim, tsim, vsim = self.rerank_by_model(rerank_mdl,
>   File "<@beartype(rag.nlp.search.Dealer.rerank_by_model) at 0x7f89fc33a0e0>", line 35, in rerank_by_model
>   File "/ragflow/rag/nlp/search.py", line 327, in rerank_by_model
>     vtsim, _ = rerank_mdl.similarity(query, [rmSpace(" ".join(tks)) for tks in ins_tw])
>   File "<@beartype(api.db.services.llm_service.LLMBundle.similarity) at 0x7f89ece9dfc0>", line 50, in similarity
>   File "/ragflow/api/db/services/llm_service.py", line 256, in similarity
>     sim, used_tokens = self.mdl.similarity(query, texts)
>   File "<@beartype(rag.llm.rerank_model.XInferenceRerank.similarity) at 0x7f89eceb5480>", line 50, in similarity
>   File "/ragflow/rag/llm/rerank_model.py", line 237, in similarity
>     for d in res["results"]:
> KeyError: 'results'
> 2025-03-24 23:36:46,186 INFO     611 172.18.0.3 - - [24/Mar/2025 23:36:46] "POST /v1/chunk/retrieval_test HTTP/1.1" 200 -
> 
> 
> xinference rerank models logs

Conclusion

The Ragflow run log shows that at 23:36:46 on March 24, 2025, the system encountered an error when performing the retrieval test (/v1/chunk/retrieval_test). The error stems from the similarity method of the XInferenceRerank trying to access the "results" key in the response, but the key does not exist, resulting in KeyError. Nevertheless, the request finally returned 200, indicating that the system may have caught the exception and continued to execute.

The root cause of the problem

The main reason for the error is that the response returned by the reordering service lacks the "results" key. Possible specific reasons include:

•	 Reorder service internal errors or configuration problems.

•	 The input data (query or retrieval results) is invalid, causing the service to fail to generate the expected output.

Propose

•	 Check the response content: Add a log before line 237 of rerank_model.py and output the value of res to confirm the specific content returned by the service.

•	 Verification input: Check the queries and texts of the incoming similarity method to ensure that they are valid.

•	 Review the configuration: Confirm whether the settings of the rerank model (rerank_mdl) are correct, including API endpoints and model availability.

•	 View the service log: If the reorder is performed through an external service (such as 192.168.1.11:11434), check the log of the service to know the details of its response.

Through the above steps, you can further locate the problem and repair the system.
