### ISSUE TITLE
[Question]: 解析文件报错？

### ISSUE THREAD

**Issue by hbsjmsjwj** [infiniflow/ragflow#2807]
### Describe your problem

Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 177, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
  File "/ragflow/rag/app/book.py", line 75, in chunk
    sections, tbls = doc_parser(
  File "/ragflow/deepdoc/parser/docx_parser.py", line 114, in __call__
    self.doc = Document(fnm) if isinstance(
  File "/usr/local/lib/python3.10/dist-packages/docx/api.py", line 23, in Document
    document_part = Package.open(docx).main_document_part
  File "/usr/local/lib/python3.10/dist-packages/docx/opc/package.py", line 116, in open
    pkg_reader = PackageReader.from_file(pkg_file)
  File "/usr/local/lib/python3.10/dist-packages/docx/opc/pkgreader.py", line 22, in from_file
    phys_reader = PhysPkgReader(pkg_file)
  File "/usr/local/lib/python3.10/dist-packages/docx/opc/phys_pkg.py", line 21, in __new__
    raise PackageNotFoundError("Package not found at '%s'" % pkg_file)
docx.opc.exceptions.PackageNotFoundError: Package not found at

**Comment by JinHai-CN** [comment]
How do you install RAGFlow? From the error message: 'docx.opc.exceptions.PackageNotFoundError: Package not found at' It seems some Python packages are missing.

**Comment by JinHai-CN** [comment]
By the way, we intend to create an international community, so we encourage using English for communication.

**Comment by hjkl950217** [comment]
I also encountered this problem。
I deployed it using docker, but I mapped the web directory and encountered this problem

**Comment by hjkl950217** [comment]
Well, my problem is solved. . I just found a "system" under personal information, which can check the status of file engine and object storage.
My object storage was reporting an error, and after I adjusted the deployment, the problem was solved

> I also encountered this problem。 I deployed it using docker, but I mapped the web directory and encountered this problem

**Comment by softprog** [comment]
is the issue already solved?
