### ISSUE TITLE
[Bug]: ES Cluster connection

### ISSUE THREAD

**Issue by DuckY-Y** [infiniflow/ragflow#281]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

654c759

### Other environment information

```Markdown
ubuntu 2204 lts
latest versions
```

### Actual behavior

```
docker logs ragflow-server
[HUQIE]:Build default trie
[HUQIE]:Build trie /ragflow/rag/res/huqie.txt
[HUQIE]:Build default trie
[HUQIE]:Build trie /ragflow/rag/res/huqie.txt
[HUQIE]:Build default trie
[HUQIE]:Build trie /ragflow/rag/res/huqie.txt
WARNING:root:Realtime synonym is disabled, since no redis connection.
WARNING:root:Realtime synonym is disabled, since no redis connection.
WARNING:root:Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
pytorch_model.bin: 100%|██████████| 1.30G/1.30G [00:42<00:00, 30.3MB/s]
[WARNING] Load term.freq FAIL!
[WARNING] Load term.freq FAIL!
layout.paper.onnx: 100%|██████████| 12.2M/12.2M [00:00<00:00, 26.9MB/s]
ocr.res: 26.2kB [00:00, 96.9kB/s] | 10.5M/12.2M [00:00<00:00, 25.0MB/s]
tsr.onnx: 100%|██████████| 12.2M/12.2M [00:00<00:00, 15.4MB/s]
layout.manual.onnx: 100%|██████████| 12.2M/12.2M [00:00<00:00, 15.7MB/s]
Fetching 9 files:  44%|████▍     | 4/9 [00:02<00:03,  1.59it/s]14.3MB/s]

    ____                 ______ __
   / __ \ ____ _ ____ _ / ____// /____  _      __
  / /_/ // __ `// __ `// /_   / // __ \| | /| / /
 / _, _// /_/ // /_/ // __/  / // /_/ /| |/ |/ /
/_/ |_| \__,_/ \__, //_/    /_/ \____/ |__/|__/
              /____/

layout.onnx: 100%|██████████| 12.2M/12.2M [00:05<00:00, 2.16MB/s]
Fetching 9 files: 100%|██████████| 9/9 [00:08<00:00,  1.05it/s]s]
Fetching 9 files: 100%|██████████| 9/9 [00:08<00:00,  1.05it/s]
WARNING:root:Realtime synonym is disabled, since no redis connection.
【INFO】Super user initialized. email: admin@ragflow.io, password: admin. Changing the password after logining is strongly recomanded.
ERROR:dashscope:HTTPSConnectionPool(host='dashscope.aliyuncs.com', port=443): Max retries exceeded with url: /api/v1/services/aigc/text-generation/generation (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4c6aeb3a90>, 'Connection to dashscope.aliyuncs.com timed out. (connect timeout=300)'))
Traceback (most recent call last):
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/urllib3/connection.py", line 198, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 793, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 491, in _make_request
    raise new_e
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/urllib3/connection.py", line 616, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/urllib3/connection.py", line 207, in _new_conn
    raise ConnectTimeoutError(
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f4c6aeb3a90>, 'Connection to dashscope.aliyuncs.com timed out. (connect timeout=300)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/urllib3/connectionpool.py", line 847, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='dashscope.aliyuncs.com', port=443): Max retries exceeded with url: /api/v1/services/aigc/text-generation/generation (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4c6aeb3a90>, 'Connection to dashscope.aliyuncs.com timed out. (connect timeout=300)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 50, in <module>
    init_web_data()
  File "/ragflow/api/db/init_data.py", line 289, in init_web_data
    init_superuser()
  File "/ragflow/api/db/init_data.py", line 69, in init_superuser
    msg = chat_mdl.chat(system="", history=[
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/api/db/services/llm_service.py", line 162, in chat
    txt, used_tokens = self.mdl.chat(system, history, gen_conf)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/llm/chat_model.py", line 91, in chat
    response = Generation.call(
               ^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/dashscope/aigc/generation.py", line 136, in call
    response = super().call(model=model,
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/dashscope/client/base_api.py", line 135, in call
    return request.call()
           ^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/dashscope/api_entities/http_request.py", line 76, in call
    output = next(response)
             ^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/dashscope/api_entities/http_request.py", line 222, in _handle_request
    raise e
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/dashscope/api_entities/http_request.py", line 205, in _handle_request
    response = session.post(url=self.url,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/requests/adapters.py", line 507, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='dashscope.aliyuncs.com', port=443): Max retries exceeded with url: /api/v1/services/aigc/text-generation/generation (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4c6aeb3a90>, 'Connection to dashscope.aliyuncs.com timed out. (connect timeout=300)'))
Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 23, in <module>
    from api.apps import app
  File "/ragflow/api/apps/__init__.py", line 25, in <module>
    from api.db.services import UserService
  File "/ragflow/api/db/services/__init__.py", line 18, in <module>
    from .user_service import UserService
  File "/ragflow/api/db/services/user_service.py", line 22, in <module>
    from api.db.db_models import DB, UserTenant
  File "/ragflow/api/db/db_models.py", line 33, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY
  File "/ragflow/api/settings.py", line 18, in <module>
    from rag.utils import ELASTICSEARCH
  File "/ragflow/rag/utils/__init__.py", line 19, in <module>
    from .es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/es_conn.py", line 456, in <module>
    ELASTICSEARCH = HuEs()
                    ^^^^^^
  File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
    instances[key] = cls(*args, **kw)
                     ^^^^^^^^^^^^^^^^
  File "/ragflow/rag/utils/es_conn.py", line 23, in __init__
    raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 34, in <module>
    from api.db.services.task_service import TaskService
  File "/ragflow/api/db/services/__init__.py", line 18, in <module>
    from .user_service import UserService
  File "/ragflow/api/db/services/user_service.py", line 22, in <module>
    from api.db.db_models import DB, UserTenant
  File "/ragflow/api/db/db_models.py", line 33, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY
  File "/ragflow/api/settings.py", line 18, in <module>
    from rag.utils import ELASTICSEARCH
  File "/ragflow/rag/utils/__init__.py", line 19, in <module>
    from .es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/es_conn.py", line 456, in <module>
    ELASTICSEARCH = HuEs()
                    ^^^^^^
  File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
    instances[key] = cls(*args, **kw)
                     ^^^^^^^^^^^^^^^^
  File "/ragflow/rag/utils/es_conn.py", line 23, in __init__
    raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 34, in <module>
    from api.db.services.task_service import TaskService
  File "/ragflow/api/db/services/__init__.py", line 18, in <module>
    from .user_service import UserService
  File "/ragflow/api/db/services/user_service.py", line 22, in <module>
    from api.db.db_models import DB, UserTenant
  File "/ragflow/api/db/db_models.py", line 33, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY
  File "/ragflow/api/settings.py", line 18, in <module>
    from rag.utils import ELASTICSEARCH
  File "/ragflow/rag/utils/__init__.py", line 19, in <module>
    from .es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/es_conn.py", line 456, in <module>
    ELASTICSEARCH = HuEs()
                    ^^^^^^
  File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
    instances[key] = cls(*args, **kw)
                     ^^^^^^^^^^^^^^^^
  File "/ragflow/rag/utils/es_conn.py", line 23, in __init__
    raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster
WARNING:root:Realtime synonym is disabled, since no redis connection.
WARNING:root:Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 5815.55it/s]
[WARNING] Load term.freq FAIL!
Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 18902.72it/s]
WARNING:root:Realtime synonym is disabled, since no redis connection.
Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 23, in <module>
    from api.apps import app
  File "/ragflow/api/apps/__init__.py", line 25, in <module>
    from api.db.services import UserService
  File "/ragflow/api/db/services/__init__.py", line 18, in <module>
    from .user_service import UserService
  File "/ragflow/api/db/services/user_service.py", line 22, in <module>
    from api.db.db_models import DB, UserTenant
  File "/ragflow/api/db/db_models.py", line 33, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY
  File "/ragflow/api/settings.py", line 18, in <module>
    from rag.utils import ELASTICSEARCH
  File "/ragflow/rag/utils/__init__.py", line 19, in <module>
    from .es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/es_conn.py", line 456, in <module>
    ELASTICSEARCH = HuEs()
                    ^^^^^^
  File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
    instances[key] = cls(*args, **kw)
                     ^^^^^^^^^^^^^^^^
  File "/ragflow/rag/utils/es_conn.py", line 23, in __init__
    raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 34, in <module>
    from api.db.services.task_service import TaskService
  File "/ragflow/api/db/services/__init__.py", line 18, in <module>
    from .user_service import UserService
  File "/ragflow/api/db/services/user_service.py", line 22, in <module>
    from api.db.db_models import DB, UserTenant
  File "/ragflow/api/db/db_models.py", line 33, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY
  File "/ragflow/api/settings.py", line 18, in <module>
    from rag.utils import ELASTICSEARCH
  File "/ragflow/rag/utils/__init__.py", line 19, in <module>
    from .es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/es_conn.py", line 456, in <module>
    ELASTICSEARCH = HuEs()
                    ^^^^^^
  File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
    instances[key] = cls(*args, **kw)
                     ^^^^^^^^^^^^^^^^
  File "/ragflow/rag/utils/es_conn.py", line 23, in __init__
    raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 34, in <module>
    from api.db.services.task_service import TaskService
  File "/ragflow/api/db/services/__init__.py", line 18, in <module>
    from .user_service import UserService
  File "/ragflow/api/db/services/user_service.py", line 22, in <module>
    from api.db.db_models import DB, UserTenant
  File "/ragflow/api/db/db_models.py", line 33, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY
  File "/ragflow/api/settings.py", line 18, in <module>
    from rag.utils import ELASTICSEARCH
  File "/ragflow/rag/utils/__init__.py", line 19, in <module>
    from .es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/es_conn.py", line 456, in <module>
    ELASTICSEARCH = HuEs()
                    ^^^^^^
  File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
    instances[key] = cls(*args, **kw)
                     ^^^^^^^^^^^^^^^^
  File "/ragflow/rag/utils/es_conn.py", line 23, in __init__
    raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster
WARNING:root:Realtime synonym is disabled, since no redis connection.
WARNING:root:Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 9642.08it/s]
[WARNING] Load term.freq FAIL!
Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 41573.50it/s]
WARNING:root:Realtime synonym is disabled, since no redis connection.
Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 23, in <module>
    from api.apps import app
  File "/ragflow/api/apps/__init__.py", line 25, in <module>
    from api.db.services import UserService
  File "/ragflow/api/db/services/__init__.py", line 18, in <module>
    from .user_service import UserService
  File "/ragflow/api/db/services/user_service.py", line 22, in <module>
    from api.db.db_models import DB, UserTenant
  File "/ragflow/api/db/db_models.py", line 33, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY
  File "/ragflow/api/settings.py", line 18, in <module>
    from rag.utils import ELASTICSEARCH
  File "/ragflow/rag/utils/__init__.py", line 19, in <module>
    from .es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/es_conn.py", line 456, in <module>
    ELASTICSEARCH = HuEs()
                    ^^^^^^
  File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
    instances[key] = cls(*args, **kw)
                     ^^^^^^^^^^^^^^^^
  File "/ragflow/rag/utils/es_conn.py", line 23, in __init__
    raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 34, in <module>
    from api.db.services.task_service import TaskService
  File "/ragflow/api/db/services/__init__.py", line 18, in <module>
    from .user_service import UserService
  File "/ragflow/api/db/services/user_service.py", line 22, in <module>
    from api.db.db_models import DB, UserTenant
  File "/ragflow/api/db/db_models.py", line 33, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY
  File "/ragflow/api/settings.py", line 18, in <module>
    from rag.utils import ELASTICSEARCH
  File "/ragflow/rag/utils/__init__.py", line 19, in <module>
    from .es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/es_conn.py", line 456, in <module>
    ELASTICSEARCH = HuEs()
                    ^^^^^^
  File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
    instances[key] = cls(*args, **kw)
                     ^^^^^^^^^^^^^^^^
  File "/ragflow/rag/utils/es_conn.py", line 23, in __init__
    raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 34, in <module>
    from api.db.services.task_service import TaskService
  File "/ragflow/api/db/services/__init__.py", line 18, in <module>
    from .user_service import UserService
  File "/ragflow/api/db/services/user_service.py", line 22, in <module>
    from api.db.db_models import DB, UserTenant
  File "/ragflow/api/db/db_models.py", line 33, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY
  File "/ragflow/api/settings.py", line 18, in <module>
    from rag.utils import ELASTICSEARCH
  File "/ragflow/rag/utils/__init__.py", line 19, in <module>
    from .es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/es_conn.py", line 456, in <module>
    ELASTICSEARCH = HuEs()
                    ^^^^^^
  File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
    instances[key] = cls(*args, **kw)
                     ^^^^^^^^^^^^^^^^
  File "/ragflow/rag/utils/es_conn.py", line 23, in __init__
    raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster
WARNING:root:Realtime synonym is disabled, since no redis connection.
WARNING:root:Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!
Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 36192.46it/s]
[WARNING] Load term.freq FAIL!
Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 43240.25it/s]
WARNING:root:Realtime synonym is disabled, since no redis connection.
WARNING:root:Realtime synonym is disabled, since no redis connection.
WARNING:root:Realtime synonym is disabled, since no redis connection.
WARNING:root:Realtime synonym is disabled, since no redis connection.
[WARNING] Load term.freq FAIL!

    ____                 ______ __
   / __ \ ____ _ ____ _ / ____// /____  _      __
  / /_/ // __ `// __ `// /_   / // __ \| | /| / /
 / _, _// /_/ // /_/ // __/  / // /_/ /| |/ |/ /
/_/ |_| \__,_/ \__, //_/    /_/ \____/ |__/|__/
              /____/


INFO:werkzeug:WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9380
 * Running on http://172.18.0.6:9380
INFO:werkzeug:Press CTRL+C to quit
[WARNING] Load term.freq FAIL!
Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 7212.22it/s]
[WARNING] Load term.freq FAIL!
Fetching 9 files: 100%|██████████| 9/9 [00:00<00:00, 9048.12it/s]
WARNING:root:Realtime synonym is disabled, since no redis connection.
```

### Steps to reproduce

```Markdown
install, using the instructions.
pip install -r requirements.txt
get some errors
comment a dependency out
pip install -r requirements.txt    again
ok works now ish

t_ocr.py gives error:
Traceback (most recent call last):
  File "/home/tesh/ragflow/deepdoc/vision/t_ocr.py", line 14, in <module>
    from deepdoc.vision.seeit import draw_box
  File "/home/tesh/ragflow/deepdoc/vision/__init__.py", line 5, in <module>
    from .table_structure_recognizer import TableStructureRecognizer
  File "/home/tesh/ragflow/deepdoc/vision/table_structure_recognizer.py", line 22, in <module>
    from rag.nlp import huqie
  File "/home/tesh/ragflow/rag/nlp/__init__.py", line 4, in <module>
    from rag.utils import num_tokens_from_string
  File "/home/tesh/ragflow/rag/utils/__init__.py", line 19, in <module>
    from .es_conn import ELASTICSEARCH
  File "/home/tesh/ragflow/rag/utils/es_conn.py", line 456, in <module>
    ELASTICSEARCH = HuEs()
  File "/home/tesh/ragflow/rag/utils/__init__.py", line 12, in _singleton
    instances[key] = cls(*args, **kw)
  File "/home/tesh/ragflow/rag/utils/es_conn.py", line 23, in __init__
    raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster
```

**Comment by KevinHuSh** [comment]
> checking site gives: {"data":null,"retcode":100,"retmsg":"<NotFound '404: Not Found'>"}

Use IP of your machine. By default, no port is needed to specify.

**Comment by Nehcknarf** [comment]
I met same issue.

**Comment by ThanhHung2112** [comment]
I found the reason because I didn't install [Elasticsearch](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-elasticsearch-on-ubuntu-22-04#step-1-installing-and-configuring-elasticsearch). Check out this link then you shoud change the host in [service_conf.yaml](https://github.com/infiniflow/ragflow/blob/main/conf/service_conf.yaml) 
```
es:
    hosts: 'http://localhost:9200' # or whatever you config.
```
 Good luck

**Comment by ShawnHoo7256** [comment]
Same issue, I cannot access 127.0.0.1:9200 in the browser. 

docker show:
`
CONTAINER ID   IMAGE                                                      COMMAND                  CREATED        STATUS                    PORTS                                                                                                                 NAMES
0145428e9127   ollama/ollama                                              "/bin/ollama serve"      14 hours ago   Exited (0) 14 hours ago                                                                                                                         ollama
39f46f9fc5e5   swr.cn-north-4.myhuaweicloud.com/infiniflow/ragflow:v1.0   "./entrypoint.sh"        14 hours ago   Up 14 hours               0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:9380->9380/tcp, :::9380->9380/tcp   ragflow-server
58bdf9274f56   docker.elastic.co/kibana/kibana:8.11.3                     "/bin/tini -- /usr/l…"   14 hours ago   Up 14 hours               0.0.0.0:6601->5601/tcp, :::6601->5601/tcp                                                                             ragflow-kibana
a9f4f4cc9321   quay.io/minio/minio:RELEASE.2023-12-20T01-00-02Z           "/usr/bin/docker-ent…"   14 hours ago   Up 14 hours               0.0.0.0:9000-9001->9000-9001/tcp, :::9000-9001->9000-9001/tcp                                                         ragflow-minio
ba4605ab4a28   mysql:5.7.18                                               "docker-entrypoint.s…"   14 hours ago   Up 14 hours (healthy)     0.0.0.0:5455->3306/tcp, :::5455->3306/tcp                                                                             ragflow-mysql
edd04f11d318   docker.elastic.co/elasticsearch/elasticsearch:8.11.3       "/bin/tini -- /usr/l…"   14 hours ago   Up 14 hours (healthy)     9300/tcp, 0.0.0.0:1200->9200/tcp, :::1200->9200/tcp                                                                   ragflow-es-01
`

**Comment by zhouzj1610** [comment]
use http://127.0.0.1:1200, since they have make port 1200 to 9200 in docker.
