### ISSUE TITLE
[Question]: Error when docker start ragflow-server, Help me, Thanks

### ISSUE THREAD

**Issue by Jonemlmm** [infiniflow/ragflow#2873]
### Describe your problem

During handling of the above exception, another exception occurred:
2024-10-17 09:47:29 
2024-10-17 09:47:29 Traceback (most recent call last):
2024-10-17 09:47:29   File "/ragflow/api/ragflow_server.py", line 26, in <module>
2024-10-17 09:47:29     from api.apps import app
2024-10-17 09:47:29   File "/ragflow/api/apps/__init__.py", line 26, in <module>
2024-10-17 09:47:29     from api.db.db_models import close_connection
2024-10-17 09:47:29   File "/ragflow/api/db/db_models.py", line 33, in <module>
2024-10-17 09:47:29     from api.settings import DATABASE, stat_logger, SECRET_KEY, DATABASE_TYPE
2024-10-17 09:47:29   File "/ragflow/api/settings.py", line 35, in <module>
2024-10-17 09:47:29     from rag.utils.es_conn import ELASTICSEARCH
2024-10-17 09:47:29   File "/ragflow/rag/utils/__init__.py", line 75, in <module>
2024-10-17 09:47:29     encoder = tiktoken.encoding_for_model("gpt-3.5-turbo")
2024-10-17 09:47:29               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-17 09:47:29   File "/ragflow/.venv/lib/python3.12/site-packages/tiktoken/model.py", line 101, in encoding_for_model
2024-10-17 09:47:29     return get_encoding(encoding_name_for_model(model_name))
2024-10-17 09:47:29            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-17 09:47:29   File "/ragflow/.venv/lib/python3.12/site-packages/tiktoken/registry.py", line 73, in get_encoding
2024-10-17 09:47:29     enc = Encoding(**constructor())
2024-10-17 09:47:29                      ^^^^^^^^^^^^^
2024-10-17 09:47:29   File "/ragflow/.venv/lib/python3.12/site-packages/tiktoken_ext/openai_public.py", line 72, in cl100k_base
2024-10-17 09:47:29     mergeable_ranks = load_tiktoken_bpe(
2024-10-17 09:47:29                       ^^^^^^^^^^^^^^^^^^
2024-10-17 09:47:29   File "/ragflow/.venv/lib/python3.12/site-packages/tiktoken/load.py", line 147, in load_tiktoken_bpe
2024-10-17 09:47:29     contents = read_file_cached(tiktoken_bpe_file, expected_hash)
2024-10-17 09:47:29                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-17 09:47:29   File "/ragflow/.venv/lib/python3.12/site-packages/tiktoken/load.py", line 64, in read_file_cached
2024-10-17 09:47:29     contents = read_file(blobpath)
2024-10-17 09:47:29                ^^^^^^^^^^^^^^^^^^^
2024-10-17 09:47:29   File "/ragflow/.venv/lib/python3.12/site-packages/tiktoken/load.py", line 25, in read_file
2024-10-17 09:47:29     resp = requests.get(blobpath)
2024-10-17 09:47:29            ^^^^^^^^^^^^^^^^^^^^^^
2024-10-17 09:47:29   File "/ragflow/.venv/lib/python3.12/site-packages/requests/api.py", line 73, in get
2024-10-17 09:47:29     return request("get", url, params=params, **kwargs)
2024-10-17 09:47:29            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-17 09:47:29   File "/ragflow/.venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
2024-10-17 09:47:29     return session.request(method=method, url=url, **kwargs)
2024-10-17 09:47:29            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-17 09:47:29   File "/ragflow/.venv/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
2024-10-17 09:47:29     resp = self.send(prep, **send_kwargs)
2024-10-17 09:47:29            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-17 09:47:29   File "/ragflow/.venv/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
2024-10-17 09:47:29     r = adapter.send(request, **kwargs)
2024-10-17 09:47:29         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-10-17 09:47:29   File "/ragflow/.venv/lib/python3.12/site-packages/requests/adapters.py", line 620, in send
2024-10-17 09:47:29     raise SSLError(e, request=request)
2024-10-17 09:47:29 requests.exceptions.SSLError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1000)')))

**Comment by KevinHuSh** [comment]
Check out the envirement variable both on the host and the container: http_porxy, https_proxy.

**Comment by Jonemlmm** [comment]
When I modified this code, it worked properly.
![Snipaste_2024-10-18_16-36-29](https://github.com/user-attachments/assets/470f27c6-402e-4c75-9f64-190b4c39bda4)
