### ISSUE TITLE
[Question]: Hanging at parsing files

### ISSUE THREAD

**Issue by duongkstn** [infiniflow/ragflow#3022]
### Describe your problem

I installed locally ragflow but it get stucked at 0.7% or 6.7%
![image](https://github.com/user-attachments/assets/40398b8c-5c15-428d-a3d5-4cd5a3834e78)

I am using:
- `ollama` (`llama3.2` and `nomic-embed-text`).
- `RAGFLOW_IMAGE=infiniflow/ragflow:v0.9.0`
or `dev`
or `dev-slim`
or `latest`

- `MEM_LIMIT`: I let it be 12GB (my computer has 15 GB in total) (in `.env` file)
- `vm.max_map_count=262144`
- default es options or I added - "ES_JAVA_OPTS=-Xms2g -Xmx2g" in docker-compose-base.yml

I also checked that in `htop`, there was running `task_executor.py` processes. 

I do not know why I can not parse file ? I also saw many issues in github and https://ragflow.io/docs/dev/faq#43-why-does-my-document-parsing-stall-at-under-one-percent , but none were successful.  I restarted again and again, uploaded the most simplest .txt file (one line), but it not worked !

Someone please helps me. It took me really long time. :(

**Comment by yuzhichang** [comment]
The ragflow image 0.9.0 is very old. Please try `infiniflow/ragflow:v0.12.0`.
Hovering on the text `Parsing ...%` will show the progress details such as parsing errors.
And check the log files such as `<ragflow_root>/docker/ragflow-logs/api/ERROR.log`.

**Comment by duongkstn** [comment]
Hi @yuzhichang . it is still stucked !
![image](https://github.com/user-attachments/assets/243fecc9-bb0b-4732-af74-f8a652f6abd5)

I pulled v0.12.0 as you said. Here is the `ERROR.log` file:
![image](https://github.com/user-attachments/assets/eba9087f-c1b3-4c09-a430-dbac2e9f92c2)

Please help me ! thanks

**Comment by EzeLLM** [comment]
Same issue here,
```

Process Duration:
59.62 s
Progress Msg:
Task has been received.
Page(1~13): OCR is running...
Page(1~13): OCR finished
Page(1~13): Layout analysis finished.
Page(1~13): Table analysis finished.
Page(1~13): Text merging finished
Page(1~13): Finished slicing files(8). Start to embedding the content.
Page(1~13): Finished embedding(1.13)! Start to build index!
```

**Comment by EzeLLM** [comment]
> Hi @yuzhichang . it is still stucked ! ![image](https://private-user-images.githubusercontent.com/25122601/380569346-243fecc9-bb0b-4732-af74-f8a652f6abd5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDEzOTgsIm5iZiI6MTczMDQ0MTA5OCwicGF0aCI6Ii8yNTEyMjYwMS8zODA1NjkzNDYtMjQzZmVjYzktYmIwYi00NzMyLWFmNzQtZjhhNjUyZjZhYmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA2MDQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZjc1NmRjNjgwODNiNTI2ZWVjODVhNTU1MjgyOTc4ZGQ3MDY0ODNhZjYzMjY2Mjg4YzBmYWM2ZmI5ZDFkNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TmFi01xPtHWXT-8vnME6ceUbwl46ar4EQUkt-ZrnVIU)
> 
> I pulled v0.12.0 as you said. Here is the `ERROR.log` file: ![image](https://private-user-images.githubusercontent.com/25122601/380577136-eba9087f-c1b3-4c09-a430-dbac2e9f92c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA0NDEzOTgsIm5iZiI6MTczMDQ0MTA5OCwicGF0aCI6Ii8yNTEyMjYwMS8zODA1NzcxMzYtZWJhOTA4N2YtYzFiMy00YzA5LWE0MzAtZGJhYzJlOWY5MmMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAxVDA2MDQ1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzMDI2MzU2ZThiNTkwMGJiZDk5MjE0YjA4MDIwZTc0OGM2YzIzNjNmZTVhYmRhNjJiNDVkMjc0OGM0ZWExYzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.4aOsbEBTZEn4juRxJmop_jGR_-gB4TEU4a8T-YVp78k)
> 
> Please help me ! thanks

Appearantly this is a problem happening with elastic search. i couldnt solve this yet but it seems to be realted to elastic search domain resolve or elastic search port. can you share your service_conf and docker ps for the related containers to check ports?

**Comment by yuzhichang** [comment]
Check all log files under `<ragflow_root>/docker/ragflow-logs`.

**Comment by iSams123** [comment]
Hello, I also have the same problem where document parsing stuck at the building index phrase.
![image](https://github.com/user-attachments/assets/227ec126-ef73-4647-96d5-de2f96c09d61)
Also, the docker terminal of ragflow-server keeps showing this message:
![image](https://github.com/user-attachments/assets/b280f337-1d6c-405a-9790-906931c917c0)
Looking forward for a fix

**Comment by Robabrown** [comment]
I'm here with the same issue. Is there any update?

**Comment by Sabk0926** [comment]
Same for me with version 0.17

**Comment by yuzhichang** [comment]
@duongkstn @Sabk0926 @KeepitSimpleAnalytics Please try RAGFlow nightly image.

**Comment by Sabk0926** [comment]
nightly image fails to run using docker desktop, error is 
2025-03-28 11:27:07     raise err from None
2025-03-28 11:27:07 elastic_transport.ConnectionError: Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7f522478bb80>: Failed to resolve 'es01' ([Errno -2] Name or service not known

**Comment by Sabk0926** [comment]
I got it working with non gpu version of the docker image. Is there a way to use GPU properly?

**Comment by Sabk0926** [comment]
Ok I spoke too soon. After parsing few files, it goes stuck again :(. so frustrating

**Comment by yuzhichang** [comment]
@Sabk0926 task_executor report heartbeat every 30 seconds, inside with are: number of done tasks, number of failed tasks, current tasks and etc. Please check the ragflow-server container log to see what happended.

**Comment by Sabk0926** [comment]
I guess the tasks were stuck even after I restarted all containers.  Is
there a way to clean the queue?

**Comment by yuzhichang** [comment]
@Sabk0926 Don't guess. Use a Python debugger, for example [austin](https://github.com/P403n1x87/austin), to check if the task_executor are stuck.

**Comment by Sabk0926** [comment]
I am not sure I understood. I restarted the containers and everything is working now but very slowly.

**Comment by yuzhichang** [comment]
@Sabk0926 Post the full log of ragflow-server container.

**Comment by Sabk0926** [comment]
[ragflow_server.log](https://github.com/user-attachments/files/19535624/ragflow_server.log)

This is complete server log. The RAG is working but it is running on CPU. If I enable GPU, documents wont parse

**Comment by yuzhichang** [comment]
@Sabk0926 I need task_executor_0.log instead of ragflow_server.log.

By the way, following log in your ragflow_server.log is duplicated with #6030 
```
2025-03-31 09:51:32,310 ERROR    15 Object of type coroutine is not JSON serializable
Traceback (most recent call last):
  File "/ragflow/graphrag/search.py", line 158, in retrieval
    ty_kwds, ents = self.query_rewrite(llm, qst, [index_name(tid) for tid in tenant_ids], kb_ids)
  File "/ragflow/graphrag/search.py", line 46, in query_rewrite
    TYPE_POOL=json.dumps(ty2ents, ensure_ascii=False, indent=2))
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 201, in encode
    chunks = list(chunks)
  File "/usr/lib/python3.10/json/encoder.py", line 438, in _iterencode
    o = _default(o)
  File "/ragflow/api/utils/__init__.py", line 148, in default
    return json.JSONEncoder.default(self, obj)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type coroutine is not JSON serializable

```

**Comment by BenYao21** [comment]
same here. I hovered on Parsing Status. And it shows duration 0,  task in queued. From the log, looks like it's still running. But the process is frozen.

**Comment by orcadevelopmenteers** [comment]
i had the same issue, turns out that a simple restart of the ragflow-server container fixed it.

**Comment by barnabas-lorincz-finshape** [comment]
> i had the same issue, turns out that a simple restart of the ragflow-server container fixed it.

I am facing the same issue with HTML parsing and RAPTOR.

The embedding and summaries are done according to the logs, no error messages, everything is stuck below 1% saying "Task is queued..." indefinitiely.

If I restart the docker container, the process magically continues and everything finishes successfully.

**Unfortunately, this is not a solution for continuous document management, and not realistic for a real world scenario.**

**Comment by barnabas-lorincz-finshape** [comment]
With version 18, the issue seems to have been resolved for me.
