### ISSUE TITLE
[Question]: ERROR:   failed to acquire lock update_progress

### ISSUE THREAD

**Issue by SnailKiller** [infiniflow/ragflow#3082]
### Describe your problem

While parsing a simple text document, the process got stuck at 8.41% completion. Upon reviewing the `ERROR.log`, I noticed the following errors:

```
2024-10-29 07:53:25,073 ERROR    (13) set_progress:(e0488adc95ca11efba960242ac1e0006), failed to acquire lock update_progress
2024-10-29 07:53:25,076 ERROR    (13) set_progress:(e0488adc95ca11efba960242ac1e0006), failed to acquire lock update_progress
2024-10-29 07:53:25,079 ERROR    (13) set_progress:(e0488adc95ca11efba960242ac1e0006), failed to acquire lock update_progress
2024-10-29 07:53:25,191 ERROR    (13) Can't update token usage for 4243989094d011ef854a0242ac180006/EMBEDDING
2024-10-29 07:53:25,194 ERROR    (13) set_progress:(e0488adc95ca11efba960242ac1e0006), failed to acquire lock update_progress
2024-10-29 07:53:25,235 ERROR    (13) Can't update token usage for 4243989094d011ef854a0242ac180006/EMBEDDING
2024-10-29 07:53:25,237 ERROR    (13) set_progress:(e0488adc95ca11efba960242ac1e0006), failed to acquire lock update_progress
2024-10-29 07:53:25,240 ERROR    (13) set_progress:(e0488adc95ca11efba960242ac1e0006), failed to acquire lock update_progress
2024-10-29 07:53:25,257 ERROR    (13) set_progress:(e0488adc95ca11efba960242ac1e0006), failed to acquire lock update_progress
2024-10-29 07:53:25,261 ERROR    (13) set_progress:(e0488adc95ca11efba960242ac1e0006), failed to acquire lock update_progress
```

### Questions

1. Why is the process unable to acquire the `update_progress` lock?
2. How can I resolve this issue and allow the progress to continue?

**Comment by KevinHuSh** [comment]
I don't think this is the reason to stuck.
What the status of your machine, like CPU and  RAM usage?
And is there any progress consuming CPU a alot ?
What's the log message when you hover to the process bar?

**Comment by moshilangzi** [comment]
While parsing a simple PDF document，the process got stuck. Upon reviewing the ERROR.log, I noticed the following errors（web anylysis state is failed）:
2024-11-11 19:03:30,675 ERROR    (3359414) set_progress:(87a71deca01c11ef8571189ba584b5f6), failed to acquire lock update_progress
2024-11-11 19:03:30,741 ERROR    (51478) set_progress:(87a71deca01c11ef8571189ba584b5f6), failed to acquire lock update_progress
2024-11-11 19:03:34,152 ERROR    (49784) set_progress:(87a71cc0a01c11ef8571189ba584b5f6), failed to acquire lock update_progress

**Comment by KevinHuSh** [comment]
I don't think this error would cause stucking issue.

**Comment by meltingrock** [comment]
I am getting the same issu:

`2025-10-28 20:13:08,466 ERROR    23 set_progress(00beaf4cb42611f0a81e163cd7da2ee0), progress: 0.3223880597014925, progress_msg: 20:13:05 Page(1~135): Processing..., got exception
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 189, in set_progress
    TaskService.update_progress(task_id, d)
  File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 3128, in inner
    return fn(*args, **kwargs)
  File "/ragflow/api/db/services/task_service.py", line 302, in update_progress
    with DB.lock("update_progress", -1):
  File "/ragflow/api/db/db_models.py", line 529, in __enter__
    self.lock()
  File "/ragflow/api/db/db_models.py", line 443, in wrapper
    raise last_exception
  File "/ragflow/api/db/db_models.py", line 427, in wrapper
    return func(*args, **kwargs)
  File "/ragflow/api/db/db_models.py", line 514, in lock
    raise Exception(f"failed to acquire lock {self.lock_name}")
Exception: failed to acquire lock update_progress`

Running:
RAGFLOW_IMAGE=infiniflow/ragflow:v0.21.1
DOC_ENGINE=infinity

No other errors except above.

**Comment by wadefelix** [comment]
mysql or mariadb?

**Comment by Yannnnnnny** [comment]
Sorry for the very late reply. We’ve released many updates since then, so I wanted to check whether this issue is still happening for you.
If the issue no longer exists, feel free to close this issue. Thanks!
