### ISSUE TITLE
[Question]: urllib connection error

### ISSUE THREAD

**Issue by rudysev** [infiniflow/ragflow#3156]
### Describe your problem

I am trying to build a knowledge base but the parse step is failing. Looking at the docker logs, I see connection errors:

```
[WARNING] Load term.freq FAIL!
[WARNING] Load term.freq FAIL!
Fetching 8 files: 100%|██████████| 8/8 [00:00<00:00, 67923.95it/s]
./entrypoint.sh: line 15:   189 Killed                  $PY rag/svr/task_executor.py $1
[INFO] [2024-11-01 20:48:00,408] [_internal._log] [line:96]: 172.18.0.2 - - [01/Nov/2024 20:48:00] "GET /v1/document/list?kb_id=da1177c8987c11efa2e10242ac120006&page=1&page_size=10 HTTP/1.1" 200 -
[WARNING] [2024-11-01 20:48:00,432] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 1 times in a row, putting on 1 second timeout
[WARNING] [2024-11-01 20:48:00,432] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 0 of 3)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fffcfe847c0>: Failed to establish a new connection: [Errno 111] Connection refused)
[WARNING] [2024-11-01 20:48:00,434] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 2 times in a row, putting on 2 second timeout
[WARNING] [2024-11-01 20:48:00,434] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 1 of 3)
```

I have restarted docker to no avail.

I ran busybox to check my connection with a ping, and noticed no connection issue when doing so:

```
(venv) rudys@mac-studio ~/.../Software/ragflow/docker % docker run --rm busybox ping -c 4 google.co
PING google.co (142.251.214.142): 56 data bytes
64 bytes from 142.251.214.142: seq=0 ttl=63 time=11.698 ms
64 bytes from 142.251.214.142: seq=1 ttl=63 time=17.517 ms
64 bytes from 142.251.214.142: seq=2 ttl=63 time=12.214 ms
64 bytes from 142.251.214.142: seq=3 ttl=63 time=14.169 ms

--- google.co ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 11.698/13.899/17.517 ms
```

I am unsure why I am seeing the connection issue with ragflow.

**Comment by JinHai-CN** [comment]
exit code 137 means that Elasticsearch is taking up too much memory

**Comment by JinHai-CN** [comment]
Please make sure your environment has at least 16 GB memory and run `$ sudo sysctl -w vm.max_map_count=262144 `before start RAGFlow.

**Comment by rudysev** [comment]
> Please make sure your environment has at least 16 GB memory and run `$ sudo sysctl -w vm.max_map_count=262144 `before start RAGFlow.

Thank you, this fixed my issue!

**Comment by pokemonjs** [comment]
> Please make sure your environment has at least 16 GB memory and run `$ sudo sysctl -w vm.max_map_count=262144 `before start RAGFlow.

hello，i use the windows system and my computer has 16 GB RAM，but i still met the problem，and i have no way to run the sysctl command，what should the Windows users do？

**Comment by cylcc06** [comment]
macos: 
sudo sysctl -w vm.max_map_count=262144
Password:
sysctl: unknown oid 'vm.max_map_count'
