### ISSUE TITLE
[Bug]: Error response after move the file to another folder

### ISSUE THREAD

**Issue by mieco** [infiniflow/ragflow#3247]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

latest dev docker image

### Actual behavior

can't embedding document after move the file to another folder.

TypeError("The view function for 'document.get' did not return a valid response. The function either returned None or ended without a return statement.")

![image](https://github.com/user-attachments/assets/be1af341-16fe-4145-b4b6-6ee848c83927)

### Steps to reproduce

```Markdown
1. upload the file to the file management
2. link the file to one knowledge base
3. move the file to another folder in file management
4. got error when trying to parse the document
```

**Comment by yuzhichang** [comment]
I got following error in `ragflow_server.log`:

```
2024-11-21 18:45:45,411 ERROR    1782542 total_page_number
Traceback (most recent call last):
  File "/home/zhichyu/github.com/infiniflow/ragflow/deepdoc/parser/pdf_parser.py", line 935, in total_page_number
    pdf = pdfplumber.open(
  File "/home/zhichyu/github.com/infiniflow/ragflow/.venv/lib/python3.10/site-packages/pdfplumber/pdf.py", line 86, in open
    stream = open(path_or_fp, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'SQL+管理命令手册+0.5.0.pdf'
2024-11-21 18:45:45,413 ERROR    1782542 '<' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "/home/zhichyu/github.com/infiniflow/ragflow/api/apps/document_app.py", line 372, in run
    queue_tasks(doc, bucket, name)
  File "/home/zhichyu/github.com/infiniflow/ragflow/api/db/services/task_service.py", line 157, in queue_tasks
    e = min(e - 1, pages)
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by liulianzhu** [comment]
I got the same bug. How you solved the problem, dude ?

**Comment by liangyuwei** [comment]
I encountered a similar problem with a file named "handbook of XXX.pdf". After I removed all the SPACE in the name, it worked. Maybe try changing your file name from Chinese to English and see if it works.

**Comment by wangq8** [comment]
The bug has been long time, might not be valid in main branch, close it now. If you still met the issue, free free to reopen the bug.
