### ISSUE TITLE
[Question]: I can't Launch backend service(Launch service from source for development)

### ISSUE THREAD

**Issue by jdx2099** [infiniflow/ragflow#3258]
### Describe your problem

I followed the guideline step by step.
![image](https://github.com/user-attachments/assets/fa4b60d5-eb6b-40b0-922f-2503007612c3)
![image](https://github.com/user-attachments/assets/584c29b0-42fd-4ee4-99ce-3fe7a8cdbba8)
In step 5, I was trying to launch the backend service but got some ERROR messgae. The followings are part of the error messages:
====================================================================================
Traceback (most recent call last):
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/connectionpool.py", line 490, in _make_request
    raise new_e
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/connectionpool.py", line 466, in _make_request
    self._validate_conn(conn)
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1095, in _validate_conn
    conn.connect()
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/connection.py", line 693, in connect
    self.sock = sock = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/contrib/socks.py", line 150, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fdab0482910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/requests/adapters.py", line 589, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/util/retry.py", line 519, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: SOCKSHTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fdab0482910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lenovo/RAG/ragflow/rag/svr/task_executor.py", line 37, in <module>
    from api.db.services.dialog_service import keyword_extraction, question_proposal
  File "/home/lenovo/RAG/ragflow/api/db/services/__init__.py", line 18, in <module>
    from .user_service import UserService
  File "/home/lenovo/RAG/ragflow/api/db/services/user_service.py", line 22, in <module>
    from api.db.db_models import DB, UserTenant
  File "/home/lenovo/RAG/ragflow/api/db/db_models.py", line 33, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY, DATABASE_TYPE
  File "/home/lenovo/RAG/ragflow/api/settings.py", line 36, in <module>
    from rag.utils.es_conn import ELASTICSEARCH
  File "/home/lenovo/RAG/ragflow/rag/utils/__init__.py", line 75, in <module>
    encoder = tiktoken.encoding_for_model("gpt-3.5-turbo")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/tiktoken/model.py", line 103, in encoding_for_model
    return get_encoding(encoding_name_for_model(model_name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/tiktoken/registry.py", line 73, in get_encoding
    enc = Encoding(**constructor())
                     ^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/tiktoken_ext/openai_public.py", line 72, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
                      ^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/tiktoken/load.py", line 147, in load_tiktoken_bpe
    contents = read_file_cached(tiktoken_bpe_file, expected_hash)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/tiktoken/load.py", line 64, in read_file_cached
    contents = read_file(blobpath)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/tiktoken/load.py", line 25, in read_file
    resp = requests.get(blobpath)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/requests/adapters.py", line 622, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: SOCKSHTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by NewConnectionError('<urllib3.contrib.socks.SOCKSHTTPSConnection object at 0x7fdab0482910>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Traceback (most recent call last):
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/urllib3/contrib/socks.py", line 110, in _new_conn
    conn = socks.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/site-packages/socks.py", line 180, in create_connection
    for r in socket.getaddrinfo(proxy_addr, proxy_port, 0, socket.SOCK_STREAM):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lenovo/anaconda3/envs/ragflow/lib/python3.11/socket.py", line 974, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:
==================================================================================

**Comment by KevinHuSh** [comment]
`tiktoken` needs to download some model from the internet. It seems the network failure.

**Comment by BrightXiaoHan** [comment]
我是部署在离线的机器上的，机器不能联网，这个有什么办法可以解决吗
I am deployed on an offline machine, which cannot be connected to the internet. Is there any way to solve this problem?

**Comment by mayanchaoDD** [comment]
@BrightXiaoHan 问题解决了吗? 求解

**Comment by Yannnnnnny** [comment]
Thanks for the update.
Just checking in — are you still experiencing this issue on the latest version? If the problem has been resolved, we can go ahead and close this issue. Otherwise, please let us know and we'll continue investigating.
