### ISSUE TITLE
[Bug]: Table 'rag_flow.document' doesn't exist

### ISSUE THREAD

**Issue by libhot** [infiniflow/ragflow#331]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

0e8931b

### Other environment information

```Markdown
Ubuntu22，Docker24,Docker Compose v2.26.1
```

### Actual behavior

按照官方安装流程
docker compose up -d
启动后，报错Table 'rag_flow.document' doesn't exist，查看database是创建了，但table全部没有创建。
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/svr/task_broker.py", line 180, in <module>
    dispatch()
  File "/ragflow/rag/svr/task_broker.py", line 64, in dispatch
    rows = collect(tm)
           ^^^^^^^^^^^
  File "/ragflow/rag/svr/task_broker.py", line 38, in collect
    docs = DocumentService.get_newly_uploaded(tm)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3128, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/ragflow/api/db/services/document_service.py", line 101, in get_newly_uploaded
    return list(docs.dicts())
           ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 7243, in __iter__
    self.execute()
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 2011, in inner
    return method(self, database, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 2082, in execute
    return self._execute(database)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 2255, in _execute
    cursor = database.execute(self)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3299, in execute
    return self.execute_sql(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3289, in execute_sql
    with __exception_wrapper__:
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3059, in __exit__
    reraise(new_type, new_type(exc_value, *exc_args), traceback)
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 192, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/peewee.py", line 3291, in execute_sql
    cursor.execute(sql, params or ())
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 822, in _read_query_result
    result.read()
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
peewee.ProgrammingError: (1146, "Table 'rag_flow.document' doesn't exist")

### Steps to reproduce

```Markdown
docker compose up -d
```

**Comment by libhot** [comment]
解决了
change docker/entrypoint.sh: 26: sleep 60 -> sleep 180
add a line after docker/docker-compose.yml: 109
- ./entrypoint.sh:/ragflow/entrypoint.sh
docker compose down -v
docker compose up

[#3](https://github.com/infiniflow/ragflow/issues/331)

**Comment by libhot** [comment]
虽然已经解决，建议加上手工初始的命令，这样更可控

**Comment by ch0pp3rVirus** [comment]
> 虽然已经解决，建议加上手工初始的命令，这样更可控

请问方便可以贴出修改后的docker-compose.yml吗，我改了之后的docker-compose.yml是这样，但是还是报错

version: '2.2'

include:
  - path: ./docker-compose-base.yml
    env_file: ./.env

services:
  ragflow:
    depends_on:
      mysql:
        condition: service_healthy
      es01:
        condition: service_healthy
    image: infiniflow/ragflow:v1.0
    container_name: ragflow-server
    ports:
      - ${SVR_HTTP_PORT}:9380
      - 4080:80
      - 443:443
    volumes:
      - ./service_conf.yaml:/ragflow/conf/service_conf.yaml
      - ./entrypoint.sh:/ragflow/entrypoint.sh
      - ./ragflow-logs:/ragflow/logs
      - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf
      - ./nginx/proxy.conf:/etc/nginx/proxy.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - TZ=${TIMEZONE}
    networks:
      - ragflow
    restart: always

我的docker image
infiniflow/ragflow                                    v1.0                           8d9f907a3257   17 hours ago   15.7GB

**Comment by ch0pp3rVirus** [comment]
> > 虽然已经解决，建议加上手工初始的命令，这样更可控
> 
> 请问方便可以贴出修改后的docker-compose.yml吗，我改了之后的docker-compose.yml是这样，但是还是报错
> 
> version: '2.2'
> 
> include:
> 
> * path: ./docker-compose-base.yml
>   env_file: ./.env
> 
> services: ragflow: depends_on: mysql: condition: service_healthy es01: condition: service_healthy image: infiniflow/ragflow:v1.0 container_name: ragflow-server ports: - ${SVR_HTTP_PORT}:9380 - 4080:80 - 443:443 volumes: - ./service_conf.yaml:/ragflow/conf/service_conf.yaml - ./entrypoint.sh:/ragflow/entrypoint.sh - ./ragflow-logs:/ragflow/logs - ./nginx/ragflow.conf:/etc/nginx/conf.d/ragflow.conf - ./nginx/proxy.conf:/etc/nginx/proxy.conf - ./nginx/nginx.conf:/etc/nginx/nginx.conf environment: - TZ=${TIMEZONE} networks: - ragflow restart: always
> 
> 我的docker image infiniflow/ragflow v1.0 8d9f907a3257 17 hours ago 15.7GB

没事了，可以跑起来了，就是启动服务要等待够久
