### ISSUE TITLE
[Question]: 1. Why a large number of log messages appear in the system interface? 2. Why does the error "unsupported operand type(s) for +: 'dict' and 'dict' appear in the system interface?

### ISSUE THREAD

**Issue by lss0510** [infiniflow/ragflow#3475]
### Describe your problem

When I finished the deployment, I was able to parse the files normally, but my system interface had the problem stated in the title.
![image](https://github.com/user-attachments/assets/5420db92-abff-43fc-9fa6-2515beb499e4)

**Comment by KevinHuSh** [comment]
Pull the latest dev version of docker image, it's fixed there.

**Comment by lss0510** [comment]
I updated the latest docker image and restarted the server, which solved some of my issues, but left some unresolved.
![image](https://github.com/user-attachments/assets/ba1144cf-8bcf-4a0d-9717-0af7ffe47002)
/ragflow/.venv/lib/python3.12/site-packages/graspologic/match/wrappers.py:74: SyntaxWarning: invalid escape sequence '\s'
  """
/ragflow/.venv/lib/python3.12/site-packages/graspologic/pipeline/embed/adjacency_spectral_embedding.py:37: SyntaxWarning: invalid escape sequence '\S'
  """
/ragflow/.venv/lib/python3.12/site-packages/graspologic/pipeline/embed/laplacian_spectral_embedding.py:38: SyntaxWarning: invalid escape sequence '\S'
  """
/ragflow/graphrag/entity_resolution.py:181: SyntaxWarning: invalid escape sequence '\d'
  pattern_int = f"{re.escape(entity_index_delimiter)}(\d+){re.escape(entity_index_delimiter)}"
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 57, in <module>
    from rag.app import laws, paper, presentation, manual, qa, table, book, resume, picture, naive, one, audio, \
  File "/ragflow/rag/app/knowledge_graph.py", line 3, in <module>
    from graphrag.index import build_knowledge_graph_chunks
  File "/ragflow/graphrag/index.py", line 27, in <module>
    from graphrag.graph_extractor import GraphExtractor, DEFAULT_ENTITY_TYPES
  File "/ragflow/graphrag/graph_extractor.py", line 311, in <module>
    def _unpack_descriptions(data: Mapping) -> list[str]:
                                   ^^^^^^^
NameError: name 'Mapping' is not defined

**Comment by KevinHuSh** [comment]
Sorry, we're fixing these things, please pull it a couple of days later.
