### ISSUE TITLE
[Bug]: front end env install always fail

### ISSUE THREAD

**Issue by zydmtaichi** [infiniflow/ragflow#3547]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

v0.13.0

### Commit ID

1d0a5606b2cb39962ca4ec0e38fcd59faeafee37

### Other environment information

```Markdown
OS: ubuntu 22.04
npm version: 8.5.1
nodejs version: v12.22.9
```

### Actual behavior

err output as below:
```
> postinstall
> umi setup

/mnt/ragflow/web/node_modules/@umijs/utils/compiled/@clack/prompts/index.js:1

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:85:18)
    at Object.<anonymous> (/mnt/ragflow/web/node_modules/@umijs/utils/dist/index.js:76:28)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
npm ERR! code 1
npm ERR! path /mnt/ragflow/web
npm ERR! command failed
npm ERR! command sh -c umi setup

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ld/.npm/_logs/2024-11-21T03_02_13_783Z-debug-0.log
```

### Expected behavior

install the env correctly

### Steps to reproduce

```Markdown
cd ./web
npm install --force
```

**Comment by zydmtaichi** [comment]
add err log as below:
[2024-11-21T03_02_13_783Z-debug-0.log](https://github.com/user-attachments/files/17839399/2024-11-21T03_02_13_783Z-debug-0.log)

**Comment by cike8899** [comment]
Pull the latest code and re-execute 'npm i'

**Comment by zydmtaichi** [comment]
> Pull the latest code and re-execute 'npm i'

okay, I update the node version to 20 lts and it looks fine
