### ISSUE TITLE
[Question]: I set embedding  config get error 

### ISSUE THREAD

**Issue by cp19861214** [infiniflow/ragflow#3553]
### Describe your problem

Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/.venv/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/.venv/lib/python3.12/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/api/utils/api_utils.py", line 171, in decorated_function
    return func(*_args, **_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/api/apps/llm_app.py", line 213, in add_llm
    mdl = EmbeddingModel[factory](
          ~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'VolcEngine'

**Comment by JinHai-CN** [comment]
The embedding model of VolcEngine is missed in code.
