### ISSUE TITLE
[Bug]: run container failed 

### ISSUE THREAD

**Issue by pxr1997** [infiniflow/ragflow#3577]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

691ea28

### RAGFlow image version

v0.13.0~172

### Other environment information

```Markdown
my environment: 
   os:windows
   docker:27.0.3
   docker-compose:2.28.1



containers' state are all healthy or started. the installation seems successful.
```

### Actual behavior

D:\program\py\ragflow\docker>docker logs -f ragflow-server
2024-11-22 10:25:40,891 INFO     19 ragflow_server log path: /ragflow/logs/ragflow_server.log
2024-11-22 10:25:40,923 INFO     21 task_executor_0 log path: /ragflow/logs/task_executor_0.log
2024-11-22 10:25:50,804 INFO     21 init database on cluster mode successfully
2024-11-22 10:25:51,033 INFO     19 init database on cluster mode successfully
2024-11-22 10:26:02,513 WARNING  19 /ragflow/.venv/lib/python3.12/site-packages/scholarly/_scholarly.py:312: SyntaxWarning: invalid escape sequence '\d'
  m = re.search("cites=[\d+,]*", object["citedby_url"])

2024-11-22 10:26:02,840 WARNING  21 /ragflow/.venv/lib/python3.12/site-packages/graspologic/align/seedless_procrustes.py:18: SyntaxWarning: invalid escape sequence '\i'
  """

2024-11-22 10:26:02,913 WARNING  21 /ragflow/.venv/lib/python3.12/site-packages/ot/unbalanced/_lbfgs.py:21: SyntaxWarning: invalid escape sequence '\m'
  """

2024-11-22 10:26:03,815 INFO     19
        ____   ___    ______ ______ __
       / __ \ /   |  / ____// ____// /____  _      __
      / /_/ // /| | / / __ / /_   / // __ \| | /| / /
     / _, _// ___ |/ /_/ // __/  / // /_/ /| |/ |/ /
    /_/ |_|/_/  |_|\____//_/    /_/ \____/ |__/|__/

2024-11-22 10:26:03,815 INFO     19 RAGFlow version: 85dd9fde(v0.13.0~172)
2024-11-22 10:26:03,816 INFO     19 project base: /ragflow
2024-11-22 10:26:03,817 INFO     19 Current configs, from /ragflow/conf/service_conf.yaml:
2024-11-22 10:26:03,817 INFO     19 ragflow: {'host': '0.0.0.0', 'http_port': 9380}
2024-11-22 10:26:03,818 INFO     19 mysql: {'name': 'rag_flow', 'user': 'root', 'password': 'infini_rag_flow', 'host': 'mysql', 'port': 3306, 'max_connections': 100, 'stale_timeout': 30}
2024-11-22 10:26:03,818 INFO     19 minio: {'user': 'rag_flow', 'password': 'infini_rag_flow', 'host': 'minio:9000'}
2024-11-22 10:26:03,819 INFO     19 es: {'hosts': 'http://es01:9200', 'username': 'elastic', 'password': 'infini_rag_flow'}
2024-11-22 10:26:03,819 INFO     19 redis: {'db': 1, 'password': 'infini_rag_flow', 'host': 'redis:6379'}
2024-11-22 10:26:03,820 INFO     19 Use Elasticsearch http://es01:9200 as the doc engine.
2024-11-22 10:26:03,905 INFO     19 GET http://es01:9200/ [status:200 duration:0.084s]
2024-11-22 10:26:03,911 INFO     19 HEAD http://es01:9200/ [status:200 duration:0.004s]
2024-11-22 10:26:03,912 INFO     19 Elasticsearch http://es01:9200 is healthy.
2024-11-22 10:26:03,916 WARNING  19 Load term.freq FAIL!
2024-11-22 10:26:03,921 WARNING  19 Realtime synonym is disabled, since no redis connection.
2024-11-22 10:26:03,926 WARNING  19 Load term.freq FAIL!
2024-11-22 10:26:03,930 WARNING  19 Realtime synonym is disabled, since no redis connection.
2024-11-22 10:26:04,541 WARNING  21 /ragflow/.venv/lib/python3.12/site-packages/hyppo/kgof/kernel.py:93: SyntaxWarning: invalid escape sequence '\s'
  """

2024-11-22 10:26:04,542 WARNING  21 /ragflow/.venv/lib/python3.12/site-packages/hyppo/kgof/kernel.py:132: SyntaxWarning: invalid escape sequence '\s'
  """

2024-11-22 10:26:04,543 WARNING  21 /ragflow/.venv/lib/python3.12/site-packages/hyppo/kgof/kernel.py:234: SyntaxWarning: invalid escape sequence '\s'
  """

2024-11-22 10:26:05,026 INFO     21 generated new fontManager
2024-11-22 10:26:07,441 INFO     19 init web data success:3.0836682319641113
2024-11-22 10:26:07,442 INFO     19 RAGFlow HTTP server start...
2024-11-22 10:26:07,444 INFO     19 WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9380
 * Running on http://172.20.0.6:9380
2024-11-22 10:26:07,444 INFO     19 Press CTRL+C to quit
2024-11-22 10:26:17,887 WARNING  21 /ragflow/.venv/lib/python3.12/site-packages/graspologic/match/wrappers.py:74: SyntaxWarning: invalid escape sequence '\s'
  """

2024-11-22 10:26:17,903 WARNING  21 /ragflow/.venv/lib/python3.12/site-packages/graspologic/pipeline/embed/adjacency_spectral_embedding.py:37: SyntaxWarning: invalid escape sequence '\S'
  """

2024-11-22 10:26:17,910 WARNING  21 /ragflow/.venv/lib/python3.12/site-packages/graspologic/pipeline/embed/laplacian_spectral_embedding.py:38: SyntaxWarning: invalid escape sequence '\S'
  """

2024-11-22 10:26:18,112 WARNING  21 /ragflow/graphrag/entity_resolution.py:181: SyntaxWarning: invalid escape sequence '\d'
  pattern_int = f"{re.escape(entity_index_delimiter)}(\d+){re.escape(entity_index_delimiter)}"

2024-11-22 10:26:18,120 INFO     21 Use Elasticsearch http://es01:9200 as the doc engine.
2024-11-22 10:26:18,132 INFO     21 GET http://es01:9200/ [status:200 duration:0.009s]
2024-11-22 10:26:18,138 INFO     21 HEAD http://es01:9200/ [status:200 duration:0.005s]
2024-11-22 10:26:18,139 INFO     21 Elasticsearch http://es01:9200 is healthy.
2024-11-22 10:26:18,143 WARNING  21 Load term.freq FAIL!
2024-11-22 10:26:18,145 WARNING  21 Realtime synonym is disabled, since no redis connection.
2024-11-22 10:26:18,150 WARNING  21 Load term.freq FAIL!
2024-11-22 10:26:18,154 WARNING  21 Realtime synonym is disabled, since no redis connection.
2024-11-22 10:26:18,157 WARNING  21 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2024-11-22 10:26:18,158 INFO     21 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2024-11-22T10:26:18.157491", "boot_at": "2024-11-22T10:26:18.120527", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2024-11-22 10:26:30,801 ERROR    19 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/.venv/lib/python3.12/site-packages/flask/app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "/ragflow/.venv/lib/python3.12/site-packages/flask/app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/.venv/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/.venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None

### Expected behavior

I can't browse the main page. either localhost:9380 or localhost:1200,could you help me?
it returns {"code":100,"data":null,"message":"<NotFound '404: Not Found'>"}

{
  "name" : "es01",
  "cluster_name" : "docker-cluster",
  "cluster_uuid" : "We075DUZSyyd78MsKYl2qQ",
  "version" : {
    "number" : "8.11.3",
    "build_flavor" : "default",
    "build_type" : "docker",
    "build_hash" : "64cf052f3b56b1fd4449f5454cb88aca7e739d9a",
    "build_date" : "2023-12-08T11:33:53.634979452Z",
    "build_snapshot" : false,
    "lucene_version" : "9.8.0",
    "minimum_wire_compatibility_version" : "7.17.0",
    "minimum_index_compatibility_version" : "7.0.0"
  },
  "tagline" : "You Know, for Search"
}

### Steps to reproduce

```Markdown
follow README doc steps by steps.
```

**Comment by KevinHuSh** [comment]
Just localhost not port number.

**Comment by pxr1997** [comment]
That's right, thank you very much

**Comment by liuao520** [comment]
请问怎么解决的  我遇到了相同的问题

**Comment by cqray1990** [comment]
> That's right, thank you very much



> That's right, thank you very much
how solver this problem?
waht did it mean  "Just localhost not port number."?
