### ISSUE TITLE
[Bug]: TypeError: 'tuple' object does not support item assignment when opening the file

### ISSUE THREAD

**Issue by XlousZ** [infiniflow/ragflow#3596]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

none

### RAGFlow image version

85dd9fde(v0.13.0~172)

### Actual behavior

![image](https://github.com/user-attachments/assets/7e0f74d0-07dc-4cab-b228-5dfc02172c7c)

2024-11-22 08:14:46,101 ERROR    28 'tuple' object does not support item assignment
Traceback (most recent call last):
  File "/ragflow/api/apps/chunk_app.py", line 60, in list_chunk
    sres = settings.retrievaler.search(query, search.index_name(tenant_id), kb_ids, highlight=True)
  File "/ragflow/rag/nlp/search.py", line 83, in search
    res = self.dataStore.search(src, [], filters, [], orderBy, offset, limit, idx_names, kb_ids)
  File "/ragflow/rag/utils/infinity_conn.py", line 284, in search
    builder.sort(order_by_expr_list)
  File "/usr/local/lib/python3.10/dist-packages/infinity/remote_thrift/table.py", line 407, in sort
    order_by_expr[1] = False
TypeError: 'tuple' object does not support item assignment

### Expected behavior

The file parsing block is opened normally.

### Steps to reproduce

```Markdown
1. use infinity
DOC_ENGINE=${DOC_ENGINE:-infinity}
RAGFLOW_IMAGE=registry.cn-hangzhou.aliyuncs.com/infiniflow/ragflow:dev
2. docker compose -f docker-compose.yml up -d
```

**Comment by yuzhichang** [comment]
Fixed by https://github.com/infiniflow/ragflow/pull/3502
