### ISSUE TITLE
[Bug]: rag_object.retrieve() issue error

### ISSUE THREAD

**Issue by DrJasonhan** [infiniflow/ragflow#3601]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

000000

### RAGFlow image version

0.13

### Other environment information

```Markdown
Ubuntu
```

### Actual behavior

Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python-ce/helpers/pydev/pydevconsole.py", line 364, in runcode
    coro = func()
  File "<input>", line 1, in <module>
  File "/Users/shuaihan/miniconda3/envs/X/lib/python3.10/site-packages/ragflow_sdk/ragflow.py", line 181, in retrieve
    raise Exception(res.get("message"))
Exception: `datasets` is required.

### Steps to reproduce

```Markdown
本地按照https://ragflow.io/docs/dev/正常调用该函数
```

**Comment by Feiue** [comment]
Use `dataset_ids` instead of `datasets`. It's a bug in 0.13 version.
