### ISSUE TITLE
[Question]: AttributeError: 'NoneType' object has no attribute 'createIdx'

### ISSUE THREAD

**Issue by shenxiaolong57** [infiniflow/ragflow#3602]
### Describe your problem

"auto_keywords": 0, "auto_questions": 0, "raptor": {"use_raptor": false}, "chunk_token_num": 128, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "layout_recognize": true, "html4excel": false, "task_page_size": 12, "pages": [[1, 1024]]}, "name": "\u57fa\u4e8e\u7535\u78c1\u6001\u52bf\u611f\u77e5\u7684\u65e0\u4eba\u673a\u4efb\u52a1\u89c4\u5212\u7cfb\u7edf.pdf", "type": "pdf", "location": "\u57fa\u4e8e\u7535\u78c1\u6001\u52bf\u611f\u77e5\u7684\u65e0\u4eba\u673a\u4efb\u52a1\u89c4\u5212\u7cfb\u7edf.pdf", "size": 2501206, "tenant_id": "84d2cb4aa59211efa7b20242ac120003", "language": "Chinese", "embd_id": "gte-Qwen2@Xinference", "img2txt_id": "qwen-vl-max@Tongyi-Qianwen", "asr_id": "paraformer-realtime-8k-v1@Tongyi-Qianwen", "llm_id": "qwen-plus@Tongyi-Qianwen", "update_time": 1732280853557}
2024-11-22 13:07:33,628 INFO     20 172.18.0.3 - - [22/Nov/2024 13:07:33] "GET /v1/document/list?kb_id=bff82756a88511ef87430242ac120003&keywords=&page_size=10&page=1 HTTP/1.1" 200 -
2024-11-22 13:07:33,750 INFO     21 From minio(0.02659617299650563) 基于电磁态势感知的无人机任务规划系统.pdf/基于电磁态势感知的无人机任务规划系统.pdf
2024-11-22 13:07:36,986 WARNING  21 Miss outlines
2024-11-22 13:07:42,538 INFO     21 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2024-11-22T13:07:42.536939", "boot_at": "2024-11-22T13:07:12.498076", "done": 0, "failed": 0, "pending": 1, "lag": 0}
2024-11-22 13:07:48,663 INFO     20 172.18.0.3 - - [22/Nov/2024 13:07:48] "GET /v1/document/list?kb_id=bff82756a88511ef87430242ac120003&keywords=&page_size=10&page=1 HTTP/1.1" 200 -
2024-11-22 13:08:01,728 INFO     21 Chunking(28.004422505997354) 基于电磁态势感知的无人机任务规划系统.pdf/基于电磁态势感知的无人机任务规划系统.pdf done
2024-11-22 13:08:02,034 INFO     21 MINIO PUT(基于电磁态势感知的无人机任务规划系统.pdf):0.10454778800340137
2024-11-22 13:08:02,034 INFO     21 Build chunks(基于电磁态势感知的无人机任务规划系统.pdf): 28.310313132999
2024-11-22 13:08:03,716 INFO     20 172.18.0.3 - - [22/Nov/2024 13:08:03] "GET /v1/document/list?kb_id=bff82756a88511ef87430242ac120003&keywords=&page_size=10&page=1 HTTP/1.1" 200 -
2024-11-22 13:08:04,900 INFO     21 HTTP Request: POST http://10.8.0.14:9997/v1/embeddings "HTTP/1.1 200 OK"
2024-11-22 13:08:05,027 ERROR    21 LLMBundle.encode can't update token usage for 84d2cb4aa59211efa7b20242ac120003/EMBEDDING used_tokens: 155
2024-11-22 13:08:12,575 INFO     21 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2024-11-22T13:08:12.569211", "boot_at": "2024-11-22T13:07:12.498076", "done": 0, "failed": 0, "pending": 1, "lag": 0}
2024-11-22 13:08:18,758 INFO     20 172.18.0.3 - - [22/Nov/2024 13:08:18] "GET /v1/document/list?kb_id=bff82756a88511ef87430242ac120003&keywords=&page_size=10&page=1 HTTP/1.1" 200 -
2024-11-22 13:08:25,773 INFO     21 HTTP Request: POST http://10.8.0.14:9997/v1/embeddings "HTTP/1.1 200 OK"
2024-11-22 13:08:25,890 ERROR    21 LLMBundle.encode can't update token usage for 84d2cb4aa59211efa7b20242ac120003/EMBEDDING used_tokens: 1628
2024-11-22 13:08:25,905 INFO     21 Embedding elapsed(基于电磁态势感知的无人机任务规划系统.pdf): 23.86
2024-11-22 13:08:25,916 ERROR    21 handle_task got exception for task {"id": "bcc7203aa8d211ef8f130242ac120003", "doc_id": "e039572ea88511efa7b90242ac120003", "from_page": 0, "to_page": 5, "retry_count": 0, "kb_id": "bff82756a88511ef87430242ac120003", "parser_id": "presentation", "parser_config": {"auto_keywords": 0, "auto_questions": 0, "raptor": {"use_raptor": false}, "chunk_token_num": 128, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "layout_recognize": true, "html4excel": false, "task_page_size": 12, "pages": [[1, 1024]]}, "name": "\u57fa\u4e8e\u7535\u78c1\u6001\u52bf\u611f\u77e5\u7684\u65e0\u4eba\u673a\u4efb\u52a1\u89c4\u5212\u7cfb\u7edf.pdf", "type": "pdf", "location": "\u57fa\u4e8e\u7535\u78c1\u6001\u52bf\u611f\u77e5\u7684\u65e0\u4eba\u673a\u4efb\u52a1\u89c4\u5212\u7cfb\u7edf.pdf", "size": 2501206, "tenant_id": "84d2cb4aa59211efa7b20242ac120003", "language": "Chinese", "embd_id": "gte-Qwen2@Xinference", "img2txt_id": "qwen-vl-max@Tongyi-Qianwen", "asr_id": "paraformer-realtime-8k-v1@Tongyi-Qianwen", "llm_id": "qwen-plus@Tongyi-Qianwen", "update_time": 1732280853557}
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 435, in handle_task
    do_handle_task(task)
  File "/ragflow/rag/svr/task_executor.py", line 400, in do_handle_task
    init_kb(r, vector_size)
  File "/ragflow/rag/svr/task_executor.py", line 271, in init_kb
    return settings.docStoreConn.createIdx(idxnm, row["kb_id"], vector_size)
AttributeError: 'NoneType' object has no attribute 'createIdx'
爆出这个错误
并且一直卡在下面的界面
![image](https://github.com/user-attachments/assets/e932e272-332d-4eff-843d-59257fec88bf)

**Comment by yuzhichang** [comment]
It should have been fixed in main.
If not, please issue a bug report instead of question.
