### ISSUE TITLE
[Question]: TypeError: 'Knowledgebase' object is not subscriptable

### ISSUE THREAD

**Issue by x303597316** [infiniflow/ragflow#3604]
### Describe your problem

2024-11-23 16:14:20,754 INFO     21 172.25.0.6 - - [23/Nov/2024 16:14:20] "GET /v1/chunk/knowledge_graph?doc_id=46d3f5ada7d711ef83680242ac190006 HTTP/1.1" 200 -
INFO:werkzeug:172.25.0.6 - - [23/Nov/2024 16:14:20] "GET /v1/chunk/knowledge_graph?doc_id=46d3f5ada7d711ef83680242ac190006 HTTP/1.1" 200 -
2024-11-23 16:14:20,757 INFO     21 172.25.0.6 - - [23/Nov/2024 16:14:20] "GET /v1/user/info HTTP/1.1" 200 -
INFO:werkzeug:172.25.0.6 - - [23/Nov/2024 16:14:20] "GET /v1/user/info HTTP/1.1" 200 -
2024-11-23 16:14:20,759 ERROR    21 'Knowledgebase' object is not subscriptable
Traceback (most recent call last):
  File "/ragflow/api/apps/chunk_app.py", line 53, in list_chunk
    kb_ids = KnowledgebaseService.get_kb_ids(tenant_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/.venv/lib/python3.12/site-packages/peewee.py", line 3128, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/ragflow/api/db/services/knowledgebase_service.py", line 76, in get_kb_ids
    kb_ids = [kb["id"] for kb in kbs]
              ~~^^^^^^
TypeError: 'Knowledgebase' object is not subscriptable
ERROR:ragflow:'Knowledgebase' object is not subscriptable

**Comment by x303597316** [comment]
infiniflow/ragflow:dev-slim   版本中发现

**Comment by KevinHuSh** [comment]
It's already fixed in the latest version.
