### ISSUE TITLE
[Question]: pip install "xinference[all]"报错

### ISSUE THREAD

**Issue by liguoyu666** [infiniflow/ragflow#3615]
### Describe your problem

win10，conda新建了2个环境，分别为python3.11和python3.22，执行pip install "xinference[all]"安装时分别报错如下，是不支持windows吗？
python3.11环境报错：
`  Downloading http://mirrors.aliyun.com/pypi/packages/86/63/6a720dbdf4e7358baa2ab206a51693f9c6e83d174179a95539f501bd4a34/pynini-2.1.5.tar.gz (627 kB)
     ---------------------------------------- 627.6/627.6 kB 5.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-x8gi9xxy\pynini_f0f67c39303240c3bde8139df9dc00bc\setup.py", line 22, in <module>
          from Cython.Build import cythonize
      ModuleNotFoundError: No module named 'Cython'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

python3.12报错：
`            import pkg_resources
          File "C:\Users\Administrator\AppData\Local\Temp\pip-build-env-akf2gizd\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
            register_finder(pkgutil.ImpImporter, find_on_path)
                            ^^^^^^^^^^^^^^^^^^^
        AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: subprocess-exited-with-error

      Getting requirements to build wheel did not run successfully.
      exit code: 1

      See above for output.

      note: This error originates from a subprocess, and is likely not a problem with pip.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by liguoyu666** [comment]
😓发错位置了，居然不能删除，尴尬,,ԾㅂԾ,,
