### ISSUE TITLE
[Bug]: Importing the ReRank model through ollama resulted in a keyerror 'ollama'

### ISSUE THREAD

**Issue by cns-cash** [infiniflow/ragflow#3680]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

4454b33e(v0.13.0~211) slim

### RAGFlow image version

4454b33e(v0.13.0~211) slim

### Other environment information

```Markdown
windows 10
ollama version is 0.4.5
model:modelscope.cn/gpustack/bge-reranker-v2-m3-GGUF:latest
```

### Actual behavior

pic

### Steps to reproduce

```Markdown
2024-11-27 12:16:48,084 INFO     19 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2024-11-27T12:16:48.079644", "boot_at": "2024-11-27T11:09:40.928496", "pending": 0, "lag": 0, "done": 2, "failed": 2, "current": null}
2024-11-27 12:16:59,379 ERROR    20 'Ollama'
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/ragflow/.venv/lib/python3.10/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/ragflow/api/utils/api_utils.py", line 171, in decorated_function
    return func(*_args, **_kwargs)
  File "/ragflow/api/apps/llm_app.py", line 238, in add_llm
    mdl = RerankModel[factory](
KeyError: 'Ollama'
```

**Comment by KevinHuSh** [comment]
Not supported yet.

**Comment by lrq3000** [comment]
Please add support, it's the only thing that prevents using RAGflow fully offline while still preserving decent production-ready RAG results (especially in multi-needle tests).

Awesome app BTW, it's the only one that supports very long documents without context collapse.

**Comment by Feiue** [comment]
`olloma` does not provide an interface for the rerank model.

**Comment by Reza2kn** [comment]
how about from huggingface hub then? there's a ton of them hosted there..

**Comment by lrq3000** [comment]
Yes since [recently](https://www.kdnuggets.com/use-almost-any-language-model-locally-with-ollama-and-hugging-face-hub) we [can](https://huggingface.co/docs/hub/ollama) now run any HF model including rerank models, is that enough or does a specific metadata need to be provided in the response?

**Comment by Feiue** [comment]
> Yes since [recently](https://www.kdnuggets.com/use-almost-any-language-model-locally-with-ollama-and-hugging-face-hub) ollama [can](https://huggingface.co/docs/hub/ollama) now run any HF model including rerank models, is that enough or does a specific metadata need to be provided in the response?
> 
> Huggingface Hub is a good second option but it cannot run fully offline if I'm not mistaken?

Could you provide me with a code reference for calling the rerank model in Ollama, or alternatively, you could submit a PR to support it? Another option is to try deploying Xinference, which supports calling the rerank model.

**Comment by lrq3000** [comment]
Currently, they are supported like any generic model from Hugging Face Hub, there is [not yet](https://github.com/ollama/ollama/issues/3368) a specific API call parameter.

I would love to be able to contribute a PR myself, but unfortunately I am not yet experienced enough coding LLM/RAG/agentic systems yet. If nobody attempts to do it before, I will likely eventually come back to this after getting my hands on a RAG project I'm starting soon.

**Comment by which-W** [comment]
@cns-cash 
👋 Thanks so much for your suggestion — and sorry for the delay in getting back to you!

At the moment, we don’t support adding rerank models directly via Ollama. That said, you can try using rerank models locally through [Xinference](https://github.com/xorbitsai/inference), which might help in your case 🧠⚙️

We really appreciate your input and hope you’ll continue to follow the project’s progress. Feel free to share more ideas or questions anytime — we’d love to hear them! 🙌
