### ISSUE TITLE
[Bug]: PPT parsing failed

### ISSUE THREAD

**Issue by asmalluniverse** [infiniflow/ragflow#3704]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

dont now

### RAGFlow image version

0.12

### Other environment information

```Markdown
ragflow version:0.12
os type:
NAME="Rocky Linux"
VERSION="8.10 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.10 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.10"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"
```

### Actual behavior

ERROR - Chunking xxx.pptx: Proxy error(TypeInitializationException): The type initializer for 'Gdip' threw an exception. ---> DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/admin/ai-rag-flow/rag/svr/task_executor.py", line 173, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow/rag/app/presentation.py", line 105, in chunk
    for pn, (txt, img) in enumerate(ppt_parser(
                                    ^^^^^^^^^^^
  File "/home/admin/ai-rag-flow/rag/app/presentation.py", line 36, in __call__
    slide.get_thumbnail(
RuntimeError: Proxy error(TypeInitializationException): The type initializer for 'Gdip' threw an exception. ---> DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory

### Expected behavior

Can parse and retrieve PowerPoint presentations

### Steps to reproduce

```Markdown
1. Upload PPT
2. Perform analysis
3. Analysis failed with error, please refer to [Actual Behavior]
```

### Additional information

Running services on a virtual machine through Docker

**Comment by KevinHuSh** [comment]
`
sudo apt install libgdiplus
`

**Comment by asmalluniverse** [comment]
hello，I tested pptx, but ppt still doesn't work. The error message is as follows：
2024-11-29 10:27:01,886.886 - INFO - From minio(0.00644688299507834) xxx.ppt
2024-11-29 10:27:01,896.896 - ERROR - Chunking xxx.ppt: File is not a zip file
Traceback (most recent call last):
  File "/home/admin/ai-rag-flow/rag/svr/task_executor.py", line 173, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow/rag/app/presentation.py", line 105, in chunk
    for pn, (txt, img) in enumerate(ppt_parser(
                                    ^^^^^^^^^^^
  File "/home/admin/ai-rag-flow/rag/app/presentation.py", line 27, in __call__
    txts = super().__call__(fnm, from_page, to_page)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow/deepdoc/parser/ppt_parser.py", line 44, in __call__
    fnm, str) else Presentation(
                   ^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/pptx/api.py", line 31, in Presentation
    presentation_part = Package.open(pptx).main_document_part
                        ^^^^^^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/pptx/opc/package.py", line 82, in open
    return cls(pkg_file)._load()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/pptx/opc/package.py", line 160, in _load
    pkg_xml_rels, parts = _PackageLoader.load(self._pkg_file, cast("Package", self))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/pptx/opc/package.py", line 190, in load
    return cls(pkg_file, package)._load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/pptx/opc/package.py", line 194, in _load
    parts, xml_rels = self._parts, self._xml_rels
                      ^^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/pptx/util.py", line 191, in __get__
    value = self._fget(obj)
            ^^^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/pptx/opc/package.py", line 222, in _parts
    content_types = self._content_types
                    ^^^^^^^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/pptx/util.py", line 191, in __get__
    value = self._fget(obj)
            ^^^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/pptx/opc/package.py", line 207, in _content_types
    return _ContentTypeMap.from_xml(self._package_reader[CONTENT_TYPES_URI])
                                    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/pptx/opc/serialized.py", line 38, in __getitem__
    return self._blob_reader[pack_uri]
           ~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/pptx/opc/serialized.py", line 187, in __getitem__
    if pack_uri not in self._blobs:
                       ^^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/pptx/util.py", line 191, in __get__
    value = self._fget(obj)
            ^^^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/pptx/opc/serialized.py", line 194, in _blobs
    with zipfile.ZipFile(self._pkg_file, "r") as z:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.12/lib/python3.12/zipfile/__init__.py", line 1349, in __init__
    self._RealGetContents()
  File "/usr/local/python3.12/lib/python3.12/zipfile/__init__.py", line 1416, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
2024-11-29 10:27:01,898.898 - INFO - Build chunks(OPMS汇报方案.ppt): 0.018715593992965296
2024-11-29 10:27:01,937.937 - INFO - 10.213.150.74 - - [29/Nov/2024 10:27:01] "GET /v1/document/list?kb_id=35&page=1&page_size=10&personName=%25E5%25BC%25A0%25E9%259B%25A8&orgTypeCode=B0102&orgCode=50500967&personCode=yzhang281 HTTP/1.1" 200 -
2024-11-29 10:27:01,937.937 - INFO - 10.213.150.74 - - [29/Nov/2024 10:27:01] "GET /v1/document/list?kb_id=35&page=1&page_size=10&personName=%25E5%25BC%25A0%25E9%259B%25A8&orgTypeCode=B0102&orgCode=50500967&personCode=yzhang281 HTTP/1.1" 200 -
2024-11-29 10:27:08,646.646 - ERROR - 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/flask/app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/flask/app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin/ai-rag-flow-venv/virtualenvs/ragflow-ToM1Ldby-py3.12/lib/python3.12/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-11-29 10:27:08,650.650 - INFO - 10.213.9.207 - - [29/Nov/2024 10:27:08] "GET /prometheus HTTP/1.1" 200 -
2024-11-29 10:27:08,650.650 - INFO - 10.213.9.207 - - [29/Nov/2024 10:27:08] "GET /prometheus HTTP/1.1" 200 -
2024-11-29 10:27:09,119.119 - INFO - 10.213.150.74 - - [29/Nov/2024 10:27:09] "GET /v1/document/list?kb_id=35&page=1&page_size=10&personName=%25E5%25BC%25A0%25E9%259B%25A8&orgTypeCode=B0102&orgCode=50500967&personCode=yzhang281 HTTP/1.1" 200 -
2024-11-29 10:27:09,119.119 - INFO - 10.213.150.74 - - [29/Nov/2024 10:27:09] "GET /v1/document/list?kb_id=35&page=1&page_size=10&personName=%25E5%25BC%25A0%25E9%259B%25A8&orgTypeCode=B0102&orgCode=50500967&personCode=yzhang281 HTTP/1.1" 200 -

**Comment by yuzhichang** [comment]
@asmalluniverse Can you attach the bad ppt here?

**Comment by asmalluniverse** [comment]
[OPMS汇报方案.ppt.zip](https://github.com/user-attachments/files/18009349/OPMS.ppt.zip)
This is the PPT I uploaded

**Comment by yuzhichang** [comment]
It's known that python-pptx only works with .pptx and .pptm files.
Duplicated with #706.

**Comment by asmalluniverse** [comment]
I understand, it only supports files ending in pptx and pptm
