### ISSUE TITLE
[Bug]: SchemaError('type String is incompatible with expected type List(Float64)')

### ISSUE THREAD

**Issue by adzhua** [infiniflow/ragflow#3706]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

no

### RAGFlow image version

0.14

### Actual behavior

![image](https://github.com/user-attachments/assets/bdfff228-b25b-4007-bb66-ac8031c402ce)

Clicking the chunk triggers the error: SchemaError('type String is incompatible with expected type List(Float64)'), as shown in the image.

Traceback (most recent call last):
  File "/ragflow/api/apps/chunk_app.py", line 97, in get
    chunk = settings.docStoreConn.get(chunk_id, search.index_name(tenant_id), kb_ids)
  File "/ragflow/rag/utils/infinity_conn.py", line 320, in get
    res = concat_dataframes(df_list, ["id"])
  File "/ragflow/rag/utils/infinity_conn.py", line 56, in concat_dataframes
    return pl.concat(df_list)
  File "/ragflow/.venv/lib/python3.10/site-packages/polars/functions/eager.py", line 185, in concat
    out = wrap_df(plr.concat_df(elems))
polars.exceptions.SchemaError: type String is incompatible with expected type List(Float64)

### Steps to reproduce

```Markdown
as shown in the image
```

**Comment by adzhua** [comment]
v0.14.1 is ok
