### ISSUE TITLE
[Question]: report_status got exception Traceback (most recent call last):   File "/data/ragflow/rag/svr/task_executor.py", line 473, in report_status     LAG_TASKS = int(group_info["lag"])

### ISSUE THREAD

**Issue by kin1n** [infiniflow/ragflow#3716]
### Describe your problem

report_status got exception
Traceback (most recent call last):
  File "/data/ragflow/rag/svr/task_executor.py", line 473, in report_status
    LAG_TASKS = int(group_info["lag"])
拉取了0.14的版本，用的源码启动，执行到最后一步bash docker/launch_backend_service.sh的时候出现了这个错误。请问是什么问题。
![Uploading 微信截图_20241128152444.png…]()

**Comment by kin1n** [comment]
ERROR    1028041 report_status got exception
Traceback (most recent call last):
  File "/data/ragflow/rag/svr/task_executor.py", line 473, in report_status
    LAG_TASKS = int(group_info["lag"])
                    ~~~~~~~~~~^^^^^^^
KeyError: 'lag'
