### ISSUE TITLE
[Bug]: $ docker logs -f ragflow-server BUG  aise this errors

### ISSUE THREAD

**Issue by cqray1990** [infiniflow/ragflow#3723]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

v0.14.0

### RAGFlow image version

v0.14.0

### Other environment information

```Markdown
ubantu 20.04
```

### Actual behavior

    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 696, in _connect
    for res in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 226, in get_unacked_for
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error -3 connecting to redis:6379. Temporary failure in name resolution.
2024-11-28 19:43:50,751 ERROR    18 RedisDB.queue_consumer rag_flow_svr_queue got exception: Error -3 connecting to redis:6379. Temporary failure in name resolution.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 696, in _connect
    for res in socket.getaddrinfo(
  File "/usr/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 195, in queue_consumer
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error -3 connecting to redis:6379. Temporary failure in name resolution.
2024-11-28 19:43:51,754 ERROR    18 RedisDB.get_unacked_for task_consumer_0 got exception: Error 111 connecting to redis:6379. Connection refused.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 728, in _connect
    raise err
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 716, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 226, in get_unacked_for
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error 111 connecting to redis:6379. Connection refused.
2024-11-28 19:43:51,757 ERROR    18 RedisDB.queue_consumer rag_flow_svr_queue got exception: Error 111 connecting to redis:6379. Connection refused.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 302, in connect
    sock = self.retry.call_with_retry(
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/retry.py", line 62, in call_with_retry
    return do()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 303, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 728, in _connect
    raise err
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 716, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/rag/utils/redis_conn.py", line 195, in queue_consumer
    group_info = self.REDIS.xinfo_groups(queue_name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/commands/core.py", line 3810, in xinfo_groups
    return self.execute_command("XINFO GROUPS", name)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/client.py", line 564, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 1107, in get_connection
    connection.connect()
  File "/ragflow/.venv/lib/python3.10/site-packages/valkey/connection.py", line 308, in connect
    raise ConnectionError(self._error_message(e))
valkey.exceptions.ConnectionError: Error 111 connecting to redis:6379. Connection refused.
2024-11-28 19:43:54,894 WARNING  18 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2024-11-28 19:43:54,895 INFO     18 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2024-11-28T19:43:54.884982", "boot_at": "2024-11-28T19:20:23.686996", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2024-11-28 19:44:00,554 INFO     10035 
        ____   ___    ______ ______ __               
       / __ \ /   |  / ____// ____// /____  _      __
      / /_/ // /| | / / __ / /_   / // __ \| | /| / /
     / _, _// ___ |/ /_/ // __/  / // /_/ /| |/ |/ / 
    /_/ |_|/_/  |_|\____//_/    /_/ \____/ |__/|__/                             

    
2024-11-28 19:44:00,555 INFO     10035 RAGFlow version: 57208d8e(v0.14.0~20) slim
2024-11-28 19:44:00,555 INFO     10035 project base: /ragflow
2024-11-28 19:44:00,555 INFO     10035 Current configs, from /ragflow/conf/service_conf.yaml:
	ragflow: {'host': '0.0.0.0', 'http_port': 9380}
	mysql: {'name': 'rag_flow', 'user': 'root', 'password': 'infini_rag_flow', 'host': 'mysql', 'port': 3306, 'max_connections': 100, 'stale_timeout': 30}
	minio: {'user': 'rag_flow', 'password': 'infini_rag_flow', 'host': 'minio:9000'}
	es: {'hosts': 'http://es01:9200', 'username': 'elastic', 'password': 'infini_rag_flow'}
	infinity: {'uri': 'infinity:23817', 'db_name': 'default_db'}
	redis: {'db': 1, 'password': 'infini_rag_flow', 'host': 'redis:6379'}
2024-11-28 19:44:00,555 INFO     10035 Use Elasticsearch http://es01:9200 as the doc engine.
2024-11-28 19:44:00,563 INFO     10035 GET http://es01:9200/ [status:200 duration:0.007s]
2024-11-28 19:44:00,567 INFO     10035 HEAD http://es01:9200/ [status:200 duration:0.003s]
2024-11-28 19:44:00,568 INFO     10035 Elasticsearch http://es01:9200 is healthy.
2024-11-28 19:44:00,576 WARNING  10035 Load term.freq FAIL!
2024-11-28 19:44:00,579 WARNING  10035 Realtime synonym is disabled, since no redis connection.
2024-11-28 19:44:00,583 WARNING  10035 Load term.freq FAIL!
2024-11-28 19:44:00,586 WARNING  10035 Realtime synonym is disabled, since no redis connection.
2024-11-28 19:44:08,474 INFO     10035 init web data success:6.52615761756897
2024-11-28 19:44:08,477 INFO     10035 RAGFlow HTTP server start...
2024-11-28 19:44:08,481 INFO     10035 WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9380
 * Running on http://172.18.0.3:9380
2024-11-28 19:44:08,481 INFO     10035 Press CTRL+C to quit
2024-11-28 19:44:24,916 WARNING  18 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2024-11-28 19:44:24,917 INFO     18 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2024-11-28T19:44:24.916002", "boot_at": "2024-11-28T19:20:23.686996", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}

why raise this errors?

and then add ollama LLM:
hint : 102
Fail to access model(llama3.2:1b).**ERROR**: [Errno 111] Connection refused

### Steps to reproduce

```Markdown
$ cd ragflow/docker
$ docker compose -f docker-compose.yml up -d
$ docker logs -f ragflow-server
```

**Comment by JinHai-CN** [comment]
It seems the components of RAGFlow are not in healthy status. Would you please check their status?

**Comment by cqray1990** [comment]
> It seems the components of RAGFlow are not in healthy status. Would you please check their status? You also can check the status of components in RAGFlow system page of UI.

how to check? i do this step one by on by as repo, and after pull images then excute docker logs -f ragflow-server,. and raise errors

**Comment by JinHai-CN** [comment]
1. https://ragflow.io/docs/dev/run_health_check
2. https://ragflow.io/docs/dev/faq#how-to-check-the-status-of-each-component-in-ragflow

**Comment by cqray1990** [comment]
> 1. https://ragflow.io/docs/dev/run_health_check
> 
>     2. https://ragflow.io/docs/dev/faq#how-to-check-the-status-of-each-component-in-ragflow

![图片](https://github.com/user-attachments/assets/cde6f819-25cd-4c99-957e-ddb5d27cf2a6)


![Screenshot 2024-11-29 at 11-23-07 RAGFlow](https://github.com/user-attachments/assets/e61cd33a-fc5f-4fa3-bb08-6872bddeb2de)
 add ollama local model always wrong

**Comment by JinHai-CN** [comment]
Have you check the document?
https://ragflow.io/docs/dev/deploy_local_llm#deploy-a-local-model-using-ollama

**Comment by cqray1990** [comment]
> Have you check the document? https://ragflow.io/docs/dev/deploy_local_llm#deploy-a-local-model-using-ollama

yes, i check this doc to install, i have not ideal about this error. i test http://localhost:11434 in web,  Ollama is running

**Comment by JinHai-CN** [comment]
NOTE
- If your Ollama and RAGFlow run on the same machine, use http://localhost:11434 as base URL.
- If your Ollama and RAGFlow run on the same machine and Ollama is in Docker, use http://host.docker.internal:11434 as base URL.
- If your Ollama runs on a different machine from RAGFlow, use http://<IP_OF_OLLAMA_MACHINE>:11434 as base URL.

**Comment by cqray1990** [comment]
> Try http://host.docker.internal:11434

i already have try this.

**Comment by JinHai-CN** [comment]
1. Make sure Ollama is running and you can access it from web browser.
2. If you start RAGFlow in docker, RAGFlow will try to connect Ollama deployed LLM by a URL. This URL: http://host.docker.internal:11434/ is the host machine address which can be access by RAGFlow in docker.
3. If 2 is failed. You can try to add a LLM SaaS, such as OpenAI key ... to check if RAGFlow works well. If RAGFlow is OK, the only thing you need to resolve is the network issue between RAGFlow and Ollama.

**Comment by cqray1990** [comment]
> 1. Make sure Ollama is running and you can access it from web browser.

how to test the fist step?

**Comment by cqray1990** [comment]
> 1. Make sure Ollama is running and you can access it from web browser.
> 
>     2. If you start RAGFlow in docker, RAGFlow will try to connect Ollama deployed LLM by a URL. This URL: http://host.docker.internal:11434/ is the host machine address which can be access by RAGFlow in docker.
> 
>     3. If 2 is failed. You can try to add a LLM SaaS, such as OpenAI key ... to check if RAGFlow works well. If RAGFlow is OK, the only issue you need to care about is the connection between RAGFlow and Ollama.

1.Make sure Ollama is running and you can access it from web browser.

how to test the fist step?

**Comment by cqray1990** [comment]
> > > 1. Make sure Ollama is running and you can access it from web browser.
> > >    
> > >    2. If you start RAGFlow in docker, RAGFlow will try to connect Ollama deployed LLM by a URL. This URL: http://host.docker.internal:11434/ is the host machine address which can be access by RAGFlow in docker.
> > >    3. If 2 is failed. You can try to add a LLM SaaS, such as OpenAI key ... to check if RAGFlow works well. If RAGFlow is OK, the only issue you need to care about is the connection between RAGFlow and Ollama.
> > 
> > 
> > 1.Make sure Ollama is running and you can access it from web browser.
> > how to test the fist step?
> 
> Check Ollama documents
thank you so much, i just use http://localhost:11434 to test ,and web brower print  Ollama is running as official said

**Comment by JinHai-CN** [comment]
Try to access http://host.docker.internal:11434/ from Docker environment.

**Comment by Snify89** [comment]
Try adding the ragflow network to your ollama und use the containers name to access.
OLLAMA_HOST needs to be "0.0.0.0" (for all IP bindings).

**Comment by yuzhichang** [comment]
Lauhch ollama and ensure it listen on `0.0.0.0`:
```
zhichyu@germ:~/ollama/bin$ OLLAMA_HOST=0.0.0.0:11434 ./ollama serve
time=2024-11-30T20:36:09.700+08:00 level=INFO source=routes.go:1248 msg="Listening on [::]:11434 (version 0.4.6)"
```

Chech if it's reachable from inside ragflow-server container:
```
zhichyu@germ:~/ollama/bin$ docker exec -it ragflow-server bash
root@8136b8c3e914:/ragflow# curl  http://host.docker.internal:11434/
Ollama is running
```

**Comment by yuzhichang** [comment]
Another ollama issue is, I cannot add `llama3.2` as the embedding and the chat model at the same time. Looks like a frontend issue. @cike8899

**Comment by ccl-private** [comment]
The linux version of ollama, which install by "curl -fsSL https://ollama.com/install.sh | sh", will create a server.
add OLLAMA_HOST here: /etc/systemd/system/ollama.service
```
[Unit]
Description=Ollama Service
After=network-online.target
 
[Service]
Environment="OLLAMA_HOST=0.0.0.0:11434"
ExecStart=/usr/bin/ollama serve
User=ollama
Group=ollama
Restart=always
RestartSec=3
 
[Install]
WantedBy=default.target
```
and restart ollama
sudo systemctl daemon-reload
sudo systemctl restart ollama

**Comment by raykin** [comment]
Run below if you need sudo to launch custom binary for unsupported GPU.
```shell
OLLAMA_HOST=0.0.0.0:11434 sudo -E custom-built-ollama serve"
```
