### ISSUE TITLE
[Bug]: Can't edit chunk(s)

### ISSUE THREAD

**Issue by Snify89** [infiniflow/ragflow#3729]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

834c4d81f38d18704684f0d74ec235368b080023
cloned via ?
6fb1a181aa18216150de1a5c595b71d3470fca5f

### RAGFlow image version

964a6f4e(v0.14.0~30) full

### Actual behavior

When I try to open the chunk edit form/window to add keywords or edit a chunk, I encounter an empty chunk textarea with an error: AttributeError("'str' object has no attribute 'args'")

![Unbenannt](https://github.com/user-attachments/assets/5ca702df-57a5-4c57-a051-fdf7cc3676ad)

### Steps to reproduce

```Markdown
Not sure. I must try it first. Might get back later here to give a better description.
```

### Additional information

Let me know if you need any more information. Thank you in advance for looking into this!

**Comment by Snify89** [comment]
> @Snify89 What document engine you are using ? Infinity or Elasticsearch?
> 
> Would you please also provide the log of RAGFlow server?
> 
> #3727 #3709 #3718 Fix several chunk related issues.

Thank you for your answer.
I have cloned from the 6fb1a181aa18216150de1a5c595b71d3470fca5f commit.
From then on I use these 2 from time to time

docker compose -f docker/docker-compose.yml pull
docker compose -f docker/docker-compose.yml up -d

the only change is .env
RAGFLOW_IMAGE=infiniflow/ragflow:dev

I use elastisearch.


> ragflow-server  | AttributeError: 'str' object has no attribute 'args'
ragflow-server  | 2024-11-28 23:33:08,799 INFO     16 172.18.0.6 - - [28/Nov/2024 23:33:08] "GET /v1/kb/detail?kb_id=4c940f92acfd11efbc3a0242ac120006 HTTP/1.1" 200 -
ragflow-server  | 2024-11-28 23:33:08,802 INFO     16 172.18.0.6 - - [28/Nov/2024 23:33:08] "GET /v1/chunk/get?chunk_id=dc2e773e4733320c57481ea4e78e5da3 HTTP/1.1" 200 -
ragflow-server  | 2024-11-28 23:33:08,811 INFO     16 POST http://es01:9200/ragflow_efc7f36eac9d11ef855f0242ac120006/_search [status:200 duration:0.008s]
ragflow-server  | 2024-11-28 23:33:08,814 INFO     16 172.18.0.6 - - [28/Nov/2024 23:33:08] "GET /v1/chunk/knowledge_graph?doc_id=b45da274ad0111ef84b50242ac120006 HTTP/1.1" 200 -
ragflow-server  | 2024-11-28 23:33:08,816 INFO     16 POST http://es01:9200/ragflow_efc7f36eac9d11ef855f0242ac120006/_search [status:200 duration:0.009s]
ragflow-server  | 2024-11-28 23:33:08,821 INFO     16 172.18.0.6 - - [28/Nov/2024 23:33:08] "POST /v1/chunk/list HTTP/1.1" 200 -
ragflow-server  | 2024-11-28 23:33:12,163 INFO     16 172.18.0.6 - - [28/Nov/2024 23:33:12] "GET /v1/user/info HTTP/1.1" 200 -
ragflow-server  | 2024-11-28 23:33:12,189 INFO     16 GET http://es01:9200/ragflow_8ed83f2cacc111ef974c0242ac120006/_doc/dc2e773e4733320c57481ea4e78e5da3?_source=true [status:404 duration:0.007s]
ragflow-server  | 2024-11-28 23:33:12,190 ERROR    16 Chunk not found
ragflow-server  | NoneType: None
ragflow-server  | 2024-11-28 23:33:12,190 ERROR    16 'str' object has no attribute 'args'
ragflow-server  | Traceback (most recent call last):
ragflow-server  |   File "/ragflow/api/apps/chunk_app.py", line 99, in get
ragflow-server  |     return server_error_response("Chunk not found")
ragflow-server  |   File "/ragflow/api/utils/api_utils.py", line 126, in server_error_response
ragflow-server  |     if len(e.args) > 1:
ragflow-server  | AttributeError: 'str' object has no attribute 'args'
ragflow-server  | 2024-11-28 23:33:12,203 INFO     16 172.18.0.6 - - [28/Nov/2024 23:33:12] "GET /v1/kb/detail?kb_id=4c940f92acfd11efbc3a0242ac120006 HTTP/1.1" 200 -
ragflow-server  | 2024-11-28 23:33:12,206 INFO     16 172.18.0.6 - - [28/Nov/2024 23:33:12] "GET /v1/chunk/get?chunk_id=dc2e773e4733320c57481ea4e78e5da3 HTTP/1.1" 200 -
ragflow-server  | 2024-11-28 23:33:12,214 INFO     16 POST http://es01:9200/ragflow_efc7f36eac9d11ef855f0242ac120006/_search [status:200 duration:0.009s]
ragflow-server  | 2024-11-28 23:33:12,215 INFO     16 POST http://es01:9200/ragflow_efc7f36eac9d11ef855f0242ac120006/_search [status:200 duration:0.004s]
ragflow-server  | 2024-11-28 23:33:12,222 INFO     16 172.18.0.6 - - [28/Nov/2024 23:33:12] "POST /v1/chunk/list HTTP/1.1" 200 -
ragflow-server  | 2024-11-28 23:33:12,223 INFO     16 172.18.0.6 - - [28/Nov/2024 23:33:12] "GET /v1/chunk/knowledge_graph?doc_id=b45da274ad0111ef84b50242ac120006 HTTP/1.1" 200 -

The chunks are extracted successfully and shown in the other window, where you can enable/disable it.

I haven't tested much, sorry.

Settings:
nomic embedding 1.5 (the one, that came with the image.)
Paper Chunk Method

Auto keyword 1
Auto question 1
I have glm4:9b in ollama implemented and minicpm:8b


OFF-Topic:
How is OCR done in case of PDFs/Images? 
What if there's OCR data already present and what is used, when theres no OCR layer yet?
Is it possible to use a img2text model for ocring?

**Comment by JinHai-CN** [comment]
@Snify89 v0.14.1 is released. You may use the new version to check if the issue is resolved.

**Comment by JinHai-CN** [comment]
There is a built-in OCR model, and user can't configure it, now.

**Comment by Snify89** [comment]
Thank you. The error perstisted still somehow and it said "chunk not found" instead of the other error. I have set up everything from scratch and now it works :)

**Comment by adzhua** [comment]
> @Snify89 v0.14.1 is released. You may use the new version to check if the issue is resolved.

Still unable to edit or add chunks through the chunk interface, using the Infinity document engine.

![image](https://github.com/user-attachments/assets/0fd47f51-9171-411d-98f0-3837d6957412)
Traceback (most recent call last):
  File "/ragflow/api/apps/chunk_app.py", line 237, in create
    settings.docStoreConn.insert([d], search.index_name(tenant_id), doc.kb_id)
  File "/ragflow/rag/utils/infinity_conn.py", line 361, in insert
    table_instance.insert(documents)
  File "/ragflow/.venv/lib/python3.10/site-packages/infinity/remote_thrift/table.py", line 183, in insert
    constant_expression = get_remote_constant_expr_from_python_value(value)
  File "/ragflow/.venv/lib/python3.10/site-packages/infinity/remote_thrift/utils.py", line 321, in get_remote_constant_expr_from_python_value
    raise InfinityException(ErrorCode.INVALID_EXPRESSION, f"Invalid constant type: {type(value)}")
infinity.common.InfinityException: (<ErrorCode.INVALID_EXPRESSION: 3069>, "Invalid constant type: <class 'list'>")

**Comment by adzhua** [comment]
> @Snify89 v0.14.1 is released. You may use the new version to check if the issue is resolved.
Still unable to add chunks through the chunk interface.
![image](https://github.com/user-attachments/assets/9f46564c-8c65-420b-8355-8411e04f392d)

Traceback (most recent call last):
  File "/ragflow/api/apps/chunk_app.py", line 237, in create
    settings.docStoreConn.insert([d], search.index_name(tenant_id), doc.kb_id)
  File "/ragflow/rag/utils/infinity_conn.py", line 358, in insert
    table_instance.insert(documents)
  File "/ragflow/.venv/lib/python3.10/site-packages/infinity/remote_thrift/table.py", line 183, in insert
    constant_expression = get_remote_constant_expr_from_python_value(value)
  File "/ragflow/.venv/lib/python3.10/site-packages/infinity/remote_thrift/utils.py", line 321, in get_remote_constant_expr_from_python_value
    raise InfinityException(ErrorCode.INVALID_EXPRESSION, f"Invalid constant type: {type(value)}")
infinity.common.InfinityException: (<ErrorCode.INVALID_EXPRESSION: 3069>, "Invalid constant type: <class 'list'>")

**Comment by yuzhichang** [comment]
Fixed
