### ISSUE TITLE
[Bug]: PDF file parsing error

### ISSUE THREAD

**Issue by JinHai-CN** [infiniflow/ragflow#3769]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

main

### RAGFlow image version

main

### Actual behavior

```
Process Begin At:
Sat, 30 Nov 2024 16:28:41 GMT
Process Duration:
199.76 s
Progress Msg:
Task has been received.
Page(1~13): OCR started
Page(1~13): OCR finished (19.87s)
Page(1~13): Layout analysis finished.
Page(1~13): Table analysis finished.
Page(1~13): Text merging finished
Page(1~13): [ERROR]Internal server error while chunking: list index out of range
```

### Steps to reproduce

```Markdown
1. Create a dataset with General chunking method
2. Upload file 
[art-of-commandline.pdf](https://github.com/user-attachments/files/17964752/art-of-commandline.pdf)
3. Start to parsing and chunking
```

**Comment by lizhichao999** [comment]
Has this issue been fixed in edwardelric233/ragflow:oc9?
I have the same problem locally, but it doesn't exist on https://demo.ragflow.io/.
![95d9f21a2021d550f6ecaf79a28594b](https://github.com/user-attachments/assets/24472d26-71fb-4dc8-84e7-4af2edc02b2c)
![ecc9e107caaa68c7d31f5089e3b915b](https://github.com/user-attachments/assets/548abfec-ec39-4a64-b76a-e614d7e5fa8d)

**Comment by JinHai-CN** [comment]
Use the latest version. And OC9 docker container isn't maintained officially.

**Comment by Zha-Miku** [comment]
> Use the latest version. And OC9 docker image isn't maintained officially.

I updated the ONNX model in version 1.4.1 ragflow-server of Docker with the same error

- docker logs
```sh
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 449, in handle_task
    do_handle_task(task)    # 处理任务
  File "/ragflow/rag/svr/task_executor.py", line 388, in do_handle_task
    cks = build(r) # 切片
  File "/ragflow/rag/svr/task_executor.py", line 200, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
  File "/ragflow/rag/app/manual.py", line 185, in chunk
    def chunk(filename, binary=None, from_page=0, to_page=100000,
  File "/ragflow/rag/app/manual.py", line 53, in __call__
    from timeit import default_timer as timer
  File "/ragflow/deepdoc/parser/pdf_parser.py", line 325, in _layouts_rec
    bxs = [b for b in bxs if b["text"]]
  File "/ragflow/deepdoc/vision/layout_recognizer.py", line 63, in __call__
    ]
  File "/ragflow/deepdoc/vision/recognizer.py", line 445, in __call__
    # 如果需要，输出完整的异常信息
  File "/ragflow/deepdoc/vision/recognizer.py", line 423, in postprocess
    # class_indices = np.where(class_ids == class_id)[0]
  File "/ragflow/deepdoc/vision/recognizer.py", line 424, in <listcomp>
    # class_boxes = boxes[class_indices, :]
IndexError: list index out of range
```

**Comment by thiner** [comment]
I am getting the same error:
```
   File "/ragflow/deepdoc/vision/layout_recognizer.py", line 240, in postprocess

     return [{

   File "/ragflow/deepdoc/vision/layout_recognizer.py", line 241, in <listcomp>

     "type": self.label_list[class_ids[i]].lower(),

 IndexError: list index out of range
```

**Comment by KevinHuSh** [comment]
Update the code and model at the same time.
https://huggingface.co/InfiniFlow/deepdoc/tree/main

**Comment by SukSuk1986** [comment]
when i upload a pdf file and found can't to start passing.and have a agflow IndexError('list index out of range') issue....

**Comment by xugangqiang** [comment]
Please try with the latest version.

**Comment by zpf121** [comment]
The bug has been long time, might not be valid in main branch, close it now. If you still met the issue, feel free to reopen the bug.
