### ISSUE TITLE
[Bug]: Install dev version and reingest document, lose chunks and not recovery

### ISSUE THREAD

**Issue by devMls** [infiniflow/ragflow#3883]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

dont now

### RAGFlow image version

dev

### Actual behavior

I have migrate from 14.1 to dev version for try to use voyage.

I suspect that since i have done that I lose chunks every time that I ingest a file.

Previously I ingest this htmL In several test general/law format raptor, no raptor.... : 
https://eur-lex.europa.eu/legal-content/ES/TXT/HTML/?uri=CELEX:32019R1009#d1e3138-1-1

And I always achieved ask about this table of the document

"Máxima concentración (valores límite) de contaminantes expresada en mg, en relación con el contenido total de micronutrientes expresado en kg"
![image](https://github.com/user-attachments/assets/3601c142-0471-4000-a073-ee55f6f35b19)

Since I update to new version to dev version with infinity and reingest document, This information is not in the chunks.

I fact i have rollback to previous version and new ingestion in the document is not present either.

finally I noticed that in the log of the ingest process I see:

Proceso iniciado en:
```
Thu, 05 Dec 2024 09:06:15 GMT
Duración del proceso:
52.79 s
Mensaje de progreso:
Task has been received.
Page(1~100000001): Start to parse.
Page(1~100000001): Finish parsing.
Page(1~100000001): Finished slicing files (**1321** chunks in 3.69s). Start to embedding the content.
Page(1~100000001): Finished embedding (in 42.48s)! Start to build index!
Page(1~100000001): Indexing elapsed in 4.85s.
Page(1~100000001): Done!
```

but in the KB list the documents show less chunks: 1159

![image](https://github.com/user-attachments/assets/3d1678b6-6f7a-4d67-a314-84506ed7f2a6)

### Steps to reproduce

```Markdown
try to ingest this html

https://eur-lex.europa.eu/legal-content/ES/TXT/HTML/?uri=CELEX%3A02019R1009-20240703

 with dev version an open ai embbedings large and look for this information:

Máxima concentración (valores límite) de contaminantes expresada en mg, en relación con el contenido total de micronutrientes expresado en kg
```

**Comment by devMls** [comment]
I do several test with that.

I noticed that the information only disapear with raptor.

I reproduce it with many configs (dev, infinity, elasticshearch....) law mode, general mode...

In general mode without raptor and 1024 token size I don't have problems, but when I use raptor and I want to explore the chunks of the documents I obtain a error, maybe assistant can't recieve information neither:


```
Traceback (most recent call last):

  File "/ragflow/api/apps/chunk_app.py", line 74, in list_chunk

    "positions": json.loads(sres.field[id].get("position_list", "[]")),

  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads

    return _default_decoder.decode(s)

  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode

    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode

    raise JSONDecodeError("Expecting value", s, err.value) from None

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by KevinHuSh** [comment]
It's been fixed for raptor.
Pull the latest dev version of docker image.
BTW, infinity did not store the field 'position_list', so switching between infinity and ES might cause problem.

**Comment by devMls** [comment]
Thanks @KevinHuSh 

With last version error with raptor is solved.

But I am experimienting this error in search yet:


![image](https://github.com/user-attachments/assets/05e53237-f3a8-4a1c-bc3b-0465a31d0875)


I find this trace in the log:

```
2024-12-06 10:44:05,028 INFO     15 10.0.1.141 - - [06/Dec/2024 10:44:05] "POST /v1/chunk/retrieval_test HTTP/1.1" 200 -

2024-12-06 10:44:05,140 ERROR    15 not enough values to unpack (expected 2, got 1)

Traceback (most recent call last):

  File "/ragflow/api/apps/document_app.py", line 500, in get_image

    bkt, nm = image_id.split("-")
```
