### ISSUE TITLE
[Question]: start infinity failed

### ISSUE THREAD

**Issue by ShenweiXie** [infiniflow/ragflow#3901]
### Describe your problem

Following the instructions "Switch doc engine from Elasticsearch to Infinity", error reported: service "ragflow" depends on undefined service "es01": invalid compose project. 
Using docker-compose-CN-oc9.yml

**Comment by ShenweiXie** [comment]
I've updated the oc9 docker compose file #3913, it stills reports such errors:

[WARNING] [2024-12-09 09:19:58,727] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 7 times in a row, putting on 30 second timeout
[WARNING] [2024-12-09 09:19:58,727] [_transport.perform_request] [line:395]: Retrying request after failure (attempt 2 of 3)
Traceback (most recent call last):
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/elastic_transport/_transport.py", line 328, in perform_request
    meta, raw_data = node.perform_request(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NameResolutionError(<urllib3.connection.HTTPConnection object at 0x7fa129caf550>: Failed to resolve 'es01' ([Errno -2] Name or service not known))
[WARNING] [2024-12-09 09:19:58,758] [_node_pool.mark_dead] [line:249]: Node <Urllib3HttpNode(http://es01:9200)> has failed for 8 times in a row, putting on 30 second timeout
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_broker.py", line 21, in <module>
    from api.db.db_models import Task
  File "/ragflow/api/db/db_models.py", line 33, in <module>
    from api.settings import DATABASE, stat_logger, SECRET_KEY
  File "/ragflow/api/settings.py", line 35, in <module>
    from rag.utils import ELASTICSEARCH
  File "/ragflow/rag/utils/__init__.py", line 19, in <module>
    from .es_conn import ELASTICSEARCH
  File "/ragflow/rag/utils/es_conn.py", line 457, in <module>
    ELASTICSEARCH = HuEs()
                    ^^^^^^
  File "/ragflow/rag/utils/__init__.py", line 12, in _singleton
    instances[key] = cls(*args, **kw)
                     ^^^^^^^^^^^^^^^^
  File "/ragflow/rag/utils/es_conn.py", line 24, in __init__
    raise Exception("Can't connect to ES cluster")
Exception: Can't connect to ES cluster

**Comment by ShenweiXie** [comment]
The problem is solved by using the latest ragflow image: swr.cn-north-4.myhuaweicloud.com/infiniflow/ragflow:dev rather than edwardelric233/ragflow:oc9
