### ISSUE TITLE
[Bug]: Unable to run.

### ISSUE THREAD

**Issue by ashunaveed** [infiniflow/ragflow#3935]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

09-12-2024 version

### RAGFlow image version

09-12-2024 version.

### Other environment information

```Markdown
Windows wsl, i7, 4060.
```

### Actual behavior

ashu@MSI:~$ cd ragflow/docker
ashu@MSI:~/ragflow/docker$ docker compose -f docker-compose.yml up -d
WARN[0000] The "HF_ENDPOINT" variable is not set. Defaulting to a blank string.
WARN[0000] The "MACOS" variable is not set. Defaulting to a blank string.
[+] Running 71/12
 ✔ mysql Pulled                                                                                                                                      421.8s
 ✔ ragflow Pulled                                                                                                                                   1148.0s
 ✔ redis Pulled                                                                                                                                      271.6s
 ✔ es01 Pulled                                                                                                                                      1195.7s
 ✔ minio Pulled                                                                                                                                      291.3s

[+] Running 10/10
 ✔ Network docker_ragflow      Created                                                                                                                 0.0s
 ✔ Volume "docker_minio_data"  Created                                                                                                                 0.0s
 ✔ Volume "docker_redis_data"  Created                                                                                                                 0.0s
 ✔ Volume "docker_esdata01"    Created                                                                                                                 0.0s
 ✔ Volume "docker_mysql_data"  Created                                                                                                                 0.0s
 ✔ Container ragflow-redis     Started                                                                                                                 1.2s
 ✔ Container ragflow-es-01     Started                                                                                                                 1.4s
 ✔ Container ragflow-mysql     Healthy                                                                                                                11.8s
 ✔ Container ragflow-minio     Started                                                                                                                 1.4s
 ✔ Container ragflow-server    Started                                                                                                                11.5s
ashu@MSI:~/ragflow/docker$ docker logs -f ragflow-server
2024-12-09 14:59:43,022 INFO     24 ragflow_server log path: /ragflow/logs/ragflow_server.log
2024-12-09 14:59:43,080 INFO     25 task_executor_0 log path: /ragflow/logs/task_executor_0.log
2024-12-09 14:59:46,528 INFO     25 init database on cluster mode successfully
2024-12-09 14:59:46,539 INFO     24 init database on cluster mode successfully
2024-12-09 14:59:53,338 INFO     24
        ____   ___    ______ ______ __
       / __ \ /   |  / ____// ____// /____  _      __
      / /_/ // /| | / / __ / /_   / // __ \| | /| / /
     / _, _// ___ |/ /_/ // __/  / // /_/ /| |/ |/ /
    /_/ |_|/_/  |_|\____//_/    /_/ \____/ |__/|__/

2024-12-09 14:59:53,338 INFO     24 RAGFlow version: v0.14.1 slim
2024-12-09 14:59:53,338 INFO     24 project base: /ragflow
2024-12-09 14:59:53,338 INFO     24 Current configs, from /ragflow/conf/service_conf.yaml:
        ragflow: {'host': '0.0.0.0', 'http_port': 9380}
        mysql: {'name': 'rag_flow', 'user': 'root', 'password': 'infini_rag_flow', 'host': 'mysql', 'port': 3306, 'max_connections': 100, 'stale_timeout': 30}
        minio: {'user': 'rag_flow', 'password': 'infini_rag_flow', 'host': 'minio:9000'}
        es: {'hosts': 'http://es01:9200', 'username': 'elastic', 'password': 'infini_rag_flow'}
        infinity: {'uri': 'infinity:23817', 'db_name': 'default_db'}
        redis: {'db': 1, 'password': 'infini_rag_flow', 'host': 'redis:6379'}
2024-12-09 14:59:53,338 INFO     24 Use Elasticsearch http://es01:9200 as the doc engine.
2024-12-09 14:59:53,400 INFO     24 GET http://es01:9200/ [status:200 duration:0.061s]
2024-12-09 14:59:53,403 INFO     24 HEAD http://es01:9200/ [status:200 duration:0.003s]
2024-12-09 14:59:53,403 INFO     24 Elasticsearch http://es01:9200 is healthy.
2024-12-09 14:59:53,405 WARNING  24 Load term.freq FAIL!
2024-12-09 14:59:53,407 WARNING  24 Realtime synonym is disabled, since no redis connection.
2024-12-09 14:59:53,409 WARNING  24 Load term.freq FAIL!
2024-12-09 14:59:53,411 WARNING  24 Realtime synonym is disabled, since no redis connection.
2024-12-09 14:59:54,038 INFO     25 generated new fontManager
2024-12-09 15:00:00,110 INFO     24 init web data success:4.293882131576538
2024-12-09 15:00:00,111 INFO     24 RAGFlow HTTP server start...
2024-12-09 15:00:00,112 INFO     24 WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9380
 * Running on http://172.18.0.6:9380
2024-12-09 15:00:00,112 INFO     24 Press CTRL+C to quit
2024-12-09 15:00:05,158 INFO     25 Use Elasticsearch http://es01:9200 as the doc engine.
2024-12-09 15:00:05,163 INFO     25 GET http://es01:9200/ [status:200 duration:0.004s]
2024-12-09 15:00:05,165 INFO     25 HEAD http://es01:9200/ [status:200 duration:0.002s]
2024-12-09 15:00:05,165 INFO     25 Elasticsearch http://es01:9200 is healthy.
2024-12-09 15:00:05,167 WARNING  25 Load term.freq FAIL!
2024-12-09 15:00:05,169 WARNING  25 Realtime synonym is disabled, since no redis connection.
2024-12-09 15:00:05,173 WARNING  25 Load term.freq FAIL!
2024-12-09 15:00:05,175 WARNING  25 Realtime synonym is disabled, since no redis connection.
2024-12-09 15:00:05,176 WARNING  25 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2024-12-09 15:00:05,177 INFO     25 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2024-12-09T15:00:05.176803", "boot_at": "2024-12-09T15:00:05.158251", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2024-12-09 15:00:38,531 WARNING  25 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2024-12-09 15:00:38,532 INFO     25 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2024-12-09T15:00:38.530274", "boot_at": "2024-12-09T15:00:05.158251", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2024-12-09 15:01:10,299 ERROR    24 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/ragflow/.venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-12-09 15:01:10,300 INFO     24 172.18.0.1 - - [09/Dec/2024 15:01:10] "GET / HTTP/1.1" 200 -
2024-12-09 15:01:10,415 ERROR    24 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/ragflow/.venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-12-09 15:01:10,416 INFO     24 172.18.0.1 - - [09/Dec/2024 15:01:10] "GET /favicon.ico HTTP/1.1" 200 -
2024-12-09 15:01:11,871 WARNING  25 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2024-12-09 15:01:11,872 INFO     25 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2024-12-09T15:01:11.871000", "boot_at": "2024-12-09T15:00:05.158251", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}

### Steps to reproduce

```Markdown
run the commands as shown in the quick start page.
```

**Comment by KevinHuSh** [comment]
Drop the port number of the address in web browser.

**Comment by ashunaveed** [comment]
Unable to run even now: ashu@MSI:~$ cd ragflow
ashu@MSI:~/ragflow$ git checkout -f v0.14.1
Note: switching to 'v0.14.1'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 834c4d81 Update version info to v0.14.1 (#3720)
ashu@MSI:~/ragflow$ docker compose -f docker/docker-compose.yml up -d
WARN[0000] The "HF_ENDPOINT" variable is not set. Defaulting to a blank string.
WARN[0000] The "MACOS" variable is not set. Defaulting to a blank string.
[+] Running 23/23
 ✔ ragflow Pulled                                                                                                                                    573.5s
   ✔ 839854a6ab69 Download complete                                                                                                                    1.3s
   ✔ e2344640a51f Download complete                                                                                                                  221.6s
   ✔ 403ce5d08b36 Download complete                                                                                                                   46.7s
   ✔ c37a05cad8d6 Download complete                                                                                                                   90.9s
   ✔ 7bd63dcf59a1 Download complete                                                                                                                  176.2s
   ✔ 711b38c9e034 Download complete                                                                                                                    5.9s
   ✔ 372d4f10d3b9 Download complete                                                                                                                    8.8s
   ✔ 9aea191153ae Download complete                                                                                                                    7.2s
   ✔ 470ee41fe202 Download complete                                                                                                                    2.1s
   ✔ 985a2e85bb7a Download complete                                                                                                                  557.8s
   ✔ f5d5cc321706 Download complete                                                                                                                    1.8s
   ✔ fdcff575f44d Download complete                                                                                                                    2.1s
   ✔ c1b6fc231dc1 Download complete                                                                                                                    3.7s
   ✔ 3580e55f84ae Download complete                                                                                                                  253.6s
   ✔ dac6fd9158f6 Download complete                                                                                                                    5.1s
   ✔ 77cbe78222d1 Download complete                                                                                                                    3.8s
   ✔ 785e76384fd9 Download complete                                                                                                                  175.6s
   ✔ 8047b067a4a2 Download complete                                                                                                                    1.8s
   ✔ a750e0652c42 Download complete                                                                                                                  190.5s
   ✔ 1f7ad440dce8 Download complete                                                                                                                    1.8s
   ✔ dc7b4a1dec6e Download complete                                                                                                                  227.4s
   ✔ 34b264a224bf Download complete                                                                                                                  117.6s
[+] Running 5/5
 ✔ Container ragflow-server  Started                                                                                                                  15.5s
 ✔ Container ragflow-es-01   Started                                                                                                                   4.2s
 ✔ Container ragflow-redis   Started                                                                                                                   4.4s
 ✔ Container ragflow-minio   Started                                                                                                                   4.6s
 ✔ Container ragflow-mysql   Healthy                                                                                                                  15.1s
ashu@MSI:~/ragflow$ docker logs -f ragflow-server
2024-12-09 20:55:24,355 INFO     29 task_executor_0 log path: /ragflow/logs/task_executor_0.log, log levels: {'peewee': 'WARNING', 'pdfminer': 'WARNING', 'root': 'INFO'}
2024-12-09 20:55:24,355 INFO     28 ragflow_server log path: /ragflow/logs/ragflow_server.log, log levels: {'peewee': 'WARNING', 'pdfminer': 'WARNING', 'root': 'INFO'}
2024-12-09 20:55:27,756 INFO     29 init database on cluster mode successfully
2024-12-09 20:55:27,898 INFO     28 init database on cluster mode successfully
2024-12-09 20:55:34,771 INFO     28
        ____   ___    ______ ______ __
       / __ \ /   |  / ____// ____// /____  _      __
      / /_/ // /| | / / __ / /_   / // __ \| | /| / /
     / _, _// ___ |/ /_/ // __/  / // /_/ /| |/ |/ /
    /_/ |_|/_/  |_|\____//_/    /_/ \____/ |__/|__/


2024-12-09 20:55:34,771 INFO     28 RAGFlow version: 0d5486aa(v0.14.1~75) slim
2024-12-09 20:55:34,771 INFO     28 project base: /ragflow
2024-12-09 20:55:34,771 INFO     28 Current configs, from /ragflow/conf/service_conf.yaml:
        ragflow: {'host': '0.0.0.0', 'http_port': 9380}
        mysql: {'name': 'rag_flow', 'user': 'root', 'password': 'infini_rag_flow', 'host': 'mysql', 'port': 3306, 'max_connections': 100, 'stale_timeout': 30}
        minio: {'user': 'rag_flow', 'password': 'infini_rag_flow', 'host': 'minio:9000'}
        es: {'hosts': 'http://es01:9200', 'username': 'elastic', 'password': 'infini_rag_flow'}
        infinity: {'uri': 'infinity:23817', 'db_name': 'default_db'}
        redis: {'db': 1, 'password': 'infini_rag_flow', 'host': 'redis:6379'}
2024-12-09 20:55:34,771 INFO     28 Use Elasticsearch http://es01:9200 as the doc engine.
2024-12-09 20:55:34,835 INFO     28 GET http://es01:9200/ [status:200 duration:0.063s]
2024-12-09 20:55:34,838 INFO     28 HEAD http://es01:9200/ [status:200 duration:0.003s]
2024-12-09 20:55:34,838 INFO     28 Elasticsearch http://es01:9200 is healthy.
2024-12-09 20:55:34,840 WARNING  28 Load term.freq FAIL!
2024-12-09 20:55:34,840 WARNING  28 Missing synonym.json
2024-12-09 20:55:34,840 WARNING  28 Realtime synonym is disabled, since no redis connection.
2024-12-09 20:55:34,840 WARNING  28 Fail to load synonym
2024-12-09 20:55:34,842 WARNING  28 Load term.freq FAIL!
2024-12-09 20:55:34,842 WARNING  28 Missing synonym.json
2024-12-09 20:55:34,842 WARNING  28 Realtime synonym is disabled, since no redis connection.
2024-12-09 20:55:34,842 WARNING  28 Fail to load synonym
2024-12-09 20:55:34,843 INFO     28 MAX_CONTENT_LENGTH: 134217728
2024-12-09 20:55:34,843 INFO     28 SERVER_QUEUE_MAX_LEN: 1024
2024-12-09 20:55:34,843 INFO     28 SERVER_QUEUE_RETENTION: 3600
2024-12-09 20:55:34,843 INFO     28 MAX_FILE_COUNT_PER_USER: 0
2024-12-09 20:55:35,540 INFO     29 generated new fontManager
2024-12-09 20:55:36,184 INFO     28 init web data success:1.0612094402313232
2024-12-09 20:55:36,185 INFO     28 RAGFlow HTTP server start...
2024-12-09 20:55:36,186 INFO     28 WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:9380
 * Running on http://172.18.0.6:9380
2024-12-09 20:55:36,186 INFO     28 Press CTRL+C to quit
2024-12-09 20:55:45,615 INFO     29
  ______           __      ______                     __
 /_  __/___ ______/ /__   / ____/  _____  _______  __/ /_____  _____
  / / / __ `/ ___/ //_/  / __/ | |/_/ _ \/ ___/ / / / __/ __ \/ ___/
 / / / /_/ (__  ) ,<    / /____>  </  __/ /__/ /_/ / /_/ /_/ / /
/_/  \__,_/____/_/|_|  /_____/_/|_|\___/\___/\__,_/\__/\____/_/

2024-12-09 20:55:45,615 INFO     29 TaskExecutor: RAGFlow version: 0d5486aa(v0.14.1~75) slim
2024-12-09 20:55:45,615 INFO     29 Use Elasticsearch http://es01:9200 as the doc engine.
2024-12-09 20:55:45,620 INFO     29 GET http://es01:9200/ [status:200 duration:0.005s]
2024-12-09 20:55:45,622 INFO     29 HEAD http://es01:9200/ [status:200 duration:0.002s]
2024-12-09 20:55:45,622 INFO     29 Elasticsearch http://es01:9200 is healthy.
2024-12-09 20:55:45,625 WARNING  29 Load term.freq FAIL!
2024-12-09 20:55:45,625 WARNING  29 Missing synonym.json
2024-12-09 20:55:45,625 WARNING  29 Realtime synonym is disabled, since no redis connection.
2024-12-09 20:55:45,625 WARNING  29 Fail to load synonym
2024-12-09 20:55:45,627 WARNING  29 Load term.freq FAIL!
2024-12-09 20:55:45,628 WARNING  29 Missing synonym.json
2024-12-09 20:55:45,628 WARNING  29 Realtime synonym is disabled, since no redis connection.
2024-12-09 20:55:45,628 WARNING  29 Fail to load synonym
2024-12-09 20:55:45,628 INFO     29 MAX_CONTENT_LENGTH: 134217728
2024-12-09 20:55:45,628 INFO     29 SERVER_QUEUE_MAX_LEN: 1024
2024-12-09 20:55:45,628 INFO     29 SERVER_QUEUE_RETENTION: 3600
2024-12-09 20:55:45,628 INFO     29 MAX_FILE_COUNT_PER_USER: 0
2024-12-09 20:55:45,633 WARNING  29 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2024-12-09 20:55:45,633 INFO     29 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2024-12-09T20:55:45.633044", "boot_at": "2024-12-09T20:55:45.614980", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2024-12-09 20:56:18,390 WARNING  29 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2024-12-09 20:56:18,391 INFO     29 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2024-12-09T20:56:18.390509", "boot_at": "2024-12-09T20:55:45.614980", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
2024-12-09 20:56:24,719 ERROR    28 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/ragflow/.venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-12-09 20:56:24,720 INFO     28 172.18.0.1 - - [09/Dec/2024 20:56:24] "GET / HTTP/1.1" 200 -
2024-12-09 20:56:24,835 ERROR    28 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/ragflow/.venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-12-09 20:56:24,836 INFO     28 172.18.0.1 - - [09/Dec/2024 20:56:24] "GET /favicon.ico HTTP/1.1" 200 -
2024-12-09 20:56:43,741 ERROR    28 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/ragflow/.venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-12-09 20:56:43,742 INFO     28 172.18.0.1 - - [09/Dec/2024 20:56:43] "GET / HTTP/1.1" 200 -
2024-12-09 20:56:43,864 ERROR    28 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/ragflow/.venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2024-12-09 20:56:43,865 INFO     28 172.18.0.1 - - [09/Dec/2024 20:56:43] "GET /favicon.ico HTTP/1.1" 200 -
2024-12-09 20:56:51,145 WARNING  29 RedisDB.queue_info rag_flow_svr_queue got exception: no such key
2024-12-09 20:56:51,146 INFO     29 task_consumer_0 reported heartbeat: {"name": "task_consumer_0", "now": "2024-12-09T20:56:51.144743", "boot_at": "2024-12-09T20:55:45.614980", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": null}
^Ccontext canceled

**Comment by ashunaveed** [comment]
![image](https://github.com/user-attachments/assets/5ec756a8-2511-460c-9fb9-2f7b195fc934)

**Comment by ashunaveed** [comment]
Got it, thank you

**Comment by ashunaveed** [comment]
got it
