### ISSUE TITLE
[Question]: parsing gives error    system version : 1b817a5b(v0.14.1~62) slim

### ISSUE THREAD

**Issue by sahilsharma-tmpl** [infiniflow/ragflow#3943]
### Describe your problem

Process Begin At:
Mon, 09 Dec 2024 19:10:47 GMT
Process Duration:
1.34 s
Progress Msg:
Task has been received.
Page(1~100000001): Start to parse.
Page(1~100000001): Finish parsing.
Page(1~100000001): Generate 2 chunks
Page(1~100000001): [ERROR]Generate embedding error:list indices must be integers or slices, not tuple.    

this error is coming

**Comment by KevinHuSh** [comment]
Do you have error message in backend logs?
`docker logs -f ragflow-server`

**Comment by sahilsharma-tmpl** [comment]
[ERROR]Generate embedding error:list indices must be integers or slices, not tuple.    this is coming

**Comment by KevinHuSh** [comment]
What's the embedding model?

**Comment by sahilsharma-tmpl** [comment]
gemini text embedding004

**Comment by Leetungwei** [comment]
请问您解决了吗

**Comment by Leetungwei** [comment]
Have you solved it?

**Comment by ansarizeeshan** [comment]
@KevinHuSh I am also getting same error with Gemini
![Image](https://github.com/user-attachments/assets/f4edf3a7-d4a8-40fa-9e44-9364b9086b66)

Embedding details:
![Image](https://github.com/user-attachments/assets/800397f5-ce8c-4d0a-9ed1-01b8e9a6eff6)

**Comment by KevinHuSh** [comment]
I'm not sure about the problem. The code is a little behind.

**Comment by h3110Fr13nd** [comment]
Seems this is specifically problem in gemini text embedding. I'm getting this error too. 
I am using this image
RAGFLOW_IMAGE=infiniflow/ragflow:v0.15.1

**Comment by KevinHuSh** [comment]
Try the `nightly` version of docker image.

**Comment by aamir-gmail** [comment]
I'm getting his error too, here are the  logs "'0%', 'boost': 1}}], 'filter': [{'terms': {'kb_id': ['63447ed8906011f0b2a0ea9e0abd0de0']}}, {'bool': {'must_not': [{'range': {'available_int': {'lt': 1}}}]}}], 'boost': 0.050000000000000044}}, 'similarity': 0.2}, 'from': 0, 'size': 64, 'timeout': '600s', 'track_total_hits': True}ApiError(500, 'search_phase_execution_exception', 'Query contains too many nested clauses; maxClauseCount is set to 3377')
Traceback (most recent call last):
  File "/ragflow/rag/utils/es_conn.py", line 251, in search
    res = self.es.search(index=indexNames,
  File "/ragflow/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/utils.py", line 446, in wrapped
    return api(*args, **kwargs)
  File "/ragflow/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/__init__.py", line 3836, in search
    return self.perform_request(  # type: ignore[return-value]
  File "/ragflow/.venv/lib/python3.10/site-packages/elasticsearch/_sync/client/_base.py", line 320, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.ApiError: ApiError(500, 'search_phase_execution_exception', 'Query contains too many nested clauses; maxClauseCount is set to 3377')
2025-09-17 09:30:06,303 ERROR    62 Knowledge base retrieval error: ApiError(500, 'search_phase_execution_exception', 'Query contains too many nested clauses; maxClauseCount is set to 3377')
Traceback (most recent call last):
  File "/ragflow/api/apps/conversation_app.py", line 223, in stream
    for ans in chat(dia, msg, True, **req):
  File "/ragflow/api/db/services/dialog_service.py", line 430, in chat
    for think in reasoner.thinking(kbinfos, " ".join(questions)):
  File "/ragflow/agentic_reasoning/deep_research.py", line 221, in thinking
    self._update_chunk_info(chunk_info, kbinfos)
  File "/ragflow/agentic_reasoning/deep_research.py", line 133, in _update_chunk_info
    chunk_info[k] = kbinfos[k]
TypeError: list indices must be integers or slices, not str
2025-09-17 09:30:34,431 INFO     63 task_executor_2d0adfad07f5_0 reported heartbeat: {"name": "task_executor_2d0adfad07f5_0", "now": "2025-09-17T09:30:34.430+10:00", "boot_at": "2025-09-17T09:14:04.040+10:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": {}}
2025-09-17 09:31:04,435 INFO     63 task_executor_2d0adfad07f5_0 reported heartbeat: {"name": "task_executor_2d0adfad07f5_0", "now": "2025-09-17T09:31:04.434+10:00", "boot_at": "2025-09-17T09:14:04.040+10:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": {}}
2025-09-17 09:31:34,445 INFO     63 task_executor_2d0adfad07f5_0 reported heartbeat: {"name": "task_executor_2d0adfad07f5_0", "now": "2025-09-17T09:31:34.445+10:00", "boot_at": "2025-09-17T09:14:04.040+10:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": {}}
2025-09-17 09:32:04,449 INFO     63 task_executor_2d0adfad07f5_0 reported heartbeat: {"name": "task_executor_2d0adfad07f5_0", "now": "2025-09-17T09:32:04.448+10:00", "boot_at": "2025-09-17T09:14:04.040+10:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": {}}
2025-09-17 09:32:34,455 INFO     63 task_executor_2d0adfad07f5_0 reported heartbeat: {"name": "task_executor_2d0adfad07f5_0", "now": "2025-09-17T09:32:34.455+10:00", "boot_at": "2025-09-17T09:14:04.040+10:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": {}}
2025-09-17 09:33:04,461 INFO     63 task_executor_2d0adfad07f5_0 reported heartbeat: {"name": "task_executor_2d0adfad07f5_0", "now": "2025-09-17T09:33:04.460+10:00", "boot_at": "2025-09-17T09:14:04.040+10:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": {}}
2025-09-17 09:33:34,466 INFO     63 task_executor_2d0adfad07f5_0 reported heartbeat: {"name": "task_executor_2d0adfad07f5_0", "now": "2025-09-17T09:33:34.465+10:00", "boot_at": "2025-09-17T09:14:04.040+10:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": {}}
2025-09-17 09:34:04,470 INFO     63 task_executor_2d0adfad07f5_0 reported heartbeat: {"name": "task_executor_2d0adfad07f5_0", "now": "2025-09-17T09:34:04.469+10:00", "boot_at": "2025-09-17T09:14:04.040+10:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": {}}
2025-09-17 09:34:34,472 INFO     63 task_executor_2d0adfad07f5_0 reported heartbeat: {"name": "task_executor_2d0adfad07f5_0", "now": "2025-09-17T09:34:34.471+10:00", "boot_at": "2025-09-17T09:14:04.040+10:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": {}}
2025-09-17 09:35:04,476 INFO     63 task_executor_2d0adfad07f5_0 reported heartbeat: {"name": "task_executor_2d0adfad07f5_0", "now": "2025-09-17T09:35:04.475+10:00", "boot_at": "2025-09-17T09:14:04.040+10:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": {}}
2025-09-17 09:35:34,573 INFO     63 task_executor_2d0adfad07f5_0 reported heartbeat: {"name": "task_executor_2d0adfad07f5_0", "now": "2025-09-17T09:35:34.572+10:00", "boot_at": "2025-09-17T09:14:04.040+10:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": {}}
2025-09-17 09:36:04,578 INFO     63 task_executor_2d0adfad07f5_0 reported heartbeat: {"name": "task_executor_2d0adfad07f5_0", "now": "2025-09-17T09:36:04.577+10:00", "boot_at": "2025-09-17T09:14:04.040+10:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": {}}
2025-09-17 09:36:34,584 INFO     63 task_executor_2d0adfad07f5_0 reported heartbeat: {"name": "task_executor_2d0adfad07f5_0", "now": "2025-09-17T09:36:34.582+10:00", "boot_at": "2025-09-17T09:14:04.040+10:00", "pending": 0, "lag": 0, "done": 0, "failed": 0, "current": {}}
" My embedding model is "text-embedding-embeddinggemma-300m" running on LM Studio, perhaps which embedding to use for best results for English and other European languages

**Comment by Yannnnnnny** [comment]
Sorry for the very late reply. We’ve released many updates since then, so I wanted to check whether this issue is still happening for you.
If the issue no longer exists, feel free to close this issue. Thanks!
