### ISSUE TITLE
[Bug]: Knowledge Graph Error. Column: page_num_int doesn't exist

### ISSUE THREAD

**Issue by woodcoal** [infiniflow/ragflow#3984]
### Describe your problem

版本：v0.14.1-123-gb844ad6e

使用 knowledge_graph 时出现以下异常：

![image](https://github.com/user-attachments/assets/ed8a36d4-7a74-4d93-bab7-a9e5d190d230)

进度一直在这里不再变化，检查后台日志提示：

```log
2024-12-11 11:57:28,517 INFO     20 Embedding chunks (8.26s)
2024-12-11 11:57:28,519 INFO     20 set_progress(b6771bf4b77311ef95f40242ac130002), progress: None, progress_msg: Page(1~100000001): Embedding chunks (8.26s)
2024-12-11 11:57:28,529 INFO     20 INFINITY created table ragflow_c8a3599eb66211ef93da0242ac190003_478b745cb70411efb8f70242ac130003, vector size 1024
2024-12-11 11:57:28,533 ERROR    20 handle_task got exception for task {"id": "b6771bf4b77311ef95f40242ac130002", "doc_id": "79f05822b71811ef99a00242ac130003", "from_page": 0, "to_page": 100000000, "retry_count": 0, "kb_id": "478b745cb70411efb8f70242ac130003", "parser_id": "knowledge_graph", "parser_config": {"entity_types": ["organization", "person", "location", "event", "time"], "chunk_token_num": 4096, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "pages": [], "layout_recognize": true}, "name": "\u4eae\u5251 (7).txt", "type": "doc", "location": "\u4eae\u5251 (7).txt", "size": 177167, "tenant_id": "c8a3599eb66211ef93da0242ac190003", "language": "Chinese", "embd_id": "bge-m3@Ollama", "pagerank": 0, "img2txt_id": "minicpm-v@Ollama", "asr_id": "whisper-large-v3-turbo___OpenAI-API@OpenAI-API-Compatible", "llm_id": "qwen2.5-coder:14b@Ollama", "update_time": 1733889308216}
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 460, in handle_task
    do_handle_task(task)
  File "/ragflow/rag/svr/task_executor.py", line 430, in do_handle_task
    doc_store_result = settings.docStoreConn.insert(chunks[b:b + es_bulk_size], search.index_name(task_tenant_id), task_dataset_id)
  File "/ragflow/rag/utils/infinity_conn.py", line 373, in insert
    table_instance.insert(documents)
  File "/ragflow/.venv/lib/python3.10/site-packages/infinity/remote_thrift/table.py", line 195, in insert
    raise InfinityException(res.error_code, res.error_msg)
infinity.common.InfinityException: (3024, "Column: page_num_int doesn't exist@src/storage/meta/entry/table_entry.cpp:1298")
```

**Comment by woodcoal** [comment]
我重建 infinity，貌似好了，但是仍然包含以下错误：

```
2024-12-11 14:26:13,839 ERROR    20 error extracting graph
Traceback (most recent call last):
  File "/ragflow/graphrag/graph_extractor.py", line 128, in __call__
    result, token_count = self._process_document(text, prompt_variables)
  File "/ragflow/graphrag/graph_extractor.py", line 182, in _process_document
    raise Exception(response)
```

**Comment by Yannnnnnny** [comment]
Thanks for the update.
Just checking in — are you still experiencing this issue on the latest version? If the problem has been resolved, we can go ahead and close this issue. Otherwise, please let us know and we'll continue investigating.
