### ISSUE TITLE
 Add table support to Infinity 

### ISSUE THREAD

**Issue by adzhua** [infiniflow/ragflow#3991]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

no

### RAGFlow image version

0.14.1

### Actual behavior

If using the dataset from https://huggingface.co/datasets/InfiniFlow/text2sql, what methods should be used to parse the question_to_sql.csv, DDL.txt, and DB Description.txt files respectively?
When I use the Table method to parse question_to_sql.csv, the following error occurs:
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 449, in handle_task
    do_handle_task(task)
  File "/ragflow/rag/svr/task_executor.py", line 418, in do_handle_task
    es_r = settings.docStoreConn.insert(cks[b:b + es_bulk_size], search.index_name(r["tenant_id"]), r["kb_id"])
  File "/ragflow/rag/utils/infinity_conn.py", line 362, in insert
    table_instance.insert(documents)
  File "/ragflow/.venv/lib/python3.10/site-packages/infinity/remote_thrift/table.py", line 195, in insert
    raise InfinityException(res.error_code, res.error_msg)
infinity.common.InfinityException: (3024, "Column: what are the names of all the cities in canada\\tselect geo_name, id\\nfrom   data_commons_public_data.cybersyn.geo_index\\nwhere iso_name ilike '%can%\r_tks doesn't exist@src/storage/meta/entry/table_entry.cpp:1292")

### Steps to reproduce

```Markdown
use the Table method to parse question_to_sql.csv
```

**Comment by qiulang** [comment]
I delete the docker image and pull again but it is the same.

**Comment by yuzhichang** [comment]
@qiulang  chunk method `table` requires Elasticsearch. We plan to add `table` support to Infinity later.

**Comment by qinling0210** [comment]
Table support to Infinity has been added by https://github.com/infiniflow/ragflow/pull/12541
