### ISSUE TITLE
[Bug]: Error creating chat assistant via API

### ISSUE THREAD

**Issue by panzi** [infiniflow/ragflow#3998]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

6d19294ddc200454f37136635f73c9c803315761

### RAGFlow image version

v0.14.1 slim

### Other environment information

```Markdown
OS type: Linux
```

### Actual behavior

When I try to create a chat assistant the RAGFlow API always returns this error message:

```
The dataset 02d23930b7f011efae530242ac130006 doesn't own parsed file
```

I just created the dataset and document in the same function where I create the chat assistant.

### Expected behavior

The chat assistant should be created.

### Steps to reproduce

```Markdown
ragflow = RAGFlow(api_key=RAGFLOW_API_KEY, base_url=RAGFLOW_BASE_URL)
dataset = ragflow.create_dataset(name = dataset_name)
doc = dataset.upload_documents([{
    "displayed_name": "Products.txt",
    "blob": b"",
}])[0]
# I will add chunks via the API later
assistant = ragflow.create_chat(
    name = assistant_name,
    dataset_ids = [dataset.id],
    prompt = Chat.Prompt(ragflow, {
        "prompt": system_prompt
    })
)
```

**Comment by panzi** [comment]
No, the dataset is created the way the script in the bug report does it. I create a dataset, add an empty file, then try to create the assistant.

**Comment by Snify89** [comment]
An empty file can not be parsed, can it?
Try it with another file that has content and use the parse call before trying to access the dataset.

**Comment by panzi** [comment]
Not in the API documentation. Btw. do I need to call `dataset.async_parse_documents([doc.id])` after I added chunks to the document via `doc.add_chunk(content)`? Anyway, if I call `dataset.async_parse_documents([doc.id])` for that empty file I get:

```
Task has been received.
Page(1~100000001): Start to parse.
Page(1~100000001): [ERROR]Internal server error while chunking: [Errno 2] No such file or directory: Products.txt
```

That is an OS level error for the file not existing within the RAGFlow docker container? Something seems to be really broken.

**Comment by panzi** [comment]
And if I use the file body `b"Foo Bar\n"` and call `dataset.async_parse_documents([doc.id])` the file parses successfully, but then when trying to create the assistant I get:
```
Traceback (most recent call last):
  File "/app/src/bug_repro.py", line 61, in <module>
    assistant = ragflow.create_chat(
                ^^^^^^^^^^^^^^^^^^^^
  File "<@beartype(ragflow_sdk.ragflow.RAGFlow.create_chat) at 0x71e972efad40>", line 127, in create_chat
  File "/usr/local/lib/python3.11/site-packages/ragflow_sdk/ragflow.py", line 133, in create_chat
    raise Exception(res["message"])
Exception: 1048
```

**Comment by panzi** [comment]
Oh and getting this in the ragflow-server logs:

```
ragflow-server | 2024-12-12 06:03:50,826 INFO     17 172.19.0.8 - - [12/Dec/2024 06:03:50] "GET /api/v1/datasets/ca93a178b80b11efb2f50242ac130006/documents?id=ca9dfc0eb80b11efae530242ac130006&page=1&page_size=30&orderby=create_time&desc=True HTTP/1.1" 200 -
ragflow-server | 2024-12-12 06:03:50,832 ERROR    17 (1048, "Column 'rerank_id' cannot be null")
ragflow-server | Traceback (most recent call last):
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 3291, in execute_sql
ragflow-server |     cursor.execute(sql, params or ())
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
ragflow-server |     result = self._query(query)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
ragflow-server |     conn.query(q)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
ragflow-server |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
ragflow-server |     result.read()
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
ragflow-server |     first_packet = self.connection._read_packet()
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
ragflow-server |     packet.raise_for_error()
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
ragflow-server |     err.raise_mysql_exception(self._data)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
ragflow-server |     raise errorclass(errno, errval)
ragflow-server | pymysql.err.IntegrityError: (1048, "Column 'rerank_id' cannot be null")
ragflow-server | 
ragflow-server | During handling of the above exception, another exception occurred:
ragflow-server | 
ragflow-server | Traceback (most recent call last):
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
ragflow-server |     rv = self.dispatch_request()
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
ragflow-server |     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
ragflow-server |   File "/ragflow/api/utils/api_utils.py", line 285, in decorated_function
ragflow-server |     return func(*args, **kwargs)
ragflow-server |   File "/ragflow/api/apps/sdk/chat.py", line 123, in create
ragflow-server |     if not DialogService.save(**req):
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 3128, in inner
ragflow-server |     return fn(*args, **kwargs)
ragflow-server |   File "/ragflow/api/db/services/common_service.py", line 69, in save
ragflow-server |     sample_obj = cls.model(**kwargs).save(force_insert=True)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 6923, in save
ragflow-server |     pk = self.insert(**field_dict).execute()
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 2011, in inner
ragflow-server |     return method(self, database, *args, **kwargs)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 2082, in execute
ragflow-server |     return self._execute(database)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 2887, in _execute
ragflow-server |     return super(Insert, self)._execute(database)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 2600, in _execute
ragflow-server |     cursor = database.execute(self)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 3299, in execute
ragflow-server |     return self.execute_sql(sql, params)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 3289, in execute_sql
ragflow-server |     with __exception_wrapper__:
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 3059, in __exit__
ragflow-server |     reraise(new_type, new_type(exc_value, *exc_args), traceback)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 192, in reraise
ragflow-server |     raise value.with_traceback(tb)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 3291, in execute_sql
ragflow-server |     cursor.execute(sql, params or ())
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/cursors.py", line 153, in execute
ragflow-server |     result = self._query(query)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/cursors.py", line 322, in _query
ragflow-server |     conn.query(q)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 563, in query
ragflow-server |     self._affected_rows = self._read_query_result(unbuffered=unbuffered)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 825, in _read_query_result
ragflow-server |     result.read()
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 1199, in read
ragflow-server |     first_packet = self.connection._read_packet()
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/connections.py", line 775, in _read_packet
ragflow-server |     packet.raise_for_error()
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/protocol.py", line 219, in raise_for_error
ragflow-server |     err.raise_mysql_exception(self._data)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/pymysql/err.py", line 150, in raise_mysql_exception
ragflow-server |     raise errorclass(errno, errval)
ragflow-server | peewee.IntegrityError: (1048, "Column 'rerank_id' cannot be null")
ragflow-server | 2024-12-12 06:03:50,833 INFO     17 172.19.0.8 - - [12/Dec/2024 06:03:50] "POST /api/v1/chats HTTP/1.1" 200 -
```

**Comment by panzi** [comment]
Is there a place where these error codes are documented?

**Comment by panzi** [comment]
We got it to work doing this:
```Python
ragflow = RAGFlow(api_key=RAGFLOW_API_KEY, base_url=RAGFLOW_BASE_URL)
dataset = ragflow.create_dataset(name = dataset_name)
doc = dataset.upload_documents([{
    "displayed_name": "Products.txt",

    # File with some content other than white-space.
    # Otherwise it will say that there is no file later on.
    "blob": b"...\r\n",
}])[0]
# I will add chunks via the API later
assistant = ragflow.create_chat(
    name = assistant_name,
    dataset_ids = [dataset.id],
    prompt = Chat.Prompt(ragflow, {
        "prompt": system_prompt,

        # Explicitly pass empty string for rerank_model.
        # The documentation says this is the default, but the
        # Python client has None as the default which will
        # cause a NOT NULL constraint violation in the
        # ragflow server.
        "rerank_model": "",
    })
)
```

**Comment by Feiue** [comment]
I don't meet this problem in `ragflow:nightly` version

**Comment by wangq8** [comment]
The bug has been long time, might not be valid in main branch, close it now. If you still met the issue, free free to reopen the bug.
