### ISSUE TITLE
[Bug]: Listing all documents of dataset doesn't work

### ISSUE THREAD

**Issue by panzi** [infiniflow/ragflow#4015]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

6d19294ddc200454f37136635f73c9c803315761

### RAGFlow image version

v0.14.1 slim

### Other environment information

```Markdown
OS type: Linux
```

### Actual behavior

Calling `dataset.list_documents()` gives this error:
```
19:21:30 │ web-backend  │     docs: list[RAGFlowDocument] = dataset.list_documents()
19:21:30 │ web-backend  │                                   ^^^^^^^^^^^^^^^^^^^^^^^^
19:21:30 │ web-backend  │   File "<@beartype(ragflow_sdk.modules.dataset.DataSet.list_documents) at 0x7e25b0b83ba0>", line 133, in list_documents
19:21:30 │ web-backend  │   File "/usr/local/lib/python3.11/site-packages/ragflow_sdk/modules/dataset.py", line 57, in list_documents
19:21:30 │ web-backend  │     raise Exception(res["message"])
19:21:30 │ web-backend  │ Exception: You don't own the document None.
```
I guess this is because of the default parameter `id=None`.

### Expected behavior

Retrieving a list of all documents of the dataset.

### Steps to reproduce

```Markdown
Create a new dataset and call `dataset.list_documents()` via the Python API.
```

### Additional information

What I actually wanted to do is to find a document of a certain name. So I'd rather have a name parameter like when listing datasets anyway: `dataset.list_documents(name = "...")`

**Comment by KevinHuSh** [comment]
Pull the nightly version of docker image. It's been fixed there.

**Comment by aryan757** [comment]
same issue !!
from ragflow_sdk import RAGFlow
rag_object = RAGFlow(api_key="ragflow-xxxxxxxxxxxxxx",base_url="https://demo.ragflow.io")
rag_object.get_dataset(name="vari")

ERROR :



---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
[/usr/local/lib/python3.11/dist-packages/requests/models.py](https://localhost:8080/#) in json(self, **kwargs)
    973         try:
--> 974             return complexjson.loads(self.text, **kwargs)
    975         except JSONDecodeError as e:

6 frames
JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

JSONDecodeError                           Traceback (most recent call last)
<@beartype(ragflow_sdk.ragflow.RAGFlow.get_dataset) at 0x7c4b60ce3f60> in get_dataset(__beartype_get_violation, __beartype_conf, __beartype_func, *args, **kwargs)

<@beartype(ragflow_sdk.ragflow.RAGFlow.list_datasets) at 0x7c4b60b3c040> in list_datasets(__beartype_get_violation, __beartype_conf, __beartype_object_136663188687616, __beartype_object_377907360, __beartype_getrandbits, __beartype_func, *args, **kwargs)

[/usr/local/lib/python3.11/dist-packages/requests/models.py](https://localhost:8080/#) in json(self, **kwargs)
    976             # Catch JSON-related errors and raise as requests.JSONDecodeError
    977             # This aliases json.JSONDecodeError and simplejson.JSONDecodeError
--> 978             raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
    979 
    980     @property

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by xugangqiang** [comment]
Please try with latest version.

**Comment by panzi** [comment]
Given all the problems I convince my boss to not use RAGFlow anymore. (Which gave use a 25x to 28x speed boost on embedding too. I.e. we're not going back.)

**Comment by zpf121** [comment]
Close this bug since is has been resolved.
