### ISSUE TITLE
[Question]: My Elasticsearch service won't start

### ISSUE THREAD

**Issue by 729973389** [infiniflow/ragflow#4018]
### This is the problem in my system log：
2024-12-13 09:41:56,723 INFO     20 task_executor_0 log path: /ragflow/logs/task_executor_0.log
2024-12-13 09:41:56,725 INFO     17 ragflow_server log path: /ragflow/logs/ragflow_server.log
2024-12-13 09:42:02,940 INFO     20 init database on cluster mode successfully
2024-12-13 09:42:03,095 INFO     17 init database on cluster mode successfully
2024-12-13 09:42:17,049 INFO     17 
        ____   ___    ______ ______ __               
       / __ \ /   |  / ____// ____// /____  _      __
      / /_/ // /| | / / __ / /_   / // __ \| | /| / /
     / _, _// ___ |/ /_/ // __/  / // /_/ /| |/ |/ / 
    /_/ |_|/_/  |_|\____//_/    /_/ \____/ |__/|__/                             

    
2024-12-13 09:42:17,058 INFO     17 RAGFlow version: v0.14.1 full
2024-12-13 09:42:17,058 INFO     17 project base: /ragflow
2024-12-13 09:42:17,058 INFO     17 Current configs, from /ragflow/conf/service_conf.yaml:
        ragflow: {'host': '0.0.0.0', 'http_port': 9380}
        mysql: {'name': 'rag_flow', 'user': 'root', 'password': 'infini_rag_flow', 'host': 'mysql', 'port': 3306, 'max_connections': 100, 'stale_timeout': 30}
        minio: {'user': 'rag_flow', 'password': 'infini_rag_flow', 'host': 'minio:9000'}
        es: {'hosts': 'http://es01:9200', 'username': 'elastic', 'password': 'infini_rag_flow'}
        infinity: {'uri': 'infinity:23817', 'db_name': 'default_db'}
        redis: {'db': 1, 'password': 'infini_rag_flow', 'host': 'redis:6379'}
2024-12-13 09:42:17,058 INFO     17 Use Elasticsearch http://es01:9200 as the doc engine.
2024-12-13 09:42:20,911 INFO     20 generated new fontManager
2024-12-13 09:42:34,154 INFO     20 Use Elasticsearch http://es01:9200 as the doc engine.
2024-12-13 09:44:28,018 INFO     17 GET http://es01:9200/ [status:N/A duration:130.959s]
2024-12-13 09:44:28,027 WARNING  17 Node <Urllib3HttpNode(http://es01:9200)> has failed for 1 times in a row, putting on 1 second timeout
2024-12-13 09:44:28,028 WARNING  17 Connection timed out. Waiting Elasticsearch http://es01:9200 to be healthy.
2024-12-13 09:44:44,402 INFO     20 GET http://es01:9200/ [status:N/A duration:130.238s]
2024-12-13 09:44:44,411 WARNING  20 Node <Urllib3HttpNode(http://es01:9200)> has failed for 1 times in a row, putting on 1 second timeout
2024-12-13 09:44:44,411 WARNING  20 Connection timed out. Waiting Elasticsearch http://es01:9200 to be healthy.
2024-12-13 09:46:43,186 INFO     17 GET http://es01:9200/ [status:N/A duration:130.151s]
2024-12-13 09:46:43,195 WARNING  17 Node <Urllib3HttpNode(http://es01:9200)> has failed for 1 times in a row, putting on 1 second timeout
2024-12-13 09:46:43,195 WARNING  17 Connection timed out. Waiting Elasticsearch http://es01:9200 to be healthy.
2024-12-13 09:46:48,201 INFO     17 Resurrected node <Urllib3HttpNode(http://es01:9200)> (force=False)
2024-12-13 09:46:59,570 INFO     20 GET http://es01:9200/ [status:N/A duration:130.152s]
2024-12-13 09:46:59,573 WARNING  20 Node <Urllib3HttpNode(http://es01:9200)> has failed for 1 times in a row, putting on 1 second timeout
2024-12-13 09:46:59,573 WARNING  20 Connection timed out. Waiting Elasticsearch http://es01:9200 to be healthy.
2024-12-13 09:47:04,581 INFO     20 Resurrected node <Urllib3HttpNode(http://es01:9200)> (force=False)
2024-12-13 09:48:58,354 INFO     17 HEAD http://es01:9200/ [status:N/A duration:130.144s]
2024-12-13 09:48:58,363 WARNING  17 Node <Urllib3HttpNode(http://es01:9200)> has failed for 2 times in a row, putting on 2 second timeout
2024-12-13 09:48:58,363 ERROR    17 Elasticsearch http://es01:9200 didn't become healthy in 120s.
Traceback (most recent call last):
  File "/ragflow/api/ragflow_server.py", line 77, in <module>
    settings.init_settings()
  File "/ragflow/api/settings.py", line 167, in init_settings
    docStoreConn = rag.utils.es_conn.ESConnection()
  File "/ragflow/rag/utils/__init__.py", line 28, in _singleton
    instances[key] = cls(*args, **kw)
  File "/ragflow/rag/utils/es_conn.py", line 45, in __init__
    raise Exception(msg)
Exception: Elasticsearch http://es01:9200 didn't become healthy in 120s.
2024-12-13 09:49:01,348 INFO     441 ragflow_server log path: /ragflow/logs/ragflow_server.log
2024-12-13 09:49:07,479 INFO     441 init database on cluster mode successfully
2024-12-13 09:49:14,738 INFO     20 HEAD http://es01:9200/ [status:N/A duration:130.148s]
2024-12-13 09:49:14,747 WARNING  20 Node <Urllib3HttpNode(http://es01:9200)> has failed for 2 times in a row, putting on 2 second timeout
2024-12-13 09:49:14,747 ERROR    20 Elasticsearch http://es01:9200 didn't become healthy in 120s.
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 537, in <module>
    main()
  File "/ragflow/rag/svr/task_executor.py", line 515, in main
    settings.init_settings()
  File "/ragflow/api/settings.py", line 167, in init_settings
    docStoreConn = rag.utils.es_conn.ESConnection()
  File "/ragflow/rag/utils/__init__.py", line 28, in _singleton
    instances[key] = cls(*args, **kw)
  File "/ragflow/rag/utils/es_conn.py", line 45, in __init__
    raise Exception(msg)
Exception: Elasticsearch http://es01:9200 didn't become healthy in 120s.

this my service_conf.yaml

ragflow:
  host: ${RAGFLOW_HOST:-0.0.0.0}
  http_port: 9380
mysql:
  name: '${MYSQL_DBNAME:-rag_flow}'
  user: '${MYSQL_USER:-root}'
  password: '${MYSQL_PASSWORD:-infini_rag_flow}'
  host: '${MYSQL_HOST:-mysql}'
  port: 3306
  max_connections: 100
  stale_timeout: 30
minio:
  user: '${MINIO_USER:-rag_flow}'
  password: '${MINIO_PASSWORD:-infini_rag_flow}'
  host: '${MINIO_HOST:-minio}:9000'
es:
  hosts: 'http://${ES_HOST:-es01}:9200'
  username: '${ES_USER:-elastic}'
  password: '${ELASTIC_PASSWORD:-infini_rag_flow}'
infinity:
  uri: '${INFINITY_HOST:-infinity}:23817'
  db_name: 'default_db'
redis:
  db: 1
  password: '${REDIS_PASSWORD:-infini_rag_flow}' 
  host: '${REDIS_HOST:-redis}:6379'

this my .env
DOC_ENGINE=${DOC_ENGINE:-elasticsearch}
COMPOSE_PROFILES=${DOC_ENGINE}
STACK_VERSION=8.11.3
ES_HOST=es01
ES_PORT=1200
ELASTIC_PASSWORD=infini_rag_flow
KIBANA_PORT=6601
KIBANA_USER=rag_flow
KIBANA_PASSWORD=infini_rag_flow
MEM_LIMIT=8073741824
INFINITY_HOST=infinity
INFINITY_THRIFT_PORT=23817
INFINITY_HTTP_PORT=23820
INFINITY_PSQL_PORT=5432
MYSQL_PASSWORD=infini_rag_flow
MYSQL_HOST=mysql
MYSQL_DBNAME=rag_flow
MYSQL_PORT=5455
MINIO_HOST=minio
MINIO_CONSOLE_PORT=9001
MINIO_PORT=9000
MINIO_USER=rag_flow
MINIO_PASSWORD=infini_rag_flow
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=infini_rag_flow
SVR_HTTP_PORT=9380
RAGFLOW_IMAGE=infiniflow/ragflow:v0.14.1
TIMEZONE='Asia/Shanghai'
HF_ENDPOINT=https://hf-mirror.com

### I don't know what this is, is it my configuration?

**Comment by 385628424** [comment]
same question

**Comment by KevinHuSh** [comment]
Check the logs of ES and free disk space which is not less than 20%.
```
docker logs -f ragflow-es-01
```

**Comment by Snify89** [comment]
> Check the logs of ES and free disk space which is not less than 20%.
> 
> ```
> docker logs -f ragflow-es-01
> ```

This should be added to the FAQ.
I faced this issue as well.

**Comment by Bug-terminator** [comment]
```
cd /path/to/ragflow/conf
vim service_conf.yaml
```
chage hosts: http://es01:1200 to hosts: http://localhost:1200
