### ISSUE TITLE
[Bug]: failed to start with the error "werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server."

### ISSUE THREAD

**Issue by qiulang** [infiniflow/ragflow#4103]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

a5cf6fc5460d73ed8bbef28ad61b65139288e63d

### RAGFlow image version

failed to start

### Other environment information

```Markdown
arch
x86_64
uname -a
Linux VM-0-2-ubuntu 5.15.0-122-generic #132-Ubuntu SMP Thu Aug 29 13:45:52 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

### Actual behavior

Failed to start, running `docker logs -f ragflow-server` shows

```
 * Running on all addresses (*******)
 * Running on http://*********:9380
 * Running on http://**********:9380
2024-12-18 17:44:44,879 INFO     24 Press CTRL+C to quit
...
2024-12-18 17:47:09,695 ERROR    24 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 854, in dispatch_request
    self.raise_routing_exception(req)
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 463, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/ragflow/.venv/lib/python3.10/site-packages/werkzeug/routing/map.py", line 629, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
```

### Steps to reproduce

```Markdown
git clone 12/18's code, commit id a5cf6fc5460d73ed8bbef28ad61b65139288e63d
```

**Comment by KevinHuSh** [comment]
Strip the port number in web browser.

**Comment by qiulang** [comment]
I have no idea what you talked about ? Those are the docker log I don't even start my browser and as a matter of fact when I open browser at 127.0.0.1:9380 it does return the same error `{"code":100,"data":null,"message":"<NotFound '404: Not Found'>"}`

**Comment by JinHai-CN** [comment]
127.0.0.1:9222

**Comment by qiulang** [comment]
docker ps shows "0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp, 0.0.0.0:9380->9380/tcp, :::9380->9380/tcp“  why should 9222 work?!

**Comment by cjxsunny** [comment]
same issues

**Comment by KevinHuSh** [comment]
Just 'http://localhost' ?

**Comment by Dongzhikang** [comment]
I am on a remote server, and 127.0.0.1:9380 gave me 

{"code":100,"data":null,"message":"<NotFound '404: Not Found'>"}

Any solutions?

**Comment by liushaoqian** [comment]
> I am on a remote server, and 127.0.0.1:9380 gave me
> 
> {"code":100,"data":null,"message":"<NotFound '404: Not Found'>"}
> 
> Any solutions?

same issue ,how to solve it？

**Comment by KevinHuSh** [comment]
`127.0.0.1:9380` is not a service for Web browser.

**Comment by liushaoqian** [comment]
What is that?



---Original---
From: "Kevin ***@***.***&gt;
Date: Thu, Jan 9, 2025 12:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [infiniflow/ragflow] [Bug]: failed to start with the error"werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not foundon the server." (Issue #4103)




 
127.0.0.1:9380 is not a service for Web browser.

**Comment by KevinHuSh** [comment]
http://127.0.0.1
http://localhost

**Comment by qiulang** [comment]
Yes just the default 80 port

**Comment by goldeneave** [comment]
hey guys, did you figure that out? How did you solve the problem

**Comment by xigan-bit** [comment]
直接访问没有端口号的就可以了

**Comment by ghostsoul2001** [comment]
> I am on a remote server, and 127.0.0.1:9380 gave me
> 
> {"code":100,"data":null,"message":"<NotFound '404: Not Found'>"}
> 
> Any solutions?

问题根源是 Nginx 配置的问题：
默认配置指向了错误的目录
前端文件实际位于 /ragflow/web/dist 而不是 /ragflow/web
解决步骤：
创建新的 ragflow.conf 配置文件
移除默认的 Nginx 配置
正确配置前端静态文件路径和后端 API 代理
