### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by panzi** [infiniflow/ragflow#4139]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

a5cf6fc5460d73ed8bbef28ad61b65139288e63d

### RAGFlow image version

v0.15.0

### Other environment information

```Markdown
OS type: Linux
```

### Actual behavior

Trying to fetch a previously created session of a chat assistant by ID gives this error response:
```Python
{'code': 100, 'data': None, 'message': "KeyError('chunk_id')"}
```

### Expected behavior

Returning a list containing the one session object in question.

### Steps to reproduce

```Markdown
Use the API to create a session of a chat assistant and then fetch the session with `assistant.list_sessions(id=...)`.
```

### Additional information

Reverting to v0.14.1 fixed it.

**Comment by qust5979** [comment]
The same error, by  fetching a previously created session of Agent by ID.

**Comment by Feiue** [comment]
It has been fixed in `v0.15.1`

**Comment by panzi** [comment]
I'm still sometimes getting this with v0.15.1:

```
Error retrieving RAGFlow session 6319bc22d34411efbed00242ac120006: KeyError('chunk_id')
```

Don't have a backtrace at the moment. Adding code to log the backtrace right now. I just know it happens in this code (added the `exc_info=exc` right now):

```Python
            try:
                session = assistant.list_sessions(id=conversation_id)[0]
            except Exception as exc:
                logger.error(f"Error retrieving RAGFlow session {conversation_id}: {exc}", exc_info=exc)
                session = assistant.create_session(name=message)
```

**Comment by panzi** [comment]
Wait, that wouldn't help you anyway, because that would only be the client side trace. Looked in the `ragflow_server.log` and found this:

```Python
2025-01-15 06:34:25,190 ERROR    18 'chunk_id'
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/ragflow/.venv/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/ragflow/api/utils/api_utils.py", line 296, in decorated_function
    return func(*args, **kwargs)
  File "/ragflow/api/apps/sdk/session.py", line 202, in list_session
    "id": chunk["chunk_id"],
KeyError: 'chunk_id'
```

**Comment by panzi** [comment]
Somehow even though I've checked out the tag v0.15.1 it still runs the v0.15.0 container! Have to manually set `RAGFLOW_IMAGE=infiniflow/ragflow:v0.15.1-slim`!

**Comment by wangq8** [comment]
The bug has been long time, might not be valid in main branch, close it now. If you still met the issue, free free to reopen the bug.
