### ISSUE TITLE
[Bug]: InvalidRequestError to Voyage API when no documents are retrieved

### ISSUE THREAD

**Issue by JRamos1993** [infiniflow/ragflow#4154]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

a5cf6fc

### RAGFlow image version

1b817a5(v0.14.1~62) slim

### Other environment information

```Markdown
OS type: Linux
```

### Actual behavior

RAGFlow throws an InvalidRequestError when the Voyage API is called with no documents retrieved. This happens because RAGFlow does not properly validate and handle the scenario where there are no documents to send for re-ranking. The error message indicates that the request body is not valid JSON, specifically complaining about an empty string, empty list, or list containing empty strings for the documents argument.

### Expected behavior

RAGFlow should handle the absence of documents gracefully by not invoking the re-ranker or by passing an empty response to the user.

### Steps to reproduce

```Markdown
1. Set up RAGFlow with Voyage API integration (version 0.15.0).
2. Send a query or message to RAGFlow that results in no matched documents.
3. Observe the logs for errors during the call to voyageai.Reranking.create.
```

### Additional information

```
ragflow-server | 2024-12-20 08:23:26,761 INFO     19 error_message="The request body is not valid JSON, or some arguments were not specified properly. In particular, Error for argument 'documents': Value error, Input cannot be an empty string, empty list, or list that contains an empty string" message='Voyage API error received'
ragflow-server | Traceback (most recent call last):
ragflow-server |   File "/ragflow/api/apps/conversation_app.py", line 181, in stream
ragflow-server |     for ans in chat(dia, msg, True, **req):
ragflow-server |   File "/ragflow/api/db/services/dialog_service.py", line 214, in chat
ragflow-server |     kbinfos = retr.retrieval(" ".join(questions), embd_mdl, tenant_ids, dialog.kb_ids, 1, dialog.top_n,
ragflow-server |   File "/ragflow/rag/nlp/search.py", line 316, in retrieval
ragflow-server |     sim, tsim, vsim = self.rerank_by_model(rerank_mdl,
ragflow-server |   File "/ragflow/rag/nlp/search.py", line 282, in rerank_by_model
ragflow-server |     vtsim,_ = rerank_mdl.similarity(query, [rmSpace(" ".join(tks)) for tks in ins_tw])
ragflow-server |   File "/ragflow/api/db/services/llm_service.py", line 252, in similarity
ragflow-server |     sim, used_tokens = self.mdl.similarity(query, texts)
ragflow-server |   File "/ragflow/rag/llm/rerank_model.py", line 425, in similarity
ragflow-server |     res = self.client.rerank(
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/voyageai/client.py", line 90, in rerank
ragflow-server |     for attempt in self.retry_controller:
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 443, in __iter__
ragflow-server |     do = self.iter(retry_state=retry_state)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 376, in iter
ragflow-server |     result = action(retry_state)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 398, in <lambda>
ragflow-server |     self._add_action_func(lambda rs: rs.outcome.result())
ragflow-server |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
ragflow-server |     return self.__get_result()
ragflow-server |   File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
ragflow-server |     raise self._exception
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/voyageai/client.py", line 92, in rerank
ragflow-server |     response = voyageai.Reranking.create(
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/voyageai/api_resources/reranking.py", line 13, in create
ragflow-server |     response = super().create(*args, **kwargs)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/voyageai/api_resources/api_resource.py", line 47, in create
ragflow-server |     response = requestor.request(
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/voyageai/api_resources/api_requestor.py", line 147, in request
ragflow-server |     resp = self._interpret_response(result)
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/voyageai/api_resources/api_requestor.py", line 408, in _interpret_response
ragflow-server |     return self._interpret_response_line(
ragflow-server |   File "/ragflow/.venv/lib/python3.10/site-packages/voyageai/api_resources/api_requestor.py", line 463, in _interpret_response_line
ragflow-server |     raise self.handle_error_response(rbody, rcode, resp.data, rheaders)
ragflow-server | voyageai.error.InvalidRequestError: The request body is not valid JSON, or some arguments were not specified properly. In particular, Error for argument 'documents': Value error, Input cannot be an empty string, empty list, or list that contains an empty string``
```

**Comment by panzi** [comment]
There are multiple ways to fix this, don't know which is the proper one. E.g. replace this:
https://github.com/infiniflow/ragflow/blob/85083ad4005dedf90a5bcd9778a258822734595f/rag/llm/rerank_model.py#L424-L431
With this:
```Python
    def similarity(self, query: str, texts: list):
        rank = np.zeros(len(texts), dtype=float)
        if not texts:
            return rank, 0
        res = self.client.rerank(
            query=query, documents=texts, model=self.model_name, top_k=len(texts)
        )
        for r in res.results:
            rank[r.index] = r.relevance_score
        return rank, res.total_tokens
```
This prevents calling Voyage AI with an empty list of docuemnts.

Or replace this: https://github.com/infiniflow/ragflow/blob/85083ad4005dedf90a5bcd9778a258822734595f/rag/nlp/search.py#L283
With this:
```Python
        if not ins_tw:
            vtsim = np.zeros(0, dtype=float)
        else:
            vtsim,_ = rerank_mdl.similarity(query, [rmSpace(" ".join(tks)) for tks in ins_tw])
```
This prevents `rerank_by_model()` to call any rerank model with an empty list of documents.

Or replace this: https://github.com/infiniflow/ragflow/blob/85083ad4005dedf90a5bcd9778a258822734595f/rag/nlp/search.py#L315
With this:
```Python
        if sres.ids and page <= RERANK_PAGE_LIMIT:
```
This prevents `retrieval()` to call `rerank_by_model()` or `rerank()` if no documents matched.

**Comment by wangq8** [comment]
Close this bug since is has been resolved.
