### ISSUE TITLE
[Bug]: pdf law parsing error: IndexError: list index out of range

### ISSUE THREAD

**Issue by nexussdad** [infiniflow/ragflow#423]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

453c291

### Other environment information

```Markdown
OS type: centos 7.6
method: docker compose
```

### Actual behavior

parsing pdfs using law method, most succeeded but one failed.

check logs:

```python
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 130, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/app/laws.py", line 106, in chunk
    for txt, poss in pdf_parser(filename if not binary else binary,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/app/laws.py", line 80, in __call__
    return [(b["text"], self._line_tag(b, zoomin))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/rag/app/laws.py", line 80, in <listcomp>
    return [(b["text"], self._line_tag(b, zoomin))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/ragflow/deepdoc/parser/pdf_parser.py", line 831, in _line_tag
    while bott * ZM > self.page_images[pn[-1] - 1].size[1]:
                      ~~~~~~~~~~~~~~~~^^^^^^^^^^^^
IndexError: list index out of range
```

<img width="1661" alt="WeChatWorkScreenshot_6376b078-0847-43f2-95f4-9160730a2c0a" src="https://github.com/infiniflow/ragflow/assets/46325623/3085fb31-3aee-4d59-80a6-103642a8e7db">

![企业微信截图_1713409756480](https://github.com/infiniflow/ragflow/assets/46325623/e987bd3e-6f6f-45fa-acbc-c4c9433a4f1c)

### Steps to reproduce

```Markdown
parsing pdfs using law method.
```

**Comment by KevinHuSh** [comment]
fixed.
