### ISSUE TITLE
[Bug]: Unable to rename chat conversation

### ISSUE THREAD

**Issue by ODAncona** [infiniflow/ragflow#4269]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

noidea

### RAGFlow image version

0.15.0

### Other environment information

```Markdown
not relevant here
```

### Actual behavior

Unable to rename a chat conversation.

Error in the "POST /v1/conversation/set HTTP/1.1" 

```ValueError('Unrecognized field name: "avatar" in {\'avatar\': \'\', \'create_date\': \'Thu, 26 Dec 2024 21:08:37 GMT\', \'create_time\': 1735218517925, \'dialog_id\': \'75ad158ac38311efbc010242ac130006\', \'id\': \'3409cb0449c84ea482772ad604452eb4\', \'message\': [{\'content\': "Hi! I\'m your assistant, what can I do for you?", \'role\': \'assistant\'}```

### Expected behavior

1) do a chat conversation without avatar
2) try to rename it
3) Conversation renamed

### Steps to reproduce

```Markdown
1) do a chat conversation without avatar
2) try to rename it
3) Error is shown
```

### Additional information

"POST /v1/conversation/set HTTP/1.1" 200 -

python traceback

```
Traceback (most recent call last):
  File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 6659, in _normalize_data
    else cls._meta.combined[key])
KeyError: 'avatar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/ragflow/api/apps/conversation_app.py", line 46, in set_conversation
    if not ConversationService.update_by_id(conv_id, req):
  File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 3128, in inner
    return fn(*args, **kwargs)
  File "/ragflow/api/db/services/common_service.py", line 109, in update_by_id
    num = cls.model.update(data).where(cls.model.id == pid).execute()
  File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 6676, in update
    return ModelUpdate(cls, cls._normalize_data(__data, update))
  File "/ragflow/api/db/db_models.py", line 252, in _normalize_data
    normalized = super()._normalize_data(data, kwargs)
  File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 6662, in _normalize_data
    raise ValueError('Unrecognized field name: "%s" in %s.'
ValueError: Unrecognized field name: "avatar" in {'avatar': '', 'create_date': 'Thu, 26 Dec 2024 21:08:37 GMT', 'create_time': 1735218517925, 'dialog_id': '75ad158ac38311efbc010242ac130006', 'id': '3409cb0449c84ea482772ad604452eb4', 'message':
```

**Comment by KevinHuSh** [comment]
Pull v0.15.1. It's been fixed there.

**Comment by ODAncona** [comment]
The issue persists in version v0.15.1 

![image](https://github.com/user-attachments/assets/b17be4ef-a26a-412c-ae61-2082453f1577)

![image](https://github.com/user-attachments/assets/1a87e3c5-a7dc-4f5d-abd8-863b4e364f38)

![image](https://github.com/user-attachments/assets/39db2f0c-de19-4a4a-8527-5f9283436b33)


```ValueError('Unrecognized field name: "avatar" in {\'avatar\': \'\', \'create_date\': \'Fri, 27 Dec 2024 16:19:09 GMT\', \'create_time\': 1735287549135, \'dialog_id\': \'75ad158ac38311efbc010242ac130006\', \'id\': \'d179e1e120f145849e5bc77bf6fc5c80\', \'message\': [{\'content\': "Hi! I\'m your assistant, what can I do for you?", \'role\': \'assistant\'}, {\'content\': \'Did you check latest version?\', \'doc_ids\': [], \'id\': \'ca382d97-014b-48b6-8dc6-65f35dd2726e\', \'role\': \'user\'}, {\'content\': \'The answer you are looking for is not found in the knowledge base! However, I am trained on data up to October 2023, so I can provide information available until that time. If you are referring to a specific version of software or document, please provide more details so I can assist you better.\', \'id\': \'ca382d97-014b-48b6-8dc6-65f35dd2726e\', \'role\': \'assistant\'}], \'name\': "Because I didn\'t 🤡", \'reference\': [{\'chunks\': []}], \'update_date\': datetime.datetime(2024, 12, 27, 16, 20, 37), \'update_time\': 1735287637057, \'user_id\': None}.')```

It would be beneficial for the community and the project if contributors could maintain honest communication about the actual status of bug resolutions.

**Comment by KevinHuSh** [comment]
Pull the `nightly` version of docker image.
Do not forget to change `docker/.env` after pulling the image.
