### ISSUE TITLE
[Bug]: LookupError: Model(qwen-plus) not authorized

### ISSUE THREAD

**Issue by senovr** [infiniflow/ragflow#4278]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

4abc144d3d1ccd42a9996e0b638238685676b212

### RAGFlow image version

v0.15.0-27-g4abc144d full

### Other environment information

```Markdown
OS: ubuntu 22.04
```

### Actual behavior

I am trying to do naive chunking, and also check to generate key words and question for each chunk.
it gives the following error:
```
2024-12-28 15:53:24,703 INFO     19 set_progress(70238bf8c4f011ef80be0242ac130006), progress: None, progress_msg: Page(1~13): Start to generate keywords for every chunk ...
2024-12-28 15:53:24,775 INFO     19 set_progress(70238bf8c4f011ef80be0242ac130006), progress: -1, progress_msg: [ERROR]handle_task got exception, please check log
2024-12-28 15:53:24,982 ERROR    19 handle_task got exception for task {"id": "70238bf8c4f011ef80be0242ac130006", "doc_id": "5a53d396c4f011efacda0242ac130006", "from_page": 0, "to_page": 12, "retry_count": 0, "kb_id": "3a3d92ccc4f011ef9f420242ac130006", "parser_id": "naive", "parser_config": {"auto_keywords": 3, "auto_questions": 3, "raptor": {"use_raptor": true, "prompt": "Please summarize the following paragraphs. Be careful with the numbers, do not make things up. Paragraphs as following:\n      {cluster_content}\nThe above is the content you need to summarize.", "max_token": 256, "threshold": 0.1, "max_cluster": 64, "random_seed": 0}, "chunk_token_num": 128, "delimiter": "\\n!?;\u3002\uff1b\uff01\uff1f", "layout_recognize": true, "html4excel": false}, "name": "Doc (1) - Unknown.pdf", "type": "pdf", "location": "Doc (1) - Unknown.pdf", "size": 130643079, "tenant_id": "e3460214c34c11ef93d40242ac130006", "language": "English", "embd_id": "Losspost/stella_en_1.5b_v5:latest@Ollama", "pagerank": 0, "img2txt_id": "qwen-vl-max@Tongyi-Qianwen", "asr_id": "paraformer-realtime-8k-v1@Tongyi-Qianwen", "llm_id": "qwen-plus@Tongyi-Qianwen", "update_time": 1735372242589}
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 511, in handle_task
    do_handle_task(task)
  File "/ragflow/rag/svr/task_executor.py", line 449, in do_handle_task
    chunks = build_chunks(task, progress_callback)
  File "/ragflow/rag/svr/task_executor.py", line 262, in build_chunks
    chat_mdl = LLMBundle(task["tenant_id"], LLMType.CHAT, llm_name=task["llm_id"], lang=task["language"])
  File "/ragflow/api/db/services/llm_service.py", line 228, in __init__
    self.mdl = TenantLLMService.model_instance(
  File "/ragflow/.venv/lib/python3.10/site-packages/peewee.py", line 3128, in inner
    return fn(*args, **kwargs)
  File "/ragflow/api/db/services/llm_service.py", line 126, in model_instance
    raise LookupError("Model({}) not authorized".format(mdlnm))
LookupError: Model(qwen-plus) not authorized
```
KB configuration is below:
![image](https://github.com/user-attachments/assets/4da4aa61-4b77-4a3a-8212-4c536fdbaafb)

### Expected behavior

I completely removed the qwen-plus as chat model. I using ollama-hosted models (both for chat and for embeddings)
My expectation is that these models should be used, not the default ones.

### Steps to reproduce

```Markdown
Models preparation:

1. Remove all default models.
2. add ollama as model source.
3. add  Losspost/stella_en_1.5b_v5:latest as embedding model
4. add mistral-nemo:latest as chat model

KB creation:
Create new KB (parameters above)

Start parsing
Got an error.
```

**Comment by senovr** [comment]
I will answer this one:
In fact, to make sure that your model is used (regardless of provider), you need to "set it as default"
To achieve that, go to system model settings and make sure that correct models (both chat and embeddings) are selected.

![image](https://github.com/user-attachments/assets/eb126c50-1407-424c-80d8-c1619c9263b7)
