### ISSUE TITLE
[Bug]: Table recognizer failed: ValueError: operands could not be broadcast together with shapes  (480,960,4) (1,1,3)

### ISSUE THREAD

**Issue by fengjac** [infiniflow/ragflow#4301]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### RAGFlow workspace code commit ID

b52b0f68fc4dbf62703635ddbe27e1c97b15e927

### RAGFlow image version

b52b0f68fc4dbf62703635ddbe27e1c97b15e927(nightly)

### Other environment information

```Markdown
Windows 11
Python 3.13.1
```

### Actual behavior

Target table png file:
<img width="817" alt="1" src="https://github.com/user-attachments/assets/01834738-e3eb-48f3-8375-e99082056172" />

D:\ragflow> python deepdoc/vision/t_recognizer.py --inputs='./input/1.png' --threshold=0.2 --mode=tsr --output_dir='./output'               
Traceback (most recent call last):
  File "D:\ragflow\deepdoc\vision\t_recognizer.py", line 190, in <module>
    main(args)
    ~~~~^^^^^^
  File "D:\ragflow\deepdoc\vision\t_recognizer.py", line 52, in main
    html = get_table_html(images[i], lyt, ocr)
  File "D:\ragflow\deepdoc\vision\t_recognizer.py", line 66, in get_table_html
    boxes = ocr(np.array(img))
  File "D:\ragflow\deepdoc\vision\ocr.py", line 591, in __call__
    dt_boxes, elapse = self.text_detector(img)
                       ~~~~~~~~~~~~~~~~~~^^^^^
  File "D:\ragflow\deepdoc\vision\ocr.py", line 444, in __call__
    data = transform(data, self.preprocess_op)
  File "D:\ragflow\deepdoc\vision\ocr.py", line 35, in transform
    data = op(data)
  File "D:\ragflow\deepdoc\vision\operators.py", line 128, in __call__
    img.astype('float32') * self.scale - self.mean) / self.std
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~
ValueError: operands could not be broadcast together with shapes (480,960,4) (1,1,3)

### Expected behavior

No error

### Steps to reproduce

```Markdown
1. put the png file of table to ./input folder;
2. $ python deepdoc/vision/t_recognizer.py --inputs='./input/1.png' --threshold=0.2 --mode=tsr --output_dir='./output'
```


### Additional information

_No response_

**Comment by fengjac** [comment]
I have also updated the model files in `rag/res/deepdoc` with [this](https://huggingface.co/InfiniFlow/deepdoc/tree/main).

**Comment by zpf121** [comment]
The bug has been long time, might not be valid in main branch, close it now. If you still met the issue, feel free to reopen the bug.
