### ISSUE TITLE
[Bug]: HuParser： ZeroDivisionError: float floor division by zero

### ISSUE THREAD

**Issue by JudeZzz1997** [infiniflow/ragflow#446]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

1j78dopc

### Actual behavior

D:\Program\Anaconda\anaconda3\envs\deepdoc\python.exe "D:\Jude\study project\my_deepdoc\parser\pdf_parser.py" 
WARNING:root:Miss outlines
dt_boxes num : 12, elapsed : 0.20821523666381836
dt_boxes num : 30, elapsed : 0.24946880340576172
dt_boxes num : 66, elapsed : 0.26940345764160156
dt_boxes num : 15, elapsed : 0.41324687004089355
dt_boxes num : 34, elapsed : 0.3281736373901367
dt_boxes num : 34, elapsed : 0.28658509254455566
dt_boxes num : 38, elapsed : 0.2980356216430664
dt_boxes num : 36, elapsed : 0.2726407051086426
dt_boxes num : 40, elapsed : 0.30141472816467285
dt_boxes num : 36, elapsed : 0.3386805057525635
preprocess
Traceback (most recent call last):
  File "D:\Jude\study project\my_deepdoc\parser\pdf_parser.py", line 1177, in <module>
    ans = parser("../dataset/扫描件.pdf")
  File "D:\Jude\study project\my_deepdoc\parser\pdf_parser.py", line 1033, in __call__
    self._concat_downward()
  File "D:\Jude\study project\my_deepdoc\parser\pdf_parser.py", line 503, in _concat_downward
    dfs(boxes[0], 1)
  File "D:\Jude\study project\my_deepdoc\parser\pdf_parser.py", line 494, in dfs
    fea = self._updown_concat_features(up, down)
  File "D:\Jude\study project\my_deepdoc\parser\pdf_parser.py", line 93, in _updown_concat_features
    w = max(self.__char_width(up), self.__char_width(down))
  File "D:\Jude\study project\my_deepdoc\parser\pdf_parser.py", line 65, in __char_width
    return (c["x1"] - c["x0"]) // len(c["text"])
ZeroDivisionError: float floor division by zero

### Steps to reproduce

```Markdown
ran the HuParser class in deepdoc/parser/pdf_parser.py and parsed a scanned pdf, an ZeroDivisionError occurred
```

**Comment by KevinHuSh** [comment]
fixed
