### ISSUE TITLE
[Bug]: Unable to start Tika server

### ISSUE THREAD

**Issue by moyangjiayou** [infiniflow/ragflow#721]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

main

### Commit ID

33eaf6f

### Other environment information

```Markdown
docker install
```

### Actual behavior

2024-05-11 10:55:37,125 [MainThread  ] [ERROR]  Unable to run java; is it installed?
[ERROR] [2024-05-11 10:55:37,125] [tika.startServer] [line:669]: Unable to run java; is it installed?
2024-05-11 10:55:37,125 [MainThread  ] [ERROR]  Failed to receive startup confirmation from startServer.
[ERROR] [2024-05-11 10:55:37,125] [tika.checkTikaServer] [line:601]: Failed to receive startup confirmation from startServer.
Traceback (most recent call last):
  File "/ragflow/rag/svr/task_executor.py", line 141, in build
    cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
  File "/ragflow/rag/app/naive.py", line 159, in chunk
    doc_parsed = parser.from_buffer(binary)
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/tika/parser.py", line 65, in from_buffer
    status, response = callServer('put', serverEndpoint, '/rmeta/text', string, headers, False, config_path=config_path, requestOptions=requestOptions)
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/tika/tika.py", line 532, in callServer
    serverEndpoint = checkTikaServer(scheme, serverHost, port, tikaServerJar, classpath, config_path)       
  File "/root/miniconda3/envs/py11/lib/python3.11/site-packages/tika/tika.py", line 602, in checkTikaServer
    raise RuntimeError("Unable to start Tika server.")
RuntimeError: Unable to start Tika server.

### Steps to reproduce

```Markdown
extract excel file
```

**Comment by lim0513** [comment]
file format error? 
convert xls to xlsx

**Comment by moyangjiayou** [comment]
您好！我是莫洋，我已经收到您的来信了！

**Comment by moyangjiayou** [comment]
> file format error? 文件格式错误？ convert xls to xlsx 将xls转换为xlsx

I fixed it by installing java in container of ragflow-server。
