### ISSUE TITLE
[Bug]: Unable to parse ppt and pptx files.

### ISSUE THREAD

**Issue by dashi6174** [infiniflow/ragflow#888]
### Is there an existing issue for the same bug?

- [X] I have checked the existing issues.

### Branch name

v0.6.0

### Commit ID

170186ee4d21b72a6f18b40e1ce6a8d37e88b3b9

### Actual behavior

Unable to parse ppt and pptx files.

1. When parsing a ppttx file, the task_executor.py process crashes and exits.

2. When parsing a ppt file, there is an error in the backend.
![image](https://github.com/infiniflow/ragflow/assets/1617266/afce8a64-b966-45a7-a2aa-4d65be568f5d)

[dfasdf.pptx](https://github.com/infiniflow/ragflow/files/15404611/dfasdf.pptx)
[ppt files.zip](https://github.com/infiniflow/ragflow/files/15404685/ppt.files.zip)

### Steps to reproduce

```Markdown
none
```

**Comment by KevinHuSh** [comment]
Install these libs in the docker container: libcrypto.so.1.1  libssl.so.10 libgdiplus

**Comment by stephenlzc** [comment]
Hi, once I upload a PPTX file to RAGflow, an error message raised as, at the same time the other files are all going well.

> [ERROR]Internal server error: file type not supported yet(pdf, xlsx, doc, docx, txt supported)

here are some pics for your refenece:
<img width="1393" alt="image" src="https://github.com/infiniflow/ragflow/assets/52523593/a02f9078-db6d-4ce4-a252-1c4cf5a6f405">

<img width="1408" alt="image" src="https://github.com/infiniflow/ragflow/assets/52523593/a10ce0e5-b512-494d-b927-dc3c3cca7ead">

Here is the log from docker:

> 2024-07-04 23:53:17 ragflow-server  | [INFO] [2024-07-04 15:53:17,016] [_internal._log] [line:96]: 172.24.0.3 - - [04/Jul/2024 15:53:17] "GET /v1/document/list?kb_id=fbc4f45638e811efab260242ac180006&page=1&page_size=10 HTTP/1.1" 200 -
2024-07-04 23:53:17 ragflow-server  | [INFO] [2024-07-04 15:53:17,024] [_internal._log] [line:96]: 172.24.0.3 - - [04/Jul/2024 15:53:17] "GET /v1/user/tenant_info HTTP/1.1" 200 -
2024-07-04 23:53:17 ragflow-server  | [INFO] [2024-07-04 15:53:17,030] [_internal._log] [line:96]: 172.24.0.3 - - [04/Jul/2024 15:53:17] "GET /v1/document/list?kb_id=fbc4f45638e811efab260242ac180006&page=1&page_size=10 HTTP/1.1" 200 -
2024-07-04 23:53:19 ragflow-server  | [INFO] [2024-07-04 15:53:19,805] [_internal._log] [line:96]: 172.24.0.3 - - [04/Jul/2024 15:53:19] "POST /v1/document/run HTTP/1.1" 200 -
2024-07-04 23:53:19 ragflow-server  | [INFO] [2024-07-04 15:53:19,858] [_internal._log] [line:96]: 172.24.0.3 - - [04/Jul/2024 15:53:19] "GET /v1/document/list?kb_id=fbc4f45638e811efab260242ac180006&page=1&page_size=10 HTTP/1.1" 200 -
2024-07-04 23:53:21 ragflow-server  | [INFO] [2024-07-04 15:53:21,648] [_internal._log] [line:96]: 172.24.0.3 - - [04/Jul/2024 15:53:21] "GET /v1/document/list?kb_id=fbc4f45638e811efab260242ac180006&page=1&page_size=10 HTTP/1.1" 200 -
2024-07-04 23:53:22 ragflow-server  | Traceback (most recent call last):
2024-07-04 23:53:22 ragflow-server  |   File "/ragflow/rag/svr/task_executor.py", line 146, in build
2024-07-04 23:53:22 ragflow-server  |     cks = chunker.chunk(row["name"], binary=binary, from_page=row["from_page"],
2024-07-04 23:53:22 ragflow-server  |   File "/ragflow/rag/app/naive.py", line 263, in chunk
2024-07-04 23:53:22 ragflow-server  |     raise NotImplementedError(
2024-07-04 23:53:22 ragflow-server  | NotImplementedError: file type not supported yet(pdf, xlsx, doc, docx, txt supported)
2024-07-04 23:53:26 ragflow-server  | [INFO] [2024-07-04 15:53:26,476] [_internal._log] [line:96]: 172.24.0.3 - - [04/Jul/2024 15:53:26] "GET /v1/document/list?kb_id=fbc4f45638e811efab260242ac180006&page=1&page_size=10 HTTP/1.1" 200 -
2024-07-04 23:53:32 ragflow-server  | [INFO] [2024-07-04 15:53:32,082] [_internal._log] [line:96]: 172.24.0.3 - - [04/Jul/2024 15:53:32] "GET /v1/document/list?kb_id=fbc4f45638e811efab260242ac180006&page=1&page_size=10 HTTP/1.1" 200 -

Many Thanks.
